 'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {CsHeader} from '../components/cs-shared'
import {AccountBar} from '../components/AccountBar'
type Billing={enabled:boolean;canUpload?:boolean;complimentary?:boolean;hasCustomer?:boolean;gameCount?:number;usedBytes?:number;status?:string;paidUntil?:string}
export default function BillingPage(){
 const [data,setData]=useState<Billing|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(refresh=false){setError('');try{const r=await fetch('/api/filmroom/billing',{method:refresh?'POST':'GET'});if(r.status===401){location.assign('/filmroom/login');return}const b=await r.json();if(!r.ok)throw Error(b.error);setData(b)}catch(e){setError(e instanceof Error?e.message:'Could not load your subscription.')}}
 useEffect(()=>{void load(new URLSearchParams(window.location.search).get('checkout')==='complete')},[])
 async function open(kind:'checkout'|'portal'){setBusy(true);setError('');try{const r=await fetch(`/api/filmroom/billing/${kind}`,{method:'POST'}),b=await r.json();if(!r.ok||!b.url)throw Error(b.error||'Please try again.');location.assign(b.url)}catch(e){setError(e instanceof Error?e.message:'Please try again.');setBusy(false)}}
 return <div className="cs min-h-screen bg-[#181917] text-[#eee9df]"><CsHeader active="library" right={<AccountBar/>}/><main className="mx-auto max-w-3xl px-5 py-10"><Link href="/filmroom" className="text-sm text-[#e49269]">← Your library</Link><p className="mt-10 text-xs uppercase tracking-[.2em] text-[#aaa89f]">Film Room Coach</p><h1 className="mt-3 text-5xl font-black uppercase" style={{fontFamily:'var(--font-bc)'}}>Your film. Your advantage.</h1><p className="mt-5 text-4xl font-bold">$25<span className="text-base font-normal text-[#c9c3b8]"> USD / month</span></p><p className="mt-4 text-[#c9c3b8]">A private library for up to 50 games and 500 GB of video. Clip plays, draw on film, tag stats, and build teaching playlists.</p><p className="mt-3 text-sm text-[#aaa89f]">Try the demo before subscribing. The demo doesn’t count toward your limits. Cancel through Manage subscription; access to new uploads continues through your paid period.</p>
 {error&&<p role="alert" className="mt-6 text-red-200">{error}</p>}
 {!data?<button onClick={()=>load()} className="mt-6 min-h-11 underline">{error?'Try again':'Loading subscription…'}</button>:!data.enabled?<p className="mt-8 rounded-md border border-white/15 p-5">Subscriptions are being prepared. Checkout is not open yet.</p>:<section className="mt-8 border-t border-white/15 pt-6"><h2 className="text-xl font-bold">{data.complimentary?'Owner access':data.canUpload?'Your plan is active':data.status==='past_due'?'Payment needs attention':data.status==='unpaid'?'Payment overdue':data.status==='canceled'?'Subscription ended':data.status==='incomplete'?'Payment not completed':data.status==='incomplete_expired'?'Checkout expired':data.status==='active'?'Subscription refresh needed':'Demo access'}</h2><p className="mt-2 text-sm text-[#c9c3b8]">{data.gameCount} / 50 games · {((data.usedBytes||0)/1e9).toFixed(1)} / 500 GB</p>{data.paidUntil&&<p className="mt-2 text-sm text-[#aaa89f]">{data.canUpload?'Current paid period ends':'Billing period ends'} {new Date(data.paidUntil).toLocaleDateString()}.</p>}<div className="mt-5 flex flex-wrap gap-3">{!data.canUpload&&!data.complimentary&&<button disabled={busy} onClick={()=>open(data.hasCustomer&&data.status&&!['none','canceled','incomplete_expired'].includes(data.status)?'portal':'checkout')} className="min-h-11 rounded-md bg-[#c66a3e] px-5 font-bold text-[#181917] disabled:opacity-50">{busy?'Opening…':data.hasCustomer&&data.status&&!['none','canceled','incomplete_expired'].includes(data.status)?'Update payment':'Subscribe · $25/month'}</button>}{data.hasCustomer&&<button disabled={busy} onClick={()=>open('portal')} className="min-h-11 rounded-md border border-white/20 px-5">Manage subscription</button>}<button onClick={()=>load(true)} className="min-h-11 px-3 text-sm underline">Refresh payment status</button></div><p className="mt-4 text-xs text-[#aaa89f]">Payment confirmation can take a moment. If you just checked out, refresh your status here. Existing film remains viewable if your subscription ends.</p></section>}
 </main></div>
}
