 'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {CsHeader} from '../components/cs-shared'
import {AccountBar} from '../components/AccountBar'
import type {Clip,Player} from '@/types/filmroom'
type Result=Clip&{games:{opponent:string}|null;clip_players:{players:{name:string}|null}[]}
const field='min-h-11 rounded border border-white/20 bg-[#20211e] px-3 text-sm'
export default function ClipSearch(){
 const [q,setQ]=useState('');const [tag,setTag]=useState('');const [player,setPlayer]=useState('');const [players,setPlayers]=useState<Player[]>([]);const [clips,setClips]=useState<Result[]>([]);const [total,setTotal]=useState(0);const [page,setPage]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [retry,setRetry]=useState(0)
 useEffect(()=>{fetch('/api/filmroom/players').then(r=>{if(!r.ok)throw Error();return r.json()}).then(setPlayers).catch(()=>setError('Player filter unavailable. Reload to retry.'))},[])
 useEffect(()=>{const ac=new AbortController();setLoading(true);const timer=setTimeout(async()=>{try{const r=await fetch('/api/filmroom/clip-search?'+new URLSearchParams({q,tag,player,page:String(page)}),{signal:ac.signal});if(r.status===401){location.href='/filmroom/login';return}if(!r.ok)throw Error('Could not search clips.');const d=await r.json();setClips(d.clips);setTotal(d.total);setError('')}catch(e){if(!ac.signal.aborted)setError(e instanceof Error?e.message:'Search failed.')}finally{if(!ac.signal.aborted)setLoading(false)}},250);return()=>{ac.abort();clearTimeout(timer)}},[q,tag,player,page,retry])
 return <div className="cs min-h-screen bg-[#181917] text-[#eee9df]"><CsHeader active="clips" right={<AccountBar/>}/><main className="mx-auto max-w-5xl space-y-6 px-4 py-8"><div><p className="text-xs uppercase tracking-widest text-[#e49269]">Across your entire library</p><h1 className="mt-2 text-4xl font-bold" style={{fontFamily:'var(--font-bc)'}}>Find the teaching moment</h1></div><div className="grid gap-3 sm:grid-cols-[2fr_1fr_1fr]"><input type="search" aria-label="Search clip titles and coaching notes" placeholder="Search titles and coaching notes" value={q} onChange={e=>{setQ(e.target.value);setPage(0)}} className={field}/><input aria-label="Filter by exact tag" placeholder="Exact tag, e.g. Spacing" value={tag} onChange={e=>{setTag(e.target.value);setPage(0)}} className={field}/><select aria-label="Filter by player" value={player} onChange={e=>{setPlayer(e.target.value);setPage(0)}} className={field}><option value="">All players</option>{players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>{error?<p role="alert" className="text-red-300">{error} <button onClick={()=>setRetry(x=>x+1)} className="underline">Retry</button></p>:loading?<p role="status">Searching your film…</p>:<><p className="text-sm text-[#c9c3b8]">{total} matching {total===1?'clip':'clips'}</p>{!clips.length&&<p>No clips match. Try another search or tag a clip in a game.</p>}<div className="grid gap-3 sm:grid-cols-2">{clips.map(c=><Link key={c.id} href={`/filmroom/game/${c.game_id}?clip=${c.id}`} className="rounded-lg border border-white/10 bg-[#20211e] p-5 hover:border-[#c66a3e]"><p className="text-xs text-[#e49269]">{c.games?.opponent||'Game film'} · {Math.floor(c.start_time_ms/60000)}:{String(Math.floor(c.start_time_ms/1000)%60).padStart(2,'0')}</p><h2 className="mt-2 font-bold">{c.title}</h2>{c.coaching_note&&<p className="mt-2 line-clamp-3 text-sm text-[#c9c3b8]">{c.coaching_note}</p>}<p className="mt-3 text-xs text-[#c9c3b8]">{c.tags?.join(' · ')}</p><p className="mt-1 text-xs">{c.clip_players?.map(p=>p.players?.name).filter(Boolean).join(', ')}</p></Link>)}</div><div className="flex items-center justify-between"><button className={field} disabled={page===0} onClick={()=>setPage(x=>x-1)}>Previous</button><span className="text-sm">Page {page+1} of {Math.max(1,Math.ceil(total/30))}</span><button className={field} disabled={(page+1)*30>=total} onClick={()=>setPage(x=>x+1)}>Next</button></div></>}</main></div>
}
