import type { Question } from './questions'

export const HEALTH_ASSESSMENT_2_QUESTIONS: Question[] = [

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 6 — Genetic & Developmental Disorders
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'ha2-ch6-q1',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'DNA is located primarily in which cellular structure?',
    options: [
      'The mitochondria',
      'The cell nucleus',
      'The endoplasmic reticulum',
      'The Golgi apparatus',
    ],
    answer: 1,
    explanation: 'DNA (deoxyribonucleic acid) is a double-stranded molecule located in the cell nucleus, organized into chromosomes. Mitochondria contain a small amount of their own DNA, but the primary genetic material is nuclear.',
    term: 'DNA',
    definition: 'Deoxyribonucleic acid — a double-stranded molecule in the cell nucleus that carries the genetic blueprint for all proteins and cellular functions.',
  },
  {
    id: 'ha2-ch6-q2',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'How many pairs of chromosomes does a normal human somatic (body) cell contain?',
    options: [
      '23 single chromosomes (haploid)',
      '22 pairs of autosomes only',
      '23 pairs — 22 autosomes and 1 sex chromosome pair',
      '46 pairs',
    ],
    answer: 2,
    explanation: 'Normal human somatic cells are diploid and contain 46 chromosomes arranged as 23 pairs — 22 pairs of autosomes and 1 pair of sex chromosomes. Gametes (sperm/egg) are haploid with 23 single chromosomes.',
    term: 'Autosomes',
    definition: 'The 22 pairs of non-sex chromosomes in human somatic cells that carry the majority of the genetic information.',
  },
  {
    id: 'ha2-ch6-q3',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Meiosis differs from mitosis in that meiosis:',
    options: [
      'Produces two identical diploid daughter cells',
      'Occurs in all somatic cells',
      'Produces four haploid gametes (sperm or egg cells)',
      'Does not involve DNA replication',
    ],
    answer: 2,
    explanation: 'Meiosis is gamete (sex cell) division that produces 4 haploid cells, each with 23 single chromosomes. Mitosis produces 2 identical diploid daughter cells used for growth and tissue repair.',
    term: 'Meiosis',
    definition: 'Sex cell division producing four haploid gametes (23 chromosomes each); enables genetic recombination during reproduction.',
  },
  {
    id: 'ha2-ch6-q4',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'A patient\'s observable physical trait (such as blue eyes or blood type A) is referred to as their:',
    options: [
      'Genotype',
      'Karyotype',
      'Phenotype',
      'Allele',
    ],
    answer: 2,
    explanation: 'Phenotype is the observable, expressed characteristic of an individual. Genotype is the underlying genetic makeup. Karyotype is the organized display of chromosomes. An allele is one version of a gene.',
    term: 'Phenotype',
    definition: 'The observable physical trait or expression of a gene; determined by the genotype and environmental influences.',
  },
  {
    id: 'ha2-ch6-q5',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'In autosomal dominant inheritance, a person who inherits ONE mutated dominant allele will:',
    options: [
      'Be a carrier but not show symptoms',
      'Express the trait or disorder',
      'Only pass it to daughters, not sons',
      'Require two copies for expression',
    ],
    answer: 1,
    explanation: 'In autosomal dominant disorders, inheriting one dominant mutant allele is sufficient to express the disorder. The allele is on an autosome (not a sex chromosome), and males and females are equally affected.',
    term: 'Autosomal dominant',
    definition: 'An inheritance pattern in which one copy of a mutated dominant allele on an autosome is sufficient to cause the disorder.',
  },
  {
    id: 'ha2-ch6-q6',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Sickle cell disease follows which inheritance pattern?',
    options: [
      'Autosomal dominant',
      'Sex-linked dominant',
      'Autosomal recessive',
      'Mitochondrial',
    ],
    answer: 2,
    explanation: 'Sickle cell disease is autosomal recessive — two copies of the mutated allele (homozygous) are required to express the disease. Heterozygous individuals (one copy) are carriers.',
    term: 'Autosomal recessive',
    definition: 'An inheritance pattern requiring two copies of the mutated allele (homozygous) for disease expression; heterozygous individuals are carriers.',
  },
  {
    id: 'ha2-ch6-q7',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Sex-linked genetic disorders are most commonly linked to the X chromosome. Which statement about X-linked recessive disorders is correct?',
    options: [
      'Females are more commonly affected than males',
      'Males are more commonly affected because they have only one X chromosome',
      'Both sexes are equally affected',
      'The disorder skips a generation in all cases',
    ],
    answer: 1,
    explanation: 'Males have only one X chromosome (XY), so a single recessive mutation on the X chromosome causes disease in males. Females (XX) need the mutation on both X chromosomes to be affected and are often carriers.',
    term: 'Sex-linked disorder',
    definition: 'A genetic disorder caused by a mutation on a sex chromosome (usually X); males with one mutated X are more commonly affected.',
  },
  {
    id: 'ha2-ch6-q8',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Down syndrome is caused by which chromosomal alteration?',
    options: [
      'Monosomy of chromosome 21',
      'Trisomy of chromosome 21',
      'Translocation of the X chromosome',
      'Deletion of chromosome 18',
    ],
    answer: 1,
    explanation: 'Down syndrome (trisomy 21) results from three copies of chromosome 21 instead of two. It is the most common chromosomal disorder and typically results from nondisjunction during meiosis.',
    term: 'Trisomy 21',
    definition: 'Down syndrome; a chromosomal disorder resulting from three copies of chromosome 21, typically caused by nondisjunction.',
  },
  {
    id: 'ha2-ch6-q9',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Which of the following is a common clinical manifestation of Down syndrome?',
    options: [
      'Tall stature and webbed neck',
      'Intellectual disability, cardiac defects, and characteristic facial features',
      'Infertility and absence of secondary sex characteristics',
      'Progressive muscle wasting beginning in infancy',
    ],
    answer: 1,
    explanation: 'Down syndrome typically presents with intellectual/mental delay, characteristic facial features, congenital cardiac defects, GI malformations, visual/hearing impairment, thyroid dysfunction, and increased leukemia risk.',
    term: 'Down syndrome',
    definition: 'Trisomy 21 chromosomal disorder presenting with intellectual disability, characteristic facial features, cardiac defects, and GI malformations.',
  },
  {
    id: 'ha2-ch6-q10',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Nondisjunction during meiosis refers to:',
    options: [
      'The failure of a chromosome pair to separate properly during cell division',
      'A deletion of a chromosome segment',
      'Inversion of a chromosomal segment',
      'Transfer of a chromosomal segment to a different chromosome',
    ],
    answer: 0,
    explanation: 'Nondisjunction is the failure of homologous chromosomes (or sister chromatids) to separate correctly during meiosis, resulting in gametes with an extra or missing chromosome — the basis of trisomy and monosomy.',
    term: 'Nondisjunction',
    definition: 'Failure of chromosomes to separate properly during meiosis, resulting in gametes with too many or too few chromosomes (trisomy or monosomy).',
  },
  {
    id: 'ha2-ch6-q11',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Turner syndrome is characterized by which chromosomal pattern?',
    options: [
      'Trisomy 21 (XXX)',
      'Trisomy of the X chromosome (XXY)',
      'Monosomy X (45, X — missing one sex chromosome)',
      'Extra Y chromosome (XYY)',
    ],
    answer: 2,
    explanation: 'Turner syndrome is monosomy X (45, X), where females are missing one sex chromosome. It presents with short stature, webbed neck, infertility, and absent or incomplete development of secondary sex characteristics.',
    term: 'Turner syndrome',
    definition: 'Monosomy X (45, X); a chromosomal disorder in females presenting with short stature, webbed neck, infertility, and absent secondary sex development.',
  },
  {
    id: 'ha2-ch6-q12',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Klinefelter syndrome (47, XXY) is characterized by:',
    options: [
      'An extra autosome, resulting in intellectual disability',
      'A male with an extra X chromosome, causing hypogonadism and infertility',
      'A female missing one X chromosome',
      'Trisomy 18 resulting in severe organ malformations',
    ],
    answer: 1,
    explanation: 'Klinefelter syndrome (47, XXY) affects males who have an extra X chromosome. It causes hypogonadism, infertility, tall stature, and gynecomastia. Intellectual ability is usually normal to mildly impaired.',
    term: 'Klinefelter syndrome',
    definition: '47, XXY chromosomal disorder in males; characterized by hypogonadism, infertility, gynecomastia, and typically tall stature.',
  },
  {
    id: 'ha2-ch6-q13',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Teratogens are agents that cause developmental disorders. Which of the following is an example of a teratogen?',
    options: [
      'Insulin',
      'Fetal alcohol (ethanol exposure during pregnancy)',
      'Iron supplementation',
      'Vitamin D',
    ],
    answer: 1,
    explanation: 'Teratogens are substances or exposures that disrupt normal organogenesis (organ development) during pregnancy. Alcohol (fetal alcohol syndrome), certain drugs, radiation, and infections (TORCH) are teratogens.',
    term: 'Teratogen',
    definition: 'An agent (chemical, drug, infection, radiation) that disrupts normal fetal organogenesis and causes developmental disorders or birth defects.',
  },
  {
    id: 'ha2-ch6-q14',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Neural tube defects (NTDs) most commonly occur because:',
    options: [
      'The neural tube fails to close in the first few weeks after conception',
      'The fetal brain develops too rapidly in the third trimester',
      'Chromosomal nondisjunction occurs during gamete formation',
      'The immune system attacks fetal neural tissue',
    ],
    answer: 0,
    explanation: 'Neural tube defects occur early in fetal development when the neural tube (precursor to brain and spinal cord) fails to close properly. The two most common types are spina bifida and anencephaly.',
    term: 'Neural tube defect',
    definition: 'A birth defect caused by incomplete closure of the neural tube in early fetal development; includes spina bifida and anencephaly.',
  },
  {
    id: 'ha2-ch6-q15',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Sickle cell disease results from a point mutation that causes:',
    options: [
      'An extra chromosome 11',
      'Altered structure of the beta chain of hemoglobin, producing hemoglobin S (HbS)',
      'Deletion of the entire hemoglobin gene',
      'An autoimmune attack on red blood cells',
    ],
    answer: 1,
    explanation: 'A single nucleotide point mutation changes the beta-globin chain of hemoglobin, producing hemoglobin S (HbS). Under low oxygen conditions, HbS causes RBCs to assume a sickle shape, leading to vascular occlusion and hemolysis.',
    term: 'Hemoglobin S (HbS)',
    definition: 'The abnormal form of hemoglobin caused by a point mutation in the beta-globin gene; causes red blood cells to sickle under low-oxygen conditions.',
  },
  {
    id: 'ha2-ch6-q16',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'A patient with sickle cell disease presents with jaundice, anemia, and severe joint pain. These manifestations are primarily related to:',
    options: [
      'Elevated platelet counts causing clotting in small vessels',
      'The proportion of HbS in the circulation causing vaso-occlusion and hemolysis',
      'Autoimmune destruction of white blood cells',
      'Fluid overload from renal failure',
    ],
    answer: 1,
    explanation: 'Clinical manifestations of sickle cell disease — including pain crises, jaundice, anemia, and organ damage — are directly related to the proportion of HbS. Sickled cells cause vaso-occlusion (pain, organ damage) and hemolyze (anemia, jaundice).',
    term: 'Sickle cell crisis',
    definition: 'An acute episode of pain and organ damage in sickle cell disease caused by vaso-occlusion from sickle-shaped red blood cells.',
  },
  {
    id: 'ha2-ch6-q17',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Prenatal diagnosis of Down syndrome can be confirmed by which test?',
    options: [
      'Hemoglobin electrophoresis',
      'Fetal karyotype analysis',
      'Lumbar puncture',
      'Amylase and lipase levels',
    ],
    answer: 1,
    explanation: 'Fetal karyotype (chromosomal analysis) is the definitive prenatal test for Down syndrome. It can be obtained via amniocentesis or chorionic villus sampling. Screening includes nuchal translucency and the quadruple blood test.',
    term: 'Karyotype',
    definition: 'An organized display of an individual\'s chromosomes; used to identify chromosomal abnormalities such as trisomy 21.',
  },
  {
    id: 'ha2-ch6-q18',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'TORCH infections are a group of maternal infections that can cross the placenta and cause developmental disorders. TORCH stands for:',
    options: [
      'Tuberculosis, Otitis, Rubella, Cytomegalovirus, Herpes',
      'Toxoplasmosis, Other infections, Rubella, Cytomegalovirus, Herpes simplex',
      'Typhoid, Otitis, Rhinovirus, CMV, HIV',
      'Toxemia, Obesity, RSV, Clostridium, Hepatitis',
    ],
    answer: 1,
    explanation: 'TORCH = Toxoplasmosis, Other (syphilis, varicella, HIV), Rubella, Cytomegalovirus, Herpes simplex. These maternal infections can cross the placenta and cause serious fetal developmental disorders.',
    term: 'TORCH infections',
    definition: 'Toxoplasmosis, Other infections, Rubella, Cytomegalovirus, and Herpes simplex — maternal infections that can cross the placenta and cause fetal developmental disorders.',
  },
  {
    id: 'ha2-ch6-q19',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'The TORCH acronym is relevant in which context?',
    options: [
      'Screening newborns for chromosomal disorders',
      'Identifying maternal infections that can cause fetal developmental disorders',
      'Classifying types of genetic mutations',
      'Diagnosing metabolic disorders in the elderly',
    ],
    answer: 1,
    explanation: 'TORCH infections can cross the placenta during pregnancy and disrupt fetal organogenesis, causing congenital abnormalities, intellectual disability, or fetal death. Maternal infection screening is a key prenatal care component.',
  },
  {
    id: 'ha2-ch6-q20',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Polygenic disorders differ from single-gene (Mendelian) disorders in that polygenic disorders:',
    options: [
      'Follow a completely predictable Mendelian inheritance pattern',
      'Involve multiple alleles at different chromosome locations and are influenced by environment',
      'Are caused exclusively by chromosomal translocations',
      'Only affect males',
    ],
    answer: 1,
    explanation: 'Polygenic disorders involve multiple alleles at different chromosome locations interacting with environmental factors (e.g., height, blood pressure, diabetes). They are less predictable than single-gene Mendelian disorders.',
    term: 'Polygenic disorder',
    definition: 'A disorder caused by the interaction of multiple alleles at different chromosome locations, often modified by environmental factors; less predictable than Mendelian inheritance.',
  },
  {
    id: 'ha2-ch6-q21',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Genetic mutations include all of the following types EXCEPT:',
    options: [
      'Deletion',
      'Translocation',
      'Inversion',
      'Senescence',
    ],
    answer: 3,
    explanation: 'Genetic mutations include deletion, duplication, inversion, insertion, and translocation of chromosomal material. Senescence refers to cellular aging, not a type of genetic mutation.',
    term: 'Translocation',
    definition: 'A type of chromosomal mutation where a segment of one chromosome attaches to a different chromosome.',
  },
  {
    id: 'ha2-ch6-q22',
    subject: 'health-assessment' as const,
    chapter: 6,
    type: 'mc',
    question: 'Spina bifida is best described as:',
    options: [
      'Complete absence of brain development',
      'Incomplete closure of the spinal neural tube, exposing the spinal cord',
      'A trisomy disorder affecting chromosome 18',
      'An autoimmune destruction of the spinal cord',
    ],
    answer: 1,
    explanation: 'Spina bifida is a neural tube defect where the spinal column does not fully close around the spinal cord. Anencephaly is the other major NTD — absence of brain development. Treatment for spina bifida is surgical correction.',
    term: 'Spina bifida',
    definition: 'A neural tube defect where the spinal column fails to close completely around the spinal cord; treated with surgical correction.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 8 — Altered Fluid & Electrolyte Balance
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'ha2-ch8-q1',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Electrolytes that carry a POSITIVE charge are called:',
    options: [
      'Anions',
      'Cations',
      'Isotones',
      'Buffers',
    ],
    answer: 1,
    explanation: 'Cations are positively charged ions (e.g., Na+, K+, Ca2+, Mg2+). Anions are negatively charged ions (e.g., Cl−, HCO3−). Electroneutrality means cations and anions are balanced in body fluids.',
    term: 'Cation',
    definition: 'An electrolyte ion with a positive charge (e.g., Na+, K+, Ca2+, Mg2+).',
  },
  {
    id: 'ha2-ch8-q2',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Total body water composes approximately what percentage of body weight?',
    options: [
      '40%',
      '50%',
      '60%',
      '75%',
    ],
    answer: 2,
    explanation: 'Total body water is approximately 60% of body weight. It is distributed as intracellular fluid (2/3, or ~40% body weight) and extracellular fluid (1/3, or ~20% body weight — comprising plasma and interstitial fluid).',
    term: 'Intracellular fluid (ICF)',
    definition: 'The fluid contained within cells; comprises 2/3 of total body water (approximately 40% of body weight).',
  },
  {
    id: 'ha2-ch8-q3',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'The normal serum sodium range is:',
    options: [
      '125–135 mEq/L',
      '135–145 mEq/L',
      '145–155 mEq/L',
      '3.5–5.0 mEq/L',
    ],
    answer: 1,
    explanation: 'Normal serum sodium is 135–145 mEq/L. Sodium is the primary cation in extracellular fluid and is critical for fluid balance, blood pressure, and nerve impulse transmission. Water follows sodium.',
    term: 'Hyponatremia',
    definition: 'Serum sodium < 135 mEq/L; presents with neurological symptoms (confusion, seizures) because water follows sodium into brain cells.',
  },
  {
    id: 'ha2-ch8-q4',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'The normal serum potassium range is:',
    options: [
      '1.5–2.5 mEq/L',
      '2.0–4.0 mEq/L',
      '3.5–5.0 mEq/L',
      '8.5–10.5 mg/dL',
    ],
    answer: 2,
    explanation: 'Normal serum potassium is 3.5–5.0 mEq/L. Potassium is the primary intracellular cation and is critical for cardiac rhythm, muscle contraction, and acid-base balance. "Too much K+ kills" — hyperkalemia causes fatal arrhythmias.',
    term: 'Hyperkalemia',
    definition: 'Serum potassium > 5.0 mEq/L; dangerous because it can cause fatal cardiac arrhythmias and muscle weakness.',
  },
  {
    id: 'ha2-ch8-q5',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'A nurse caring for a patient with hypokalemia would expect which of the following signs and symptoms?',
    options: [
      'Hypertension and bradycardia',
      'Muscle cramping, weakness, bradycardia, and alkalosis',
      'Peaked T waves on ECG and muscle rigidity',
      'Hypercalcemia and hyperreflexia',
    ],
    answer: 1,
    explanation: 'The COW BRAIN mnemonic captures hypokalemia signs: Cramping, Oral causes (vomiting), Weakness, Bradycardia, Respiratory arrest, Alkalosis, Ileus, NG suction. Bananas (high K+) help prevent hypokalemia.',
    term: 'Hypokalemia',
    definition: 'Serum potassium < 3.5 mEq/L; presents with muscle cramping, weakness, bradycardia, respiratory arrest, ileus, and metabolic alkalosis.',
  },
  {
    id: 'ha2-ch8-q6',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Normal serum calcium is 8.5–10.5 mg/dL. Calcium is important for all of the following EXCEPT:',
    options: [
      'Strong bones and teeth',
      'Muscle contraction',
      'Nerve impulse transmission',
      'Insulin secretion regulation',
    ],
    answer: 3,
    explanation: 'Calcium is critical for strong bones and teeth, muscle contraction, and nerve impulse transmission. While calcium has a role in some endocrine processes, insulin secretion is primarily regulated by blood glucose, not calcium balance.',
    term: 'Hypocalcemia',
    definition: 'Serum calcium < 8.5 mg/dL; presents with positive Chvostek sign (facial nerve tapping causes cheek twitch) and positive Trousseau sign (hand spasm with BP cuff inflation).',
  },
  {
    id: 'ha2-ch8-q7',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'A nurse inflates a blood pressure cuff above the patient\'s systolic pressure and observes carpal spasm. This is called a positive:',
    options: [
      'Chvostek sign',
      'Trousseau sign',
      'Kernig sign',
      'Babinski sign',
    ],
    answer: 1,
    explanation: 'Trousseau sign is positive when inflating a BP cuff above systolic pressure causes carpal spasm (hand tetany), indicating hypocalcemia. Chvostek sign is facial nerve tapping causing cheek twitch — both indicate hypocalcemia.',
    term: 'Trousseau sign',
    definition: 'A sign of hypocalcemia: hand/carpal spasm when a BP cuff is inflated above systolic pressure, compressing the brachial nerve.',
  },
  {
    id: 'ha2-ch8-q8',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Hypercalcemia (calcium > 10.5 mg/dL) most commonly presents with:',
    options: [
      'Positive Trousseau and Chvostek signs',
      'Confusion, muscle weakness, kidney stones, bone pain, and constipation',
      'Peaked T waves and muscle cramps',
      'Seizures and cardiac arrest',
    ],
    answer: 1,
    explanation: 'Hypercalcemia presents with confusion, cardiac arrhythmias, muscle weakness, kidney stones (back pain), increased urine output, bone pain, and constipation. A useful mnemonic: "Bones, Stones, Groans, and Moans" (bones: bone pain; stones: kidney stones; groans: GI symptoms; moans: neurological).',
    term: 'Hypercalcemia',
    definition: 'Serum calcium > 10.5 mg/dL; presents with confusion, arrhythmias, muscle weakness, kidney stones, bone pain, and constipation.',
  },
  {
    id: 'ha2-ch8-q9',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Normal serum magnesium is 1.5–2.5 mEq/L. Hypomagnesemia presents with the CASH mnemonic, which stands for:',
    options: [
      'Confusion, Arrhythmia, Seizures, Hypertension',
      'Cramping, Arrhythmia, Seizures, Hypotension',
      'Coma, Alkalosis, Spasms, Hyporeflexia',
      'Cramping, Alkalosis, Stroke, Headache',
    ],
    answer: 1,
    explanation: 'CASH = Cramping, Arrhythmia, Seizures, Hypotension — the key signs of hypomagnesemia (Mg < 1.5 mEq/L). Magnesium is essential for CNS function, muscle and cardiac contraction, and carbohydrate/protein metabolism.',
    term: 'Hypomagnesemia',
    definition: 'Serum magnesium < 1.5 mEq/L; presents with cramping, arrhythmia, seizures, and hypotension (CASH mnemonic).',
  },
  {
    id: 'ha2-ch8-q10',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Osmosis is best defined as:',
    options: [
      'Fluid movement from a vessel into the interstitial space via pressure gradients',
      'Water movement through a cell membrane from an area of LOW to HIGH particulate concentration',
      'Active pumping of sodium out of cells using ATP',
      'The reabsorption of fluid from interstitial space back into the vascular space',
    ],
    answer: 1,
    explanation: 'Osmosis is the passive movement of water through a semipermeable membrane from an area of low solute concentration (high water concentration) to an area of high solute concentration (low water concentration), equilibrating concentrations.',
    term: 'Osmosis',
    definition: 'The movement of water through a semipermeable membrane from an area of low to high particulate (solute) concentration.',
  },
  {
    id: 'ha2-ch8-q11',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'A hypertonic IV solution has greater osmotic pressure than intracellular fluid. What effect does it have on cells?',
    options: [
      'Cells swell and may lyse',
      'Cells shrink as water moves out by osmosis',
      'No change in cell size',
      'Cells burst due to water influx',
    ],
    answer: 1,
    explanation: 'Hypertonic solutions have higher solute concentration than ICF. Water moves out of cells by osmosis into the hypertonic environment, causing cells to shrink/crenate. Hypotonic solutions cause cells to swell and potentially lyse.',
    term: 'Hypertonic solution',
    definition: 'A solution with greater osmotic pressure than intracellular fluid; causes cells to shrink as water moves out by osmosis.',
  },
  {
    id: 'ha2-ch8-q12',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'The renin-angiotensin-aldosterone system (RAAS) primarily helps regulate:',
    options: [
      'Blood glucose levels',
      'Fluid balance and blood pressure by controlling sodium and water retention',
      'Potassium excretion only',
      'Calcium absorption from the gut',
    ],
    answer: 1,
    explanation: 'The RAAS is a key regulatory system for fluid balance and blood pressure. Renin triggers angiotensin II production, which stimulates aldosterone release, causing sodium (and water) retention by the kidneys.',
    term: 'RAAS',
    definition: 'Renin-angiotensin-aldosterone system; regulates fluid balance and blood pressure through sodium and water retention by the kidneys.',
  },
  {
    id: 'ha2-ch8-q13',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'A patient with cirrhosis develops ascites. The primary mechanism causing ascites is:',
    options: [
      'Decreased sodium intake leading to cellular dehydration',
      'Portal hypertension and reduced oncotic pressure causing fluid accumulation in the peritoneal cavity',
      'Hyperkalemia causing third-spacing of fluids',
      'Hypercalcemia stimulating excess fluid secretion',
    ],
    answer: 1,
    explanation: 'Cirrhosis causes portal hypertension (due to liver fibrosis impeding blood flow) and reduced albumin production (decreasing oncotic pressure), leading to fluid leaking into the peritoneal cavity (ascites). Signs include abdominal distension, discomfort, and weight gain.',
    term: 'Ascites',
    definition: 'Abnormal accumulation of fluid in the peritoneal (abdominal) cavity; commonly caused by cirrhosis, portal hypertension, and reduced oncotic pressure.',
  },
  {
    id: 'ha2-ch8-q14',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'A dehydrated patient has a serum sodium of 125 mEq/L. This is classified as which type of dehydration?',
    options: [
      'Hypernatremic dehydration',
      'Isonatremic dehydration',
      'Hyponatremic dehydration',
      'Isotonic dehydration',
    ],
    answer: 2,
    explanation: 'Hyponatremic dehydration: Na < 130 mEq/L, hypotonic fluid loss, fluid shifts from intravascular to extravascular. Isonatremic: Na 130–150 mEq/L (most common, 80%). Hypernatremic: Na > 150 mEq/L, hypotonic fluid loss.',
    term: 'Hyponatremic dehydration',
    definition: 'Dehydration with serum sodium < 130 mEq/L; causes fluid shift from intravascular to extravascular space.',
  },
  {
    id: 'ha2-ch8-q15',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Classic clinical manifestations of dehydration include all of the following EXCEPT:',
    options: [
      'Dry mucous membranes',
      'Decreased level of consciousness',
      'Prolonged capillary refill time (> 3 seconds)',
      'Facial plethora (flushing) and bounding pulses',
    ],
    answer: 3,
    explanation: 'Dehydration signs include dry mucous membranes, decreased LOC, prolonged cap refill (>3 sec), decreased or absent tears, depressed fontanel, sunken eyes, and decreased urine output. Flushing and bounding pulses suggest fluid overload, not dehydration.',
    term: 'Dehydration',
    definition: 'A negative fluid balance state with decreased total body water; presents with dry membranes, prolonged cap refill, decreased LOC, and decreased urine output.',
  },
  {
    id: 'ha2-ch8-q16',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Which electrolyte is the PRIMARY extracellular cation responsible for fluid balance and blood pressure?',
    options: [
      'Potassium (K+)',
      'Calcium (Ca2+)',
      'Sodium (Na+)',
      'Magnesium (Mg2+)',
    ],
    answer: 2,
    explanation: 'Sodium (Na+, normal 135–145 mEq/L) is the primary extracellular cation. "Water follows sodium" — sodium balance directly drives fluid distribution and blood pressure. Potassium is the primary INTRAcellular cation.',
    term: 'Sodium (Na+)',
    definition: 'Primary extracellular cation (normal 135–145 mEq/L); critical for fluid balance, blood pressure, and nerve impulse transmission. Water follows sodium.',
  },
  {
    id: 'ha2-ch8-q17',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Antidiuretic hormone (ADH) regulates fluid balance by:',
    options: [
      'Promoting sodium excretion from the kidneys',
      'Causing the kidneys to retain water, reducing urine output',
      'Stimulating thirst to increase fluid intake',
      'Promoting potassium reabsorption',
    ],
    answer: 1,
    explanation: 'ADH (vasopressin) is released when blood osmolality rises (dehydration). It acts on renal collecting ducts to increase water reabsorption, reducing urine output and diluting blood. It is one of three primary regulators: thirst, RAAS, and ADH.',
    term: 'ADH (Antidiuretic hormone)',
    definition: 'A hormone that promotes renal water reabsorption when blood osmolality is high, reducing urine output and restoring fluid balance.',
  },
  {
    id: 'ha2-ch8-q18',
    subject: 'health-assessment' as const,
    chapter: 8,
    type: 'mc',
    question: 'Potassium (K+) is higher INSIDE the cell than outside. Which organ is the primary regulator of potassium balance?',
    options: [
      'The liver',
      'The lungs',
      'The kidneys',
      'The adrenal glands',
    ],
    answer: 2,
    explanation: 'The kidneys are the primary regulators of potassium balance. Insulin also lowers serum potassium by driving K+ into cells. Aldosterone promotes K+ excretion. "Too much K+ kills" — hyperkalemia causes fatal cardiac arrhythmias.',
    term: 'Potassium (K+)',
    definition: 'Primary intracellular cation (normal 3.5–5.0 mEq/L); critical for cardiac rhythm, muscle contraction, and acid-base balance; regulated primarily by the kidneys.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 9 — Altered Acid-Base Balance
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'ha2-ch9-q1',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'The normal arterial blood pH range is:',
    options: [
      '7.20–7.30',
      '7.25–7.40',
      '7.35–7.45',
      '7.45–7.55',
    ],
    answer: 2,
    explanation: 'Normal arterial blood pH is 7.35–7.45. A pH < 7.35 is acidosis; pH > 7.45 is alkalosis. Maintaining this narrow range is critical for cellular enzyme function and homeostasis.',
    term: 'pH',
    definition: 'The clinical measurement of the acid-to-base ratio in blood; normal arterial range is 7.35–7.45.',
  },
  {
    id: 'ha2-ch9-q2',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'Buffer systems resist pH changes by:',
    options: [
      'Increasing hydrogen ion production',
      'Trading stronger acids and bases for weaker ones to minimize pH shifts',
      'Eliminating all hydrogen ions from the blood',
      'Retaining carbon dioxide to acidify the blood',
    ],
    answer: 1,
    explanation: 'Buffer systems mix acids and bases to resist pH change by trading strong acids/bases for weaker ones. The three buffer systems are: Plasma (seconds), Respiratory (minutes), and Renal (hours to days).',
    term: 'Buffer system',
    definition: 'A chemical system that resists pH change by trading strong acids and bases for weaker equivalents; includes plasma, respiratory, and renal buffers.',
  },
  {
    id: 'ha2-ch9-q3',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'Which buffer system responds fastest to pH changes — within seconds?',
    options: [
      'Renal buffer system',
      'Respiratory buffer system',
      'Plasma buffer system',
      'Hepatic buffer system',
    ],
    answer: 2,
    explanation: 'The plasma buffer system (including bicarbonate and protein buffers) responds within seconds. The respiratory buffer responds in minutes (CO2 excretion). The renal buffer responds in hours to days (H+ excretion and HCO3− conservation).',
    term: 'Plasma buffer system',
    definition: 'The fastest-acting buffer system (seconds); includes bicarbonate (H2CO3/NaHCO3) and protein buffers that resist pH changes.',
  },
  {
    id: 'ha2-ch9-q4',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'In the respiratory buffer system, when blood becomes more acidic (pH drops), the body compensates by:',
    options: [
      'Retaining CO2 to raise pH',
      'Increasing breathing rate to blow off CO2 and raise pH',
      'Decreasing respiratory rate to conserve bicarbonate',
      'Stimulating the kidneys to produce more hydrogen ions',
    ],
    answer: 1,
    explanation: 'CO2 + H2O → H2CO3 → H+ + HCO3−. In acidosis, the lungs increase breathing rate to eliminate CO2, reducing carbonic acid formation and raising pH. In alkalosis, the lungs retain CO2 by slowing breathing.',
    term: 'Respiratory buffer system',
    definition: 'Regulates pH by controlling CO2 (carbonic acid); responds within minutes — in acidosis, increases breathing rate to blow off CO2.',
  },
  {
    id: 'ha2-ch9-q5',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'Metabolic acidosis is characterized by:',
    options: [
      'pH > 7.45 and HCO3− > 31 mEq/L',
      'pH < 7.35 and HCO3− < 24 mEq/L (base deficit)',
      'pH < 7.35 and elevated CO2',
      'pH > 7.45 and decreased CO2',
    ],
    answer: 1,
    explanation: 'Metabolic acidosis: pH < 7.35, HCO3− < 24 mEq/L (base deficit). Contributing mechanisms: increased acid production, decreased renal acid secretion, increased bicarbonate loss, increased chloride. Respiratory compensation: hyperventilation (Kussmaul breathing).',
    term: 'Metabolic acidosis',
    definition: 'An acid-base imbalance with pH < 7.35 and HCO3− < 24 mEq/L; caused by base deficit or acid accumulation; compensated by hyperventilation.',
  },
  {
    id: 'ha2-ch9-q6',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'A patient in metabolic acidosis is hyperventilating with deep, rapid respirations. This breathing pattern is called:',
    options: [
      'Cheyne-Stokes breathing',
      'Biot\'s breathing',
      'Kussmaul breathing',
      'Apneustic breathing',
    ],
    answer: 2,
    explanation: 'Kussmaul breathing is deep, rapid, labored breathing that represents the body\'s respiratory compensation for metabolic acidosis — increasing CO2 elimination to raise pH. It is classically seen in diabetic ketoacidosis.',
    term: 'Kussmaul breathing',
    definition: 'Deep, rapid, labored respiration that is respiratory compensation for metabolic acidosis; seen in diabetic ketoacidosis.',
  },
  {
    id: 'ha2-ch9-q7',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'Clinical manifestations of metabolic acidosis include all of the following EXCEPT:',
    options: [
      'Nausea and vomiting',
      'Confusion and lethargy',
      'Vasodilation and flushed skin',
      'Hypertension and bradycardia',
    ],
    answer: 3,
    explanation: 'Metabolic acidosis presents with anorexia, nausea, vomiting, weakness, lethargy, confusion, coma, vasodilation, decreased heart rate, and flushed skin. Hypertension is not a typical feature — acidosis tends to cause vasodilation and hypotension.',
    term: 'Metabolic acidosis symptoms',
    definition: 'Presents with nausea, vomiting, weakness, confusion, lethargy, vasodilation, decreased heart rate, and flushed skin.',
  },
  {
    id: 'ha2-ch9-q8',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'Metabolic alkalosis is characterized by:',
    options: [
      'pH < 7.35 and HCO3− < 24 mEq/L',
      'pH > 7.45 and HCO3− > 31 mEq/L (base excess)',
      'pH > 7.45 and elevated PaCO2',
      'pH < 7.35 and decreased PaCO2',
    ],
    answer: 1,
    explanation: 'Metabolic alkalosis: pH > 7.45, HCO3− > 31 mEq/L. Contributing mechanisms: decreased H+ ions, increased HCO3−, loss of Cl− ions. Often asymptomatic or presents with signs of hypokalemia (which frequently accompanies metabolic alkalosis).',
    term: 'Metabolic alkalosis',
    definition: 'An acid-base imbalance with pH > 7.45 and HCO3− > 31 mEq/L; caused by base excess or acid loss; often presents with hypokalemia signs.',
  },
  {
    id: 'ha2-ch9-q9',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'The renal buffer system compensates for pH imbalances by:',
    options: [
      'Rapidly expelling CO2 within seconds',
      'Retaining or excreting H+ ions and bicarbonate over hours to days',
      'Producing plasma proteins to bind hydrogen ions',
      'Stimulating ADH release to retain water',
    ],
    answer: 1,
    explanation: 'The renal buffer system is the slowest but most powerful — responding in hours to days. It eliminates/conserves H+, produces/conserves bicarbonate, and regulates ammonia, K+/H+ exchange, and Cl−/HCO3− exchange.',
    term: 'Renal buffer system',
    definition: 'The slowest buffer (hours to days) but most powerful; regulates pH by excreting or conserving H+ ions and bicarbonate through the kidneys.',
  },
  {
    id: 'ha2-ch9-q10',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'Which ABG findings indicate respiratory acidosis?',
    options: [
      'pH 7.50, PaCO2 28 mmHg, HCO3− 24 mEq/L',
      'pH 7.28, PaCO2 55 mmHg, HCO3− 24 mEq/L',
      'pH 7.28, PaCO2 35 mmHg, HCO3− 16 mEq/L',
      'pH 7.48, PaCO2 42 mmHg, HCO3− 32 mEq/L',
    ],
    answer: 1,
    explanation: 'Respiratory acidosis: pH < 7.35 + elevated PaCO2 (hypoventilation/CO2 retention). Option B: pH 7.28 (acidosis) + PaCO2 55 (elevated = respiratory cause) + normal HCO3− = uncompensated respiratory acidosis. Option C has low pH + low HCO3− = metabolic acidosis.',
    term: 'Respiratory acidosis',
    definition: 'Acid-base imbalance with pH < 7.35 caused by CO2 retention from hypoventilation; elevated PaCO2 is the hallmark.',
  },
  {
    id: 'ha2-ch9-q11',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'A patient receiving parenteral nutrition (PN) develops metabolic acidosis. Which ABG finding would confirm this?',
    options: [
      'pH 7.38, PaCO2 42, HCO3− 24',
      'pH 7.52, PaCO2 40, HCO3− 34',
      'pH 7.30, HCO3− 18, decreased CO2 (respiratory compensation)',
      'pH 7.30, PaCO2 58, HCO3− 26',
    ],
    answer: 2,
    explanation: 'Metabolic acidosis in PN: pH < 7.35, decreased HCO3−, and decreased CO2 (respiratory compensation through hyperventilation). The additives in PN solutions (hydrochloric and organic acids) can contribute to metabolic acidosis.',
    term: 'Parenteral nutrition (PN)',
    definition: 'IV delivery of nutrients (glucose, amino acids, lipids, electrolytes); can cause metabolic acidosis due to acid additives in the solution.',
  },
  {
    id: 'ha2-ch9-q12',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'Which statement about the bicarbonate buffer system is correct?',
    options: [
      'It uses H2CO3 (weak acid) and NaHCO3 (weak base) to resist pH change',
      'It is the slowest of the three buffer systems',
      'It only functions in the intracellular compartment',
      'It requires 48 hours to activate after pH changes',
    ],
    answer: 0,
    explanation: 'The bicarbonate buffer system uses carbonic acid (H2CO3, a weak acid) and sodium bicarbonate (NaHCO3, a weak base) to buffer strong acids and bases, substituting them for weaker equivalents. It is part of the plasma buffer system (fastest — seconds).',
    term: 'Bicarbonate buffer system',
    definition: 'Uses H2CO3 (weak acid) and NaHCO3 (bicarb, weak base) to resist pH changes by trading strong acids/bases for weaker equivalents.',
  },
  {
    id: 'ha2-ch9-q13',
    subject: 'health-assessment' as const,
    chapter: 9,
    type: 'mc',
    question: 'The normal HCO3− (bicarbonate) level in arterial blood is:',
    options: [
      '12–18 mEq/L',
      '18–22 mEq/L',
      '22–26 mEq/L',
      '28–34 mEq/L',
    ],
    answer: 2,
    explanation: 'Normal HCO3− is 22–26 mEq/L. Values < 22 suggest metabolic acidosis (base deficit); values > 26 suggest metabolic alkalosis (base excess). In metabolic acidosis, HCO3− < 24 mEq/L; in metabolic alkalosis, HCO3− > 31 mEq/L.',
    term: 'Bicarbonate (HCO3−)',
    definition: 'The primary base in blood (normal 22–26 mEq/L); low HCO3− = metabolic acidosis; high HCO3− = metabolic alkalosis.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 13 — Respiratory System
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'ha2-ch13-q1',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'When auscultating the lungs, the nurse should position the stethoscope:',
    options: [
      'Over the scapula to enhance adventitious sounds',
      'Barely touching the skin to avoid auditory artifact',
      'Over the left lung fields first',
      'In one position long enough to hear a complete inhalation-exhalation cycle',
    ],
    answer: 3,
    explanation: 'Proper lung auscultation requires holding the stethoscope in each position long enough to hear a complete inhalation-exhalation set before moving. The diaphragm should be pressed firmly against the skin for best contact.',
  },
  {
    id: 'ha2-ch13-q2',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'A chest X-ray shows atelectasis in the right base. During auscultation, the nurse would most likely find:',
    options: [
      'Increased fremitus in the right base',
      'Diminished or absent breath sounds over the affected area',
      'Wheezing throughout all lung fields',
      'Symmetrical chest expansion',
    ],
    answer: 1,
    explanation: 'Atelectasis (alveolar collapse) causes diminished or absent breath sounds over the affected area because little to no air is moving through collapsed alveoli. It typically affects dependent lung regions (right base is common post-surgery or in immobile patients).',
    term: 'Atelectasis',
    definition: 'Collapse or incomplete expansion of alveoli; presents with diminished or absent breath sounds over the affected area.',
  },
  {
    id: 'ha2-ch13-q3',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'Which respiratory pattern is characterized by deep, rapid, labored breaths and is associated with metabolic acidosis?',
    options: [
      'Cheyne-Stokes',
      'Bradypnea',
      'Kussmaul',
      'Biot\'s',
    ],
    answer: 2,
    explanation: 'Kussmaul breathing is deep, rapid, labored respiration seen in metabolic acidosis (classically DKA) as the body tries to blow off CO2. Cheyne-Stokes has alternating crescendo-decrescendo with apneic periods. Bradypnea is slow breathing.',
    term: 'Eupnea',
    definition: 'Normal, regular breathing at a normal rate (12–20 breaths/minute in adults).',
  },
  {
    id: 'ha2-ch13-q4',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'Cheyne-Stokes breathing is characterized by:',
    options: [
      'Rapid, shallow, regular breaths',
      'Very slow breathing below 12 breaths per minute',
      'Alternating periods of increasing/decreasing depth with episodes of apnea',
      'Complete cessation of breathing for more than 60 seconds',
    ],
    answer: 2,
    explanation: 'Cheyne-Stokes breathing is a cyclical pattern of crescendo (increasing depth) then decrescendo (decreasing depth) respirations, followed by a period of apnea, then repeating. It is associated with severe brain injury, heart failure, and altitude.',
    term: 'Cheyne-Stokes breathing',
    definition: 'Alternating crescendo/decrescendo respiratory depth with episodes of apnea; associated with severe neurological injury or heart failure.',
  },
  {
    id: 'ha2-ch13-q5',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'A 10-year-old with asthma comes to the clinic complaining of increased shortness of breath with exercise. Which of the following is a recognized risk factor for asthma in this patient?',
    options: [
      'Being female and having a history of chickenpox',
      'Exposure to secondhand smoke, personal history of eczema',
      'Being tall and athletic',
      'Having up-to-date immunizations',
    ],
    answer: 1,
    explanation: 'Risk factors for asthma include: family history of atopy (eczema, allergic rhinitis), exposure to indoor/outdoor allergens, secondhand tobacco smoke, respiratory infections, and male sex in children. Having up-to-date immunizations is protective.',
    term: 'Asthma',
    definition: 'A chronic inflammatory airway disorder with reversible bronchospasm; risk factors include atopy, allergen exposure, and tobacco smoke exposure.',
  },
  {
    id: 'ha2-ch13-q6',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'Routine examination of the respiratory system includes all of the following EXCEPT:',
    options: [
      'Inspection of posture and breathing effort',
      'Counting respirations and observing breathing patterns',
      'Measuring oxygen saturation',
      'Percussing the cerebellum for coordination',
    ],
    answer: 3,
    explanation: 'Routine respiratory examination includes inspection (appearance, posture, breathing effort), counting respirations, oxygen saturation measurement, nail/skin/lip inspection, and thorax inspection, palpation, and auscultation. Cerebellar percussion is a neurological assessment.',
  },
  {
    id: 'ha2-ch13-q7',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'Wheezing is an adventitious breath sound caused by:',
    options: [
      'Fluid or secretions in the large airways',
      'Narrowed airways (bronchospasm or obstruction) causing turbulent airflow',
      'Air entering previously collapsed alveoli',
      'Pleural surfaces rubbing together',
    ],
    answer: 1,
    explanation: 'Wheezing is a high-pitched musical sound caused by narrowed airways — from bronchospasm (asthma), secretions, or obstruction. Crackles (rales) are from fluid/secretions. Pleural friction rub is from inflamed pleural surfaces rubbing.',
    term: 'Adventitious breath sounds',
    definition: 'Abnormal breath sounds superimposed on normal sounds; includes wheezing (narrowed airways), crackles/rales (fluid), and pleural friction rub.',
  },
  {
    id: 'ha2-ch13-q8',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'A pneumothorax is best described as:',
    options: [
      'Blood accumulation in the pleural space',
      'Air accumulation in the pleural space, causing lung collapse',
      'Fluid accumulation in the alveoli',
      'Inflammation of the lung parenchyma from infection',
    ],
    answer: 1,
    explanation: 'Pneumothorax is air in the pleural space (normally a vacuum), causing the lung to collapse. Hemothorax is blood in the pleural space. Pneumonia is alveolar inflammation/infection. Pulmonary edema is fluid in alveoli.',
    term: 'Pneumothorax',
    definition: 'Air accumulation in the pleural space causing lung collapse; presents with absent breath sounds on the affected side, tracheal deviation, and respiratory distress.',
  },
  {
    id: 'ha2-ch13-q9',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'Tachypnea is defined as:',
    options: [
      'A respiratory rate below 12 breaths per minute',
      'A respiratory rate above 20 breaths per minute in adults',
      'Deep, labored breathing',
      'Painful breathing',
    ],
    answer: 1,
    explanation: 'Tachypnea = rapid breathing (> 20 breaths/min in adults). Bradypnea = slow breathing (< 12/min). Eupnea = normal rate. Dyspnea = difficulty breathing (subjective). Kussmaul = deep, rapid (metabolic acidosis). Hyperpnea = deep breathing, rate may be normal.',
    term: 'Tachypnea',
    definition: 'Respiratory rate above 20 breaths per minute in adults; may indicate infection, pain, respiratory distress, or metabolic acidosis.',
  },
  {
    id: 'ha2-ch13-q10',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'Gas exchange in the lungs requires adequate perfusion, which means:',
    options: [
      'Delivering oxygenated blood to tissues and removing CO2 via the pulmonary circulation',
      'Ventilating alveoli with fresh air through inhalation',
      'Buffering blood pH through the bicarbonate system',
      'Filtering toxins from the blood via the kidneys',
    ],
    answer: 0,
    explanation: 'Perfusion refers to the delivery of oxygenated blood to tissues (and removal of CO2) via the circulatory system. Gas exchange requires both ventilation (air moving into alveoli) and perfusion (blood flowing past alveoli). V/Q mismatch impairs gas exchange.',
    term: 'Gas exchange',
    definition: 'The process of O2 moving from alveoli into blood and CO2 moving from blood into alveoli; requires adequate ventilation and perfusion.',
  },
  {
    id: 'ha2-ch13-q11',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'Which of the following is a chronic pulmonary disease characterized by airflow obstruction and includes emphysema and chronic bronchitis?',
    options: [
      'Pneumonia',
      'Tuberculosis',
      'COPD (Chronic Obstructive Pulmonary Disease)',
      'Pleuritis',
    ],
    answer: 2,
    explanation: 'COPD (Chronic Obstructive Pulmonary Disease) is an umbrella term encompassing emphysema (alveolar destruction, air trapping) and chronic bronchitis (persistent productive cough ≥ 3 months/year for 2+ years). Major risk factor: tobacco smoking.',
    term: 'COPD',
    definition: 'Chronic Obstructive Pulmonary Disease; encompasses emphysema and chronic bronchitis; characterized by persistent airflow obstruction, primarily caused by tobacco smoke.',
  },
  {
    id: 'ha2-ch13-q12',
    subject: 'health-assessment' as const,
    chapter: 13,
    type: 'mc',
    question: 'Tuberculosis (TB) is caused by which organism and is spread primarily by:',
    options: [
      'Staphylococcus aureus, spread by direct contact',
      'Mycobacterium tuberculosis, spread by airborne droplet nuclei',
      'Streptococcus pneumoniae, spread by respiratory secretions',
      'Candida albicans, spread by immunosuppression',
    ],
    answer: 1,
    explanation: 'TB is caused by Mycobacterium tuberculosis and is spread by airborne droplet nuclei when infected individuals cough, sneeze, or speak. It primarily affects the lungs but can disseminate to other organs.',
    term: 'Tuberculosis (TB)',
    definition: 'A pulmonary infection caused by Mycobacterium tuberculosis; spread by airborne droplet nuclei; may be latent or active.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 14 — Cardiovascular System
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'ha2-ch14-q1',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'When auscultating heart sounds, the nurse hears the best aortic valve sounds at which landmark?',
    options: [
      'Left midclavicular line (5th intercostal space)',
      'Left lower sternal border (4th intercostal space)',
      'Right upper sternal border (2nd intercostal space)',
      'Erb\'s point (3rd left intercostal space)',
    ],
    answer: 2,
    explanation: 'Heart auscultation landmarks: Aortic = right upper sternal border (2nd ICS); Pulmonic = left upper sternal border (2nd ICS); Erb\'s point = 3rd left ICS; Tricuspid = left lower sternal border (4th ICS); Mitral = left midclavicular line (5th ICS, apex).',
    term: 'Heart auscultation sites',
    definition: 'Aortic (right 2nd ICS), Pulmonic (left 2nd ICS), Erb\'s point (left 3rd ICS), Tricuspid (left 4th ICS), Mitral/Apex (left 5th ICS, MCL).',
  },
  {
    id: 'ha2-ch14-q2',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'A patient awaiting mitral valve repair surgery would most likely have their heart murmur heard best at:',
    options: [
      'The right upper sternal border',
      'The left upper sternal border',
      'Erb\'s point',
      'The left midclavicular line (apex)',
    ],
    answer: 3,
    explanation: 'Mitral valve sounds are auscultated at the apex — the left midclavicular line at the 5th intercostal space. Mitral valve disorders (stenosis or regurgitation) produce murmurs best heard at this location.',
  },
  {
    id: 'ha2-ch14-q3',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'During cardiac auscultation, S1 represents which cardiac event?',
    options: [
      'Closure of the aortic and pulmonic valves at the start of diastole',
      'Closure of the mitral and tricuspid valves at the start of systole ("lub")',
      'Opening of the aortic and pulmonic valves during systole',
      'Atrial contraction just before ventricular systole',
    ],
    answer: 1,
    explanation: 'S1 ("lub") is produced by mitral and tricuspid (AV) valve closure at the beginning of systole. S2 ("dub") is produced by aortic and pulmonic valve closure at the end of systole/beginning of diastole.',
    term: 'S1 heart sound',
    definition: 'The first heart sound ("lub") produced by closure of the mitral and tricuspid (AV) valves at the beginning of ventricular systole.',
  },
  {
    id: 'ha2-ch14-q4',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'A patient with bilateral +2 pitting edema, dry scaling skin, and an undetectable dorsalis pedis pulse with warm feet. What is the best initial action?',
    options: [
      'Call the physician immediately',
      'Assess skin turgor over the clavicle',
      'Use a Doppler device and assess capillary refill',
      'Assess for renal artery stenosis',
    ],
    answer: 2,
    explanation: 'When a peripheral pulse cannot be palpated, the next step is to use a Doppler ultrasound to determine if flow is present. Warm feet suggest venous insufficiency (not arterial occlusion), and the Doppler will help confirm perfusion status before escalating.',
  },
  {
    id: 'ha2-ch14-q5',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'Systole refers to which phase of the cardiac cycle?',
    options: [
      'The phase when the heart fills with blood (relaxation phase)',
      'The phase when the ventricles contract and eject blood',
      'The period between S1 and S2 when the heart rests',
      'Atrial relaxation after the P wave on ECG',
    ],
    answer: 1,
    explanation: 'Systole = ventricular contraction (ejection phase); begins with S1 (AV valve closure) and ends with S2 (semilunar valve closure). Diastole = ventricular relaxation and filling; the phase between S2 and the next S1.',
    term: 'Systole',
    definition: 'The phase of the cardiac cycle when the ventricles contract and eject blood; bounded by S1 (start) and S2 (end).',
  },
  {
    id: 'ha2-ch14-q6',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'Routine cardiovascular examination of the peripheral vascular system includes:',
    options: [
      'Palpating carotid pulses, inspecting jugular veins, and measuring blood pressure',
      'Percussing the precordium for dullness',
      'Auscultating the temporal lobes',
      'Inspecting pupillary reflexes',
    ],
    answer: 0,
    explanation: 'Peripheral vascular assessment includes: palpating carotid pulses, inspecting jugular veins, measuring BP, inspecting and palpating upper and lower extremities, and palpating peripheral pulses (radial, brachial, dorsalis pedis, posterior tibial).',
  },
  {
    id: 'ha2-ch14-q7',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'Which cardiovascular condition is characterized by chest pain from decreased coronary blood flow, often precipitated by exertion?',
    options: [
      'Pericarditis',
      'Heart failure',
      'Angina pectoris',
      'Venous thromboembolism',
    ],
    answer: 2,
    explanation: 'Angina pectoris is chest pain/discomfort resulting from myocardial ischemia — insufficient coronary blood flow to meet myocardial oxygen demand. Stable angina is triggered by exertion; unstable angina occurs at rest and is a medical emergency.',
    term: 'Angina pectoris',
    definition: 'Chest pain or discomfort from myocardial ischemia (insufficient coronary blood flow); stable angina is triggered by exertion, unstable angina occurs at rest.',
  },
  {
    id: 'ha2-ch14-q8',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'Left ventricular failure (left-sided heart failure) most commonly presents with:',
    options: [
      'Peripheral edema, jugular venous distension, and hepatomegaly',
      'Pulmonary congestion, dyspnea, orthopnea, and crackles in the lungs',
      'Ascites and splenomegaly',
      'Hypertension and tachycardia only',
    ],
    answer: 1,
    explanation: 'Left-sided heart failure causes backup of blood into the pulmonary circulation: pulmonary congestion, dyspnea, orthopnea (must sit upright to breathe), paroxysmal nocturnal dyspnea, and crackles (rales). Right-sided failure causes peripheral/systemic congestion: edema, JVD, hepatomegaly.',
    term: 'Left ventricular failure',
    definition: 'Failure of the left ventricle causing pulmonary congestion: dyspnea, orthopnea, paroxysmal nocturnal dyspnea, and pulmonary crackles.',
  },
  {
    id: 'ha2-ch14-q9',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'Hypertension is defined as blood pressure ≥ 130/80 mmHg (Stage 1). Which of the following is a modifiable risk factor for hypertension?',
    options: [
      'Age',
      'Family history',
      'Biological sex',
      'Obesity and high sodium intake',
    ],
    answer: 3,
    explanation: 'Modifiable HTN risk factors: obesity, high sodium/low potassium intake, physical inactivity, tobacco use, excessive alcohol, stress. Non-modifiable: age, family history, race, sex. Identifying modifiable factors guides lifestyle interventions.',
    term: 'Hypertension',
    definition: 'Blood pressure persistently ≥ 130/80 mmHg; a major risk factor for stroke, CAD, and renal disease; managed with lifestyle changes and medications.',
  },
  {
    id: 'ha2-ch14-q10',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'An apical pulse is auscultated at which anatomical location?',
    options: [
      'Right upper sternal border, 2nd intercostal space',
      'Left midclavicular line, 5th intercostal space (cardiac apex)',
      'Epigastric area below the xiphoid process',
      'Right lower sternal border, 4th intercostal space',
    ],
    answer: 1,
    explanation: 'The apical pulse is auscultated at the cardiac apex — left midclavicular line at the 5th intercostal space. This is also the mitral (M) site. The apical pulse reflects direct ventricular contraction and is the most accurate pulse site.',
    term: 'Apical pulse',
    definition: 'The heart rate auscultated at the cardiac apex (left 5th ICS, MCL); the most accurate pulse site, reflecting direct ventricular contraction.',
  },
  {
    id: 'ha2-ch14-q11',
    subject: 'health-assessment' as const,
    chapter: 14,
    type: 'mc',
    question: 'Peripheral artery disease (PAD) differs from peripheral venous disease (PVD) in that PAD is characterized by:',
    options: [
      'Varicose veins and dependent edema that worsens with prolonged standing',
      'Intermittent claudication (leg pain with exercise), reduced pulses, cool extremities, and thin/shiny skin',
      'Deep vein thrombosis and unilateral leg swelling',
      'Bounding peripheral pulses and flushed extremities',
    ],
    answer: 1,
    explanation: 'PAD (arterial): intermittent claudication, absent/reduced pulses, cool/pale/cyanotic extremities, thin/shiny skin, hair loss, slow healing. PVD/venous insufficiency: dependent edema, varicosities, brawny skin, stasis ulcers, normal pulses.',
    term: 'Peripheral artery disease (PAD)',
    definition: 'Arterial occlusive disease of peripheral vessels; presents with intermittent claudication, reduced pulses, cool extremities, and thin/shiny skin.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 15 — Abdomen
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'ha2-ch15-q1',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'The correct sequence for abdominal assessment is:',
    options: [
      'Inspection → Percussion → Palpation → Auscultation',
      'Palpation → Inspection → Auscultation → Percussion',
      'Inspection → Auscultation → Percussion → Palpation',
      'Auscultation → Palpation → Inspection → Percussion',
    ],
    answer: 2,
    explanation: 'Abdominal assessment follows a unique order: Inspection → Auscultation → Percussion → Palpation (IAPP). Palpation is done LAST because it can alter bowel sounds and cause guarding, affecting subsequent assessment steps. This differs from the standard IPPA used elsewhere.',
    term: 'Abdominal assessment sequence',
    definition: 'Inspection → Auscultation → Percussion → Palpation (IAPP); auscultation before palpation to avoid altering bowel sounds.',
  },
  {
    id: 'ha2-ch15-q2',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'The four abdominal quadrants are named:',
    options: [
      'Superior, Inferior, Medial, Lateral',
      'Right Upper, Right Lower, Left Upper, Left Lower',
      'Anterior, Posterior, Dorsal, Ventral',
      'Epigastric, Umbilical, Hypogastric, Iliac',
    ],
    answer: 1,
    explanation: 'The abdomen is divided into 4 quadrants: Right Upper Quadrant (RUQ — liver, gallbladder), Left Upper Quadrant (LUQ — stomach, spleen), Right Lower Quadrant (RLQ — appendix, right ovary), Left Lower Quadrant (LLQ — sigmoid colon, left ovary).',
    term: 'Abdominal quadrants',
    definition: 'RUQ (liver, gallbladder), LUQ (stomach, spleen), RLQ (appendix, cecum), LLQ (sigmoid colon); used to document location of abdominal findings.',
  },
  {
    id: 'ha2-ch15-q3',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'Normal bowel sounds are described as:',
    options: [
      'High-pitched rushing sounds heard every 5–15 seconds (active gurgles)',
      'Absent sounds in all four quadrants',
      'A harsh scratching sound synchronous with respiration',
      'Low-pitched continuous hums',
    ],
    answer: 0,
    explanation: 'Normal bowel sounds are intermittent, gurgling sounds heard at a rate of 5–30/minute. Hypoactive sounds (< 5/min) suggest reduced peristalsis (ileus, post-op). Hyperactive sounds suggest increased peristalsis (gastroenteritis, early obstruction).',
    term: 'Bowel sounds',
    definition: 'Intermittent gurgling sounds from intestinal peristalsis; normal rate 5–30/minute; absent in ileus, hyperactive in gastroenteritis or early bowel obstruction.',
  },
  {
    id: 'ha2-ch15-q4',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'When percussing the kidneys for tenderness (costovertebral angle tenderness), the nurse should:',
    options: [
      'Start tapping at the level of T1',
      'Tap firmly in the costovertebral angle (CVA)',
      'Use the indirect method over the spine',
      'Ask the patient about cholelithiasis history first',
    ],
    answer: 1,
    explanation: 'Costovertebral angle (CVA) tenderness is assessed by tapping (fist percussion) at the costovertebral angle — where the 12th rib meets the spine. Significant pain = positive CVA tenderness, suggesting renal pathology (pyelonephritis, kidney stone).',
    term: 'Costovertebral angle (CVA) tenderness',
    definition: 'Tenderness elicited by fist percussion at the angle where the 12th rib meets the spine; positive finding suggests pyelonephritis or kidney stone.',
  },
  {
    id: 'ha2-ch15-q5',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'A 44-year-old male presents with gas, belching, and food regurgitation after eating spicy foods, worsening over 2 months. He has a BMI in the obese range. This presentation is most consistent with:',
    options: [
      'Peptic ulcer disease',
      'Pancreatitis',
      'Gastroesophageal reflux disease (GERD)',
      'Diverticulitis',
    ],
    answer: 2,
    explanation: 'GERD presents with heartburn, regurgitation, gas, and belching, worsened by spicy/fatty foods, large meals, lying down, and obesity. Risk factors include obesity, hiatal hernia, and pregnancy. Antacids provide temporary relief.',
    term: 'GERD',
    definition: 'Gastroesophageal reflux disease; caused by reflux of stomach acid into the esophagus; worsened by obesity, spicy foods, and lying down.',
  },
  {
    id: 'ha2-ch15-q6',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'The liver is found in which abdominal quadrant and is assessed by:',
    options: [
      'Left lower quadrant; palpated below the left costal margin',
      'Right upper quadrant; palpated below the right costal margin and percussed for size',
      'Epigastric region; auscultated for bruits',
      'Right lower quadrant; assessed for rebound tenderness',
    ],
    answer: 1,
    explanation: 'The liver occupies the RUQ. It is palpated below the right costal margin (may be felt on deep inspiration) and percussed to determine its span (normal 6–12 cm in the MCL). Hepatomegaly is > 12 cm span.',
    term: 'Hepatomegaly',
    definition: 'Liver enlargement (> 12 cm percussion span at the midclavicular line); associated with hepatitis, cirrhosis, right heart failure, and malignancy.',
  },
  {
    id: 'ha2-ch15-q7',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'Inflammatory bowel disease (IBD) includes which two chronic conditions?',
    options: [
      'Gastritis and peptic ulcer disease',
      'Irritable bowel syndrome and diverticulitis',
      'Crohn\'s disease and ulcerative colitis',
      'Appendicitis and cholecystitis',
    ],
    answer: 2,
    explanation: 'IBD includes Crohn\'s disease (can affect any part of the GI tract, transmural inflammation, skip lesions) and ulcerative colitis (limited to the colon and rectum, mucosal inflammation, continuous lesions).',
    term: 'Inflammatory bowel disease (IBD)',
    definition: 'Umbrella term for Crohn\'s disease (any GI tract, transmural) and ulcerative colitis (colon/rectum, mucosal); both characterized by chronic intestinal inflammation.',
  },
  {
    id: 'ha2-ch15-q8',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'When beginning an abdominal examination, the nurse should first:',
    options: [
      'Begin with palpation if the patient is in pain',
      'Ask the patient to straighten their legs flat for the examination',
      'Observe the patient\'s general appearance, behavior, and position',
      'Ask the patient about vascular sounds in the abdomen',
    ],
    answer: 2,
    explanation: 'The abdominal exam begins with observing the patient\'s general appearance, behavior, and position — a key assessment principle. The patient should have knees slightly flexed (not straight) to relax the abdominal muscles. Palpation is always last.',
  },
  {
    id: 'ha2-ch15-q9',
    subject: 'health-assessment' as const,
    chapter: 15,
    type: 'mc',
    question: 'The spleen is located in which abdominal quadrant?',
    options: [
      'Right upper quadrant (RUQ)',
      'Right lower quadrant (RLQ)',
      'Left upper quadrant (LUQ)',
      'Left lower quadrant (LLQ)',
    ],
    answer: 2,
    explanation: 'The spleen is located in the LUQ, posterior to the stomach. It is normally non-palpable. Splenomegaly (enlarged spleen) may be felt below the left costal margin. Trauma to the LUQ can cause splenic rupture — a surgical emergency.',
    term: 'Spleen',
    definition: 'An organ in the LUQ; normally non-palpable; splenomegaly may be detected by palpation below the left costal margin.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CHAPTER 19 — Degenerative Changes in Aging
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'ha2-ch19-q1',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Senescence is best defined as:',
    options: [
      'A sudden deterioration caused by a specific disease',
      'The normal, progressive, universal decline in physiologic capacity associated with aging',
      'A genetic mutation causing accelerated aging',
      'Cognitive decline specific to Alzheimer disease',
    ],
    answer: 1,
    explanation: 'Senescence is the gradual, normal, universal process of aging — progressive decrease in physiological capacity, increased vulnerability to disease, and decreased adaptation to environmental stimuli. It is distinct from pathological aging.',
    term: 'Senescence',
    definition: 'The normal, progressive, universal process of biological aging; characterized by decreased physiologic capacity and increased vulnerability to disease.',
  },
  {
    id: 'ha2-ch19-q2',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Which theory of aging proposes that accumulated DNA damage and genetic mutations accumulate over time and drive the aging process?',
    options: [
      'Immunologic theory',
      'Neuroendocrine theory',
      'Somatic mutation/accumulated mutations theory',
      'Antagonistic pleiotropy theory',
    ],
    answer: 2,
    explanation: 'Somatic mutation and accumulated mutations theories propose that DNA damage accumulates over time (from radiation, reactive oxygen species, etc.) and eventually impairs cellular function, leading to aging. Free radical theory is a related stochastic theory.',
    term: 'Theories of aging',
    definition: 'Include developmental theories (accumulated mutations, immunologic, antagonistic pleiotropy, neuroendocrine) and stochastic theories (free radical, somatic mutation).',
  },
  {
    id: 'ha2-ch19-q3',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Normal skin changes associated with aging include all of the following EXCEPT:',
    options: [
      'Increased dryness and wrinkles',
      'Decreased elasticity',
      'Varied pigmentation patterns',
      'Increased subcutaneous fat deposition and thickening',
    ],
    answer: 3,
    explanation: 'Normal skin aging includes increased dryness, wrinkles, decreased elasticity, and varied pigmentation (age spots). Subcutaneous fat actually DECREASES with aging, contributing to wrinkling and loss of insulation. Hair also thins and grays.',
    term: 'Skin aging changes',
    definition: 'Normal aging: increased dryness, wrinkles, decreased elasticity, varied pigmentation, thinning skin, decreased subcutaneous fat, hair thinning and graying.',
  },
  {
    id: 'ha2-ch19-q4',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Age-related changes in fluid and electrolyte balance in older adults include:',
    options: [
      'Increased total body water and improved renal sodium regulation',
      'Decreased total body water, reduced renal function, and altered sodium balance',
      'Increased muscle mass and improved hormone regulation',
      'Enhanced ADH response and greater thirst sensation',
    ],
    answer: 1,
    explanation: 'Aging causes decreased total body water, decreased muscle mass (replaced by fat), decreased renal function (GFR, renal blood flow), and altered sodium and elimination balance. Older adults are more vulnerable to dehydration and electrolyte imbalances.',
    term: 'Aging and fluid balance',
    definition: 'Aging decreases total body water, muscle mass, and renal function, making older adults more vulnerable to dehydration and electrolyte imbalances.',
  },
  {
    id: 'ha2-ch19-q5',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Immune senescence refers to:',
    options: [
      'The sudden failure of the immune system due to AIDS',
      'Progressive dysfunction of the immune system associated with normal aging',
      'The development of autoimmune disorders in young adults',
      'Hypersensitivity reactions becoming more severe with age',
    ],
    answer: 1,
    explanation: 'Immune senescence is the gradual, progressive decline in immune system function associated with normal aging. It increases risk of infection, cancer (due to impaired immune surveillance), and reduced vaccine efficacy.',
    term: 'Immune senescence',
    definition: 'Progressive dysfunction of the immune system associated with aging; increases susceptibility to infection and cancer.',
  },
  {
    id: 'ha2-ch19-q6',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Sarcopenia is the age-related:',
    options: [
      'Loss of bone density',
      'Loss of lean muscle mass and muscle strength',
      'Progressive loss of cartilage in joints',
      'Accumulation of calcium in vascular smooth muscle',
    ],
    answer: 1,
    explanation: 'Sarcopenia is the age-related progressive loss of lean muscle mass and strength. It contributes to falls, functional decline, and disability in older adults. Osteoporosis is bone mass loss. Kyphosis is spinal curvature.',
    term: 'Sarcopenia',
    definition: 'Age-related loss of lean muscle mass and strength; contributes to falls, functional decline, and disability in older adults.',
  },
  {
    id: 'ha2-ch19-q7',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Osteoporosis is classified as which DEXA scan T-score?',
    options: [
      'T score > 0',
      'T score between -1.0 and -2.5 (osteopenia)',
      'T score < -2.5',
      'T score between -0.5 and -1.0',
    ],
    answer: 2,
    explanation: 'DEXA bone density T-scores: Normal = > -1.0; Osteopenia = -1.0 to -2.5; Osteoporosis = < -2.5. Osteoporosis significantly increases fracture risk, especially in the spine, hip, and wrist.',
    term: 'Osteoporosis',
    definition: 'Loss of bone mass with T-score < -2.5 on DEXA scan; characterized by imbalance favoring bone resorption over formation; increases fracture risk.',
  },
  {
    id: 'ha2-ch19-q8',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Risk factors for osteoporosis include all of the following EXCEPT:',
    options: [
      'Loss of estrogen (menopause)',
      'Sedentary lifestyle',
      'Excessive alcohol use and cigarette smoking',
      'High-impact weight-bearing exercise',
    ],
    answer: 3,
    explanation: 'Weight-bearing exercise is PROTECTIVE against osteoporosis — it stimulates bone remodeling and increases bone density. Risk factors include: family history, estrogen loss, aging, low calcium/vitamin D, smoking, excessive alcohol, and sedentary lifestyle.',
    term: 'Osteoporosis risk factors',
    definition: 'Includes: family history, estrogen loss, aging, low calcium/vitamin D, smoking, excessive alcohol, and sedentary lifestyle; weight-bearing exercise is protective.',
  },
  {
    id: 'ha2-ch19-q9',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'The recommended daily calcium intake for adults over 50 to prevent osteoporosis is approximately:',
    options: [
      '500 mg/day in one dose',
      '800 mg/day',
      '1200 mg/day in divided doses',
      '2000 mg/day',
    ],
    answer: 2,
    explanation: 'Adults over 50 need 1200 mg/day of calcium in divided doses (calcium is absorbed more efficiently in smaller doses). Vitamin D 400–600 IU/day is also recommended to enhance calcium absorption. Magnesium is needed to activate Vitamin D.',
    term: 'Calcium intake (aging)',
    definition: 'Adults over 50: 1200 mg/day in divided doses + Vitamin D 400-600 IU/day; magnesium needed to activate Vitamin D.',
  },
  {
    id: 'ha2-ch19-q10',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Alzheimer disease pathophysiology involves all of the following EXCEPT:',
    options: [
      'Neurofibrillary tangles (tau protein)',
      'Senile plaques (beta-amyloid protein)',
      'Neuronal atrophy and inflammation',
      'Demyelination of peripheral motor nerves',
    ],
    answer: 3,
    explanation: 'Alzheimer disease pathology includes neurofibrillary tangles (abnormal tau protein), senile plaques (beta-amyloid deposits), neuronal atrophy, and inflammation in the brain. Demyelination of peripheral nerves is characteristic of diseases like MS and Guillain-Barré, not Alzheimer.',
    term: 'Alzheimer disease',
    definition: 'A neurodegenerative disorder characterized by neurofibrillary tangles (tau), senile plaques (beta-amyloid), neuronal atrophy, and progressive cognitive decline.',
  },
  {
    id: 'ha2-ch19-q11',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Age-related cardiovascular changes include all of the following EXCEPT:',
    options: [
      'Decreased elasticity of vascular smooth muscle',
      'Increased left ventricular wall thickness',
      'Atherosclerosis progression',
      'Increased cardiac output and heart rate reserve',
    ],
    answer: 3,
    explanation: 'Aging cardiovascular changes: decreased vascular elasticity (increased afterload), increased LV wall thickness, progressive atherosclerosis, and reduced pulmonary capillary density. Cardiac output and heart rate RESERVE decrease with age, not increase.',
    term: 'Aging cardiovascular changes',
    definition: 'Includes decreased vascular elasticity, increased LV wall thickness, atherosclerosis, and reduced cardiac reserve; all increase risk of cardiac disease.',
  },
  {
    id: 'ha2-ch19-q12',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Age-related renal changes include reduced GFR and decreased renal blood flow. A clinically important consequence is:',
    options: [
      'Increased drug excretion, requiring higher medication doses',
      'Impaired drug excretion, increasing risk of drug toxicity',
      'Enhanced sodium retention and hyponatremia prevention',
      'Increased urinary output and improved hydration',
    ],
    answer: 1,
    explanation: 'Reduced GFR and renal blood flow in aging impairs drug excretion, significantly increasing the risk of drug accumulation and toxicity. Many medications (digoxin, NSAIDs, antibiotics) must be dose-adjusted in older adults for this reason.',
    term: 'Aging and renal function',
    definition: 'Aging reduces renal blood flow, GFR, renal mass, and nephron number; impairs drug excretion, increasing toxicity risk; also causes urinary incontinence.',
  },
  {
    id: 'ha2-ch19-q13',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Age-related neurological changes include all of the following EXCEPT:',
    options: [
      'Decreased brain mass and enlarged cerebral ventricles',
      'Decreased motor response speed and reflexes',
      'Decreased number of neurons and synapses',
      'Enhanced sensory acuity and faster pain response',
    ],
    answer: 3,
    explanation: 'Neurological aging changes: decreased brain mass, enlarged ventricles, decreased neurons/synapses/dendritic processes, slower motor responses, decreased reflexes, and reduced sensory acuity (hearing, vision, pain threshold). Sensory acuity DECREASES, not increases, with age.',
    term: 'Aging neurological changes',
    definition: 'Decreased brain mass, enlarged cerebral ventricles, fewer neurons/synapses, slower motor responses, reduced reflexes, and decreased sensory acuity.',
  },
  {
    id: 'ha2-ch19-q14',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'The SAFETY priority for patients with Alzheimer disease is critical because:',
    options: [
      'Alzheimer is primarily a physical disability requiring fall prevention only',
      'Cognitive decline impairs judgment, memory, and ability to recognize hazards, creating multiple safety risks',
      'Alzheimer patients are prone to violent outbursts requiring restraints',
      'Memory loss only affects long-term memory, leaving daily function intact',
    ],
    answer: 1,
    explanation: 'Alzheimer disease causes progressive cognitive decline — memory loss, confusion, impaired judgment, and difficulty with visual/spatial information — severely impairing the ability to recognize and respond to hazards. Safety (falls, wandering, medication management) is the top nursing priority.',
    term: 'Alzheimer disease management',
    definition: 'Focuses on safety, maximizing quality of life, promoting general health, and pharmacologic therapy (cholinesterase inhibitors, antidepressants, antipsychotics).',
  },
  {
    id: 'ha2-ch19-q15',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Hutchinson-Gilford progeria syndrome is relevant to aging studies because:',
    options: [
      'It is the most common form of dementia in older adults',
      'It is a rare genetic disorder causing dramatically accelerated aging in children',
      'It is a form of osteoporosis specific to children',
      'It represents the standard model of normal senescence',
    ],
    answer: 1,
    explanation: 'Progeria (Hutchinson-Gilford progeria syndrome) is a rare genetic disorder in children causing premature and accelerated aging — cardiovascular disease, joint problems, and other age-related changes occur in early childhood. It is studied as an extreme model of aging processes.',
    term: 'Progeria',
    definition: 'Hutchinson-Gilford progeria syndrome; a rare genetic disorder causing dramatically accelerated aging in children, used to study aging mechanisms.',
  },
  {
    id: 'ha2-ch19-q16',
    subject: 'health-assessment' as const,
    chapter: 19,
    type: 'mc',
    question: 'Age-related bowel changes increase the risk of all of the following EXCEPT:',
    options: [
      'Constipation',
      'Fecal incontinence',
      'Fecal impaction',
      'Hyperactive peristalsis and diarrhea as the primary complaint',
    ],
    answer: 3,
    explanation: 'Age-related bowel changes typically include constipation, fecal incontinence, and fecal impaction — caused by reduced peristalsis, weaker sphincter muscles, and medication effects. While diarrhea can occur (especially with fecal impaction overflow), hyperactive peristalsis is not a primary age-related change.',
    term: 'Aging bowel changes',
    definition: 'Age-related: constipation, fecal incontinence, fecal impaction; caused by reduced peristalsis, weakened sphincters, and medications.',
  },
]
