export type Question = {
  id: string
  chapter: 1 | 2 | 3 | 4 | 5
  type: 'mc' | 'tf'
  question: string
  options: string[]
  answer: number
  explanation: string
  term?: string
  definition?: string
}

export const QUESTIONS: Question[] = [
  // ============ CHAPTER 1: Intro to Pathophysiology ============
  {
    id: 'c1-q1', chapter: 1, type: 'mc',
    question: 'Pathophysiology is best defined as the study of:',
    options: [
      'The structure of body organs and systems',
      'Functional changes in the body caused by injury, disorder, or disease',
      'The classification and naming of diseases',
      'Microorganisms that cause infection',
    ],
    answer: 1,
    explanation: 'Pathophysiology studies the FUNCTIONAL changes caused by injury, disorder, or disease. Anatomy studies structure, and microbiology studies microorganisms — those are related sciences, not pathophysiology itself.',
    term: 'Pathophysiology', definition: 'The study of functional changes in the body caused by injury, disorder, or disease.',
  },
  {
    id: 'c1-q2', chapter: 1, type: 'mc',
    question: 'A disease is defined as a functional impairment of cells, tissues, organs, or organ systems. It serves as an umbrella term that includes all of the following EXCEPT:',
    options: ['Injuries', 'Disorders', 'Syndromes', 'Homeostasis'],
    answer: 3,
    explanation: 'Disease is an umbrella term covering injuries, disorders, illnesses, and syndromes. Homeostasis is a steady state of balance — the opposite of disease, not a type of it.',
    term: 'Disease', definition: 'Functional impairment of cells, tissues, organs, or organ systems; umbrella term for injuries, disorders, illnesses, and syndromes.',
  },
  {
    id: 'c1-q3', chapter: 1, type: 'mc',
    question: 'The term that describes the origination and development of an illness or disease over time is:',
    options: ['Etiology', 'Pathogenesis', 'Prognosis', 'Diagnosis'],
    answer: 1,
    explanation: 'Pathogenesis is the origination and development of disease — from when the process begins to when it presents. Etiology is the cause; prognosis is the predicted course; diagnosis is labeling the disease.',
    term: 'Pathogenesis', definition: 'The origination and development of an illness or disease, from onset to clinical presentation.',
  },
  {
    id: 'c1-q4', chapter: 1, type: 'mc',
    question: 'Etiology refers to:',
    options: [
      'The predicted outcome of a disease',
      'The presenting signs and symptoms',
      'The exact cause of a disease',
      'The development of a disease over time',
    ],
    answer: 2,
    explanation: 'Etiology is the exact CAUSE of disease. The predicted outcome is prognosis, signs/symptoms are clinical manifestations, and development over time is pathogenesis.',
    term: 'Etiology', definition: 'The exact cause of a disease.',
  },
  {
    id: 'c1-q5', chapter: 1, type: 'mc',
    question: 'A patient develops a bloodstream infection three days after being admitted to the hospital for surgery. This infection is best classified as:',
    options: ['Idiopathic', 'Iatrogenic', 'Nosocomial', 'Multifactorial'],
    answer: 2,
    explanation: 'Nosocomial means an infection acquired in a healthcare environment. Iatrogenic is caused by medical treatment itself, idiopathic has no known cause, and multifactorial means multiple causes.',
    term: 'Nosocomial', definition: 'An infection acquired in a healthcare environment (e.g., a hospital).',
  },
  {
    id: 'c1-q6', chapter: 1, type: 'mc',
    question: 'A disease that arises as an unintended result of medical treatment is termed:',
    options: ['Nosocomial', 'Iatrogenic', 'Idiopathic', 'Endemic'],
    answer: 1,
    explanation: 'Iatrogenic disease is caused inadvertently by medical treatment (e.g., a medication side effect). Nosocomial is healthcare-environment acquired, idiopathic has no known cause, and endemic describes disease constantly present in a population.',
    term: 'Iatrogenic', definition: 'A condition caused inadvertently by medical treatment or intervention.',
  },
  {
    id: 'c1-q7', chapter: 1, type: 'mc',
    question: 'A condition with no identifiable cause is described as:',
    options: ['Multifactorial', 'Idiopathic', 'Iatrogenic', 'Pathogenic'],
    answer: 1,
    explanation: 'Idiopathic means no known cause. Multifactorial means several causes, iatrogenic is treatment-caused, and pathogenic refers to a disease-causing microorganism.',
    term: 'Idiopathic', definition: 'A disease or condition with no known or identifiable cause.',
  },
  {
    id: 'c1-q8', chapter: 1, type: 'mc',
    question: 'A disease-causing microorganism is called a:',
    options: ['Pathogen', 'Antigen', 'Antibody', 'Cytokine'],
    answer: 0,
    explanation: 'A pathogen is a disease-causing microorganism. An antigen triggers an immune response, an antibody is produced against antigens, and a cytokine is a signaling protein.',
    term: 'Pathogen', definition: 'A disease-causing microorganism.',
  },
  {
    id: 'c1-q9', chapter: 1, type: 'mc',
    question: 'When a disease has more than one contributing cause, it is described as:',
    options: ['Idiopathic', 'Multifactorial', 'Iatrogenic', 'Systemic'],
    answer: 1,
    explanation: 'Multifactorial means having more than one cause (e.g., heart disease from genetics + diet + smoking). Idiopathic means no known cause.',
    term: 'Multifactorial', definition: 'Having more than one contributing cause.',
  },
  {
    id: 'c1-q10', chapter: 1, type: 'mc',
    question: 'Which statement correctly distinguishes a sign from a symptom?',
    options: [
      'A sign is subjective; a symptom is objective',
      'A sign is objective and observable; a symptom is subjective and reported by the patient',
      'Signs and symptoms are the same thing',
      'A sign only occurs in chronic disease',
    ],
    answer: 1,
    explanation: 'A sign is objective and measurable/observable by others (e.g., fever, rash). A symptom is subjective — what the patient reports feeling (e.g., pain, nausea).',
    term: 'Sign vs. symptom', definition: 'A sign is objective and observable by others; a symptom is subjective and reported by the patient.',
  },
  {
    id: 'c1-q11', chapter: 1, type: 'mc',
    question: 'A patient with rheumatoid arthritis experiences a period where symptoms nearly disappear, followed later by a flare-up. These periods are called:',
    options: [
      'Acute and subacute phases',
      'Remissions and exacerbations',
      'Prodrome and convalescence',
      'Incidence and prevalence',
    ],
    answer: 1,
    explanation: 'A remission is a period when symptoms lessen or disappear; an exacerbation is a flare-up or worsening. This remission/exacerbation pattern is typical of many chronic diseases.',
    term: 'Remission vs. exacerbation', definition: 'Remission is a period of reduced or absent symptoms; exacerbation is a worsening or flare-up of the disease.',
  },
  {
    id: 'c1-q12', chapter: 1, type: 'mc',
    question: 'A disease process that has a rapid onset and short duration is described as:',
    options: ['Chronic', 'Acute', 'Idiopathic', 'Systemic'],
    answer: 1,
    explanation: 'Acute means rapid onset and short duration. Chronic means long-lasting or persistent. Subacute falls between the two.',
    term: 'Acute', definition: 'A disease with rapid onset and short duration.',
  },
  {
    id: 'c1-q13', chapter: 1, type: 'mc',
    question: 'A symptom present throughout the entire body, such as fever affecting the whole system, is described as:',
    options: ['Local', 'Systemic', 'Focal', 'Asymptomatic'],
    answer: 1,
    explanation: 'Systemic effects involve the whole body (e.g., fever, fatigue). Local effects are confined to one area. Focal is localized to a specific region; asymptomatic means no symptoms.',
    term: 'Systemic', definition: 'Affecting the entire body or multiple organ systems rather than a single localized area.',
  },
  {
    id: 'c1-q14', chapter: 1, type: 'mc',
    question: 'Labeling a disease based on diagnostic criteria is known as:',
    options: ['Prognosis', 'Diagnosis', 'Pathogenesis', 'Etiology'],
    answer: 1,
    explanation: 'Diagnosis is the act of labeling/identifying the disease based on diagnostic criteria. Prognosis predicts how the disease will progress.',
    term: 'Diagnosis', definition: 'The identification/labeling of a disease based on diagnostic criteria.',
  },
  {
    id: 'c1-q15', chapter: 1, type: 'mc',
    question: 'A prediction of how a patient will proceed through the disease process is called the:',
    options: ['Diagnosis', 'Etiology', 'Prognosis', 'Manifestation'],
    answer: 2,
    explanation: 'Prognosis is the prediction of the likely course and outcome of a disease. Diagnosis identifies the disease; etiology is its cause.',
    term: 'Prognosis', definition: 'The prediction of how a patient will progress through and recover from a disease.',
  },
  {
    id: 'c1-q16', chapter: 1, type: 'mc',
    question: 'Which pair correctly defines morbidity and mortality?',
    options: [
      'Morbidity = death rate; mortality = disease rate',
      'Morbidity = the rate of disease/illness; mortality = the rate of death',
      'Both refer to the death rate',
      'Both refer to the rate of recovery',
    ],
    answer: 1,
    explanation: 'Morbidity refers to the rate/burden of disease or illness in a population. Mortality refers to the rate of death. Students often reverse these — morbidity = sickness, mortality = death.',
    term: 'Morbidity vs. mortality', definition: 'Morbidity is the rate of disease/illness in a population; mortality is the rate of death.',
  },
  {
    id: 'c1-q17', chapter: 1, type: 'mc',
    question: 'Homeostasis is best described as:',
    options: [
      'A state of suffering or distress',
      'A steady state of balance in the body',
      'The exact cause of a disease',
      'An infection acquired in a hospital',
    ],
    answer: 1,
    explanation: 'Homeostasis is the body\u2019s steady state of internal balance. Illness is a state of suffering/distress; etiology is cause; nosocomial is hospital-acquired infection.',
    term: 'Homeostasis', definition: 'A steady state of internal balance maintained by the body.',
  },
  {
    id: 'c1-q18', chapter: 1, type: 'mc',
    question: 'Epidemiology is the study of health and disease in populations. Which pair does it use to measure disease frequency?',
    options: [
      'Signs and symptoms',
      'Incidence and prevalence',
      'Morbidity and etiology',
      'Diagnosis and prognosis',
    ],
    answer: 1,
    explanation: 'Epidemiology measures incidence (number of NEW cases in a period) and prevalence (total EXISTING cases at a point in time). Both describe disease frequency in populations.',
    term: 'Epidemiology', definition: 'The study of the distribution and determinants of health and disease in populations.',
  },
  {
    id: 'c1-q19', chapter: 1, type: 'mc',
    question: 'Which correctly distinguishes incidence from prevalence?',
    options: [
      'Incidence = total existing cases; prevalence = new cases',
      'Incidence = new cases over a period; prevalence = total existing cases at a point in time',
      'They mean the same thing',
      'Incidence applies only to chronic disease',
    ],
    answer: 1,
    explanation: 'Incidence counts NEW cases arising over a time period; prevalence counts ALL existing cases (new + old) at a given point. A quick memory hook: Incidence = Incoming.',
    term: 'Incidence vs. prevalence', definition: 'Incidence is the number of new cases over a period; prevalence is the total existing cases at a point in time.',
  },
  {
    id: 'c1-q20', chapter: 1, type: 'mc',
    question: 'A disease outbreak that spreads across multiple countries or worldwide is classified as a(n):',
    options: ['Endemic', 'Epidemic', 'Pandemic', 'Sporadic'],
    answer: 2,
    explanation: 'A pandemic spans multiple countries/continents (e.g., COVID-19). An epidemic is a sudden rise above normal in a region; endemic is the constant baseline level in a population.',
    term: 'Pandemic', definition: 'A disease epidemic that has spread across multiple countries or worldwide.',
  },
  {
    id: 'c1-q21', chapter: 1, type: 'mc',
    question: 'A disease that is constantly present at a predictable baseline level within a particular population or region is:',
    options: ['Epidemic', 'Pandemic', 'Endemic', 'Iatrogenic'],
    answer: 2,
    explanation: 'Endemic describes a disease constantly present at an expected baseline in a region (e.g., malaria in parts of Africa). Epidemic is a spike above baseline; pandemic is global spread.',
    term: 'Endemic', definition: 'A disease constantly present at a predictable baseline level in a specific population or region.',
  },
  {
    id: 'c1-q22', chapter: 1, type: 'mc',
    question: 'Administering childhood vaccinations to prevent disease from ever occurring is an example of which level of prevention?',
    options: ['Primary prevention', 'Secondary prevention', 'Tertiary prevention', 'Quaternary prevention'],
    answer: 0,
    explanation: 'Primary prevention stops disease before it occurs (vaccines, health education). Secondary is early detection/screening; tertiary is rehabilitation to limit complications of existing disease.',
    term: 'Primary prevention', definition: 'Prevention of disease before it occurs, e.g., vaccinations and health education.',
  },
  {
    id: 'c1-q23', chapter: 1, type: 'mc',
    question: 'A mammogram performed to detect breast cancer early in an asymptomatic woman is an example of:',
    options: ['Primary prevention', 'Secondary prevention', 'Tertiary prevention', 'Evidence-based practice'],
    answer: 1,
    explanation: 'Secondary prevention is early detection through screening (mammograms, blood pressure checks, Pap smears). Primary prevents disease entirely; tertiary rehabilitates after disease is established.',
    term: 'Secondary prevention', definition: 'Early detection of disease through screening before symptoms are advanced.',
  },
  {
    id: 'c1-q24', chapter: 1, type: 'mc',
    question: 'A stroke patient participating in physical therapy to regain function and prevent further complications is receiving:',
    options: ['Primary prevention', 'Secondary prevention', 'Tertiary prevention', 'Screening'],
    answer: 2,
    explanation: 'Tertiary prevention is rehabilitation of a patient with established disease to prevent complications or progression (e.g., rehab after a stroke or cardiac event).',
    term: 'Tertiary prevention', definition: 'Rehabilitation of a patient with established disease to prevent complications or progression.',
  },
  {
    id: 'c1-q25', chapter: 1, type: 'mc',
    question: 'Evidence-based practice is best characterized by which statement?',
    options: [
      'Relying on a single research study',
      'Following tradition and personal opinion only',
      'Integrating the totality of current research, knowledge, and expert practice with respect for human variation',
      'Using only the physician\u2019s preference',
    ],
    answer: 2,
    explanation: 'Evidence-based practice goes beyond any single study — it integrates the totality of current research, clinical knowledge, and expert practice, with conscientious respect for human health variations.',
    term: 'Evidence-based practice', definition: 'Care informed by the totality of current research, clinical knowledge, and expert practice, respecting human variation.',
  },
  {
    id: 'c1-q26', chapter: 1, type: 'mc',
    question: 'A modifiable risk factor is one that:',
    options: [
      'Cannot be changed, such as age or genetics',
      'Can be changed or controlled, such as smoking or diet',
      'Always causes disease',
      'Is the same as the etiology',
    ],
    answer: 1,
    explanation: 'Modifiable risk factors can be changed (smoking, diet, exercise, weight). Nonmodifiable risk factors cannot be changed (age, sex, genetics, family history).',
    term: 'Modifiable risk factor', definition: 'A risk factor that can be changed or controlled, such as smoking, diet, or activity level.',
  },
  {
    id: 'c1-q27', chapter: 1, type: 'tf',
    question: 'True or False: An asymptomatic patient has a disease but displays no symptoms.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Asymptomatic means the disease is present but produces no noticeable symptoms — common in early hypertension or early-stage cancers.',
    term: 'Asymptomatic', definition: 'Having a disease present but displaying no symptoms.',
  },
  {
    id: 'c1-q28', chapter: 1, type: 'tf',
    question: 'True or False: Prevalence measures only the number of new cases of a disease during a specific time period.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. That describes INCIDENCE (new cases). Prevalence measures the total number of existing cases at a point in time.',
  },
  {
    id: 'c1-q29', chapter: 1, type: 'tf',
    question: 'True or False: Age and genetics are examples of nonmodifiable risk factors.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Nonmodifiable risk factors cannot be changed — age, sex, race, and genetic/family history all qualify.',
    term: 'Nonmodifiable risk factor', definition: 'A risk factor that cannot be changed, such as age, sex, or genetics.',
  },
  {
    id: 'c1-q30', chapter: 1, type: 'mc',
    question: 'Which of the following is a goal of studying pathogenesis?',
    options: [
      'To assign blame for the disease',
      'To enable prevention, early diagnosis, and treatment',
      'To determine the death rate only',
      'To name the disease',
    ],
    answer: 1,
    explanation: 'Understanding pathogenesis (how disease develops) allows clinicians to prevent it, diagnose it early, and treat it effectively. Naming the disease is diagnosis, not the goal of studying pathogenesis.',
  },

  // ============ CHAPTER 2: Altered Cells & Tissues ============
  {
    id: 'c2-q1', chapter: 2, type: 'mc',
    question: 'Which cellular structure provides a protective barrier and regulates transport into and out of the cell to maintain homeostasis?',
    options: ['Nucleus', 'Plasma membrane', 'Mitochondria', 'Golgi apparatus'],
    answer: 1,
    explanation: 'The plasma membrane forms the protective barrier and controls what enters/exits the cell to maintain homeostasis. The nucleus holds DNA, mitochondria make ATP, and the Golgi packages proteins.',
    term: 'Plasma membrane', definition: 'The cell\u2019s outer barrier that protects it and regulates transport in and out to maintain homeostasis.',
  },
  {
    id: 'c2-q2', chapter: 2, type: 'mc',
    question: 'Which organelle is considered the \u201cpowerhouse\u201d of the cell, producing ATP?',
    options: ['Lysosome', 'Ribosome', 'Mitochondria', 'Peroxisome'],
    answer: 2,
    explanation: 'Mitochondria generate ATP (cellular energy). Lysosomes digest waste, ribosomes build proteins, and peroxisomes break down fatty acids and neutralize toxins.',
    term: 'Mitochondria', definition: 'The organelle that produces ATP, the cell\u2019s main energy source.',
  },
  {
    id: 'c2-q3', chapter: 2, type: 'mc',
    question: 'The movement of solute particles from an area of high concentration to an area of low concentration, requiring no energy, is called:',
    options: ['Osmosis', 'Diffusion', 'Active transport', 'Endocytosis'],
    answer: 1,
    explanation: 'Diffusion is passive movement of a solute down its concentration gradient (high to low), no energy required. Osmosis is specifically the movement of water; active transport requires energy.',
    term: 'Diffusion', definition: 'Passive movement of solute from an area of high concentration to low concentration; no energy required.',
  },
  {
    id: 'c2-q4', chapter: 2, type: 'mc',
    question: 'Osmosis specifically refers to the movement of:',
    options: [
      'Solutes across a membrane against a gradient',
      'Water from an area of low solute concentration to high solute concentration',
      'Large particles via vesicles',
      'Ions with the help of a carrier protein',
    ],
    answer: 1,
    explanation: 'Osmosis is the passive movement of WATER across a membrane toward the area of higher solute concentration (lower water concentration). It is a special case of diffusion involving water.',
    term: 'Osmosis', definition: 'Passive movement of water across a membrane from an area of low solute concentration to high solute concentration.',
  },
  {
    id: 'c2-q5', chapter: 2, type: 'mc',
    question: 'The sodium-potassium pump moves ions against their concentration gradients using ATP. This is an example of:',
    options: ['Diffusion', 'Osmosis', 'Facilitated transport', 'Active transport'],
    answer: 3,
    explanation: 'Active transport moves substances AGAINST their gradient and requires energy (ATP), like the sodium-potassium pump. Facilitated transport uses carriers but is still passive (no energy, moves down gradient).',
    term: 'Active transport', definition: 'Movement of a substance against its concentration gradient using cellular energy (ATP).',
  },
  {
    id: 'c2-q6', chapter: 2, type: 'mc',
    question: 'Facilitated transport differs from simple diffusion in that it:',
    options: [
      'Requires ATP',
      'Uses a carrier or channel protein to move substances down the gradient without energy',
      'Moves substances against the gradient',
      'Only moves water',
    ],
    answer: 1,
    explanation: 'Facilitated transport uses a carrier/channel protein to help substances (like glucose) cross the membrane down their gradient — still passive, no ATP. Active transport is what requires ATP and moves against the gradient.',
    term: 'Facilitated transport', definition: 'Passive movement of a substance down its gradient with the help of a carrier or channel protein; no energy required.',
  },
  {
    id: 'c2-q7', chapter: 2, type: 'mc',
    question: 'The increase in the number of cells in a tissue is termed:',
    options: ['Hypertrophy', 'Proliferation', 'Differentiation', 'Metaplasia'],
    answer: 1,
    explanation: 'Proliferation is an increase in the NUMBER of cells. Differentiation is the change in a cell\u2019s physical/functional properties; hypertrophy is an increase in cell SIZE.',
    term: 'Proliferation', definition: 'An increase in the number of cells.',
  },
  {
    id: 'c2-q8', chapter: 2, type: 'mc',
    question: 'The process by which cells develop specialized physical and functional properties is called:',
    options: ['Proliferation', 'Differentiation', 'Hyperplasia', 'Apoptosis'],
    answer: 1,
    explanation: 'Differentiation directs a cell to develop into a specific specialized type. Proliferation is simply an increase in cell number.',
    term: 'Differentiation', definition: 'The process by which cells develop specialized physical and functional properties.',
  },
  {
    id: 'c2-q9', chapter: 2, type: 'mc',
    question: 'A decrease in the size of cells, resulting in reduced tissue or organ size (such as muscle wasting after prolonged bed rest), is called:',
    options: ['Hypertrophy', 'Atrophy', 'Hyperplasia', 'Metaplasia'],
    answer: 1,
    explanation: 'Atrophy is a DECREASE in cell size leading to shrinkage of the tissue/organ (disuse, aging, denervation). Hypertrophy is the opposite — an increase in cell size.',
    term: 'Atrophy', definition: 'A decrease in the size of cells, causing reduced tissue or organ size.',
  },
  {
    id: 'c2-q10', chapter: 2, type: 'mc',
    question: 'A weightlifter\u2019s skeletal muscle cells enlarge in response to increased workload. This adaptive response is called:',
    options: ['Hyperplasia', 'Hypertrophy', 'Metaplasia', 'Dysplasia'],
    answer: 1,
    explanation: 'Hypertrophy is an increase in the SIZE of existing cells (like enlarged muscle from training or a thickened heart wall). Hyperplasia is an increase in the NUMBER of cells.',
    term: 'Hypertrophy', definition: 'An increase in the size of individual cells, enlarging the tissue or organ.',
  },
  {
    id: 'c2-q11', chapter: 2, type: 'mc',
    question: 'An increase in the number of cells in a tissue, such as endometrial thickening in response to estrogen, is called:',
    options: ['Hypertrophy', 'Hyperplasia', 'Atrophy', 'Dysplasia'],
    answer: 1,
    explanation: 'Hyperplasia is an increase in the NUMBER of cells. Compare with hypertrophy (increase in cell SIZE). A memory hook: hyperPLAsia = PLenty of cells.',
    term: 'Hyperplasia', definition: 'An increase in the number of cells in a tissue.',
  },
  {
    id: 'c2-q12', chapter: 2, type: 'mc',
    question: 'The reversible replacement of one mature cell type by another, such as columnar cells becoming squamous cells in the airway of a smoker, is called:',
    options: ['Metaplasia', 'Dysplasia', 'Hyperplasia', 'Anaplasia'],
    answer: 0,
    explanation: 'Metaplasia is the reversible conversion of one mature cell type into another, usually as an adaptation to chronic irritation. Dysplasia is disordered, abnormal cell growth that may precede cancer.',
    term: 'Metaplasia', definition: 'The reversible replacement of one mature cell type with another in response to stress or irritation.',
  },
  {
    id: 'c2-q13', chapter: 2, type: 'mc',
    question: 'Abnormal changes in the size, shape, and organization of cells\u2014often considered a precancerous change\u2014is termed:',
    options: ['Metaplasia', 'Hyperplasia', 'Dysplasia', 'Hypertrophy'],
    answer: 2,
    explanation: 'Dysplasia is disordered, atypical cell growth (abnormal size/shape/organization). It is often precancerous, as seen in abnormal cervical Pap results. Metaplasia is an orderly, reversible cell-type swap.',
    term: 'Dysplasia', definition: 'Abnormal changes in the size, shape, and organization of cells; often a precancerous change.',
  },
  {
    id: 'c2-q14', chapter: 2, type: 'mc',
    question: 'Programmed, orderly cell death that is a normal physiologic process is called:',
    options: ['Necrosis', 'Apoptosis', 'Atrophy', 'Autolysis'],
    answer: 1,
    explanation: 'Apoptosis is programmed, controlled cell death — a normal, tidy process that does not trigger inflammation. Necrosis is uncontrolled, pathologic cell death from injury that DOES cause inflammation.',
    term: 'Apoptosis', definition: 'Programmed, orderly cell death that is a normal physiologic process and does not cause inflammation.',
  },
  {
    id: 'c2-q15', chapter: 2, type: 'mc',
    question: 'Which best describes necrosis?',
    options: [
      'Programmed cell death with no inflammation',
      'Uncontrolled, pathologic cell death due to injury that provokes inflammation',
      'An increase in cell number',
      'The normal shrinking of cells with age',
    ],
    answer: 1,
    explanation: 'Necrosis is unregulated cell death caused by injury (ischemia, toxins, trauma) and it triggers an inflammatory response. Apoptosis, by contrast, is programmed and does not cause inflammation.',
    term: 'Necrosis', definition: 'Uncontrolled, pathologic cell death caused by injury, which provokes inflammation.',
  },
  {
    id: 'c2-q16', chapter: 2, type: 'mc',
    question: 'A patient sustains a burn from touching a hot stove. This is an example of which cause of cellular injury?',
    options: ['Chemical injury', 'Thermal injury', 'Mechanical injury', 'Ischemic injury'],
    answer: 1,
    explanation: 'Thermal injury results from extremes of temperature (heat or cold), such as a burn. Chemical injury comes from toxins/acids, mechanical from physical force/trauma.',
    term: 'Thermal injury', definition: 'Cellular injury caused by extremes of temperature, such as burns or frostbite.',
  },
  {
    id: 'c2-q17', chapter: 2, type: 'mc',
    question: 'Ingestion of a caustic household cleaner that damages the esophageal lining is an example of:',
    options: ['Thermal injury', 'Mechanical injury', 'Chemical injury', 'Physical injury'],
    answer: 2,
    explanation: 'Chemical injury results from toxic substances such as acids, bases, drugs, or poisons. Mechanical injury is from physical force; thermal is from temperature extremes.',
    term: 'Chemical injury', definition: 'Cellular damage caused by toxic substances such as acids, bases, drugs, or poisons.',
  },
  {
    id: 'c2-q18', chapter: 2, type: 'mc',
    question: 'Cerebral atrophy is characterized by:',
    options: [
      'Enlargement of brain neurons',
      'A progressive reduction in the size of neurons in the cerebrum',
      'An increase in the number of brain cells',
      'Inflammation of the meninges',
    ],
    answer: 1,
    explanation: 'Cerebral atrophy is a progressive reduction in the SIZE of neurons in the cerebrum, shrinking brain tissue. It can be focal (localized) or global (whole brain).',
    term: 'Cerebral atrophy', definition: 'A progressive reduction in the size of neurons in the cerebrum, shrinking brain tissue.',
  },
  {
    id: 'c2-q19', chapter: 2, type: 'mc',
    question: 'Cerebral atrophy affecting the entire brain rather than one region is described as:',
    options: ['Focal', 'Global', 'Local', 'Systemic'],
    answer: 1,
    explanation: 'Global cerebral atrophy affects the entire brain; focal atrophy is localized to a particular region. \u201cGlobal\u201d = whole; \u201cfocal\u201d = a specific focus/spot.',
  },
  {
    id: 'c2-q20', chapter: 2, type: 'mc',
    question: 'Cardiac hypertrophy most commonly develops as a response to:',
    options: [
      'Decreased cardiac workload',
      'Excessive cardiac workload and increased functional demand',
      'A viral infection of the heart',
      'A decrease in blood pressure',
    ],
    answer: 1,
    explanation: 'Cardiac hypertrophy (increased cardiac muscle mass) develops from excessive workload/increased demand — for example, chronic hypertension forcing the heart to pump against high pressure. It can also be an inherited trait.',
    term: 'Cardiac hypertrophy', definition: 'An increase in cardiac muscle mass, often from excessive workload or increased functional demand.',
  },
  {
    id: 'c2-q21', chapter: 2, type: 'mc',
    question: 'Which set of clinical manifestations is most consistent with cardiac hypertrophy?',
    options: [
      'Fever, rash, and joint pain',
      'Shortness of breath, chest pain, and syncope',
      'Diarrhea and vomiting',
      'Numbness and tingling in the feet',
    ],
    answer: 1,
    explanation: 'Cardiac hypertrophy impairs cardiac function and can cause shortness of breath, chest pain, syncope (fainting), and reduced output. Fever/rash/joint pain point to inflammatory or infectious processes.',
  },
  {
    id: 'c2-q22', chapter: 2, type: 'mc',
    question: 'Which treatment approach for cardiac hypertrophy aims to reduce the workload of the heart?',
    options: [
      'Increasing physical exertion',
      'Drugs that relax the ventricles and decrease the pressure the heart pumps against',
      'Withholding all medications',
      'Increasing dietary sodium',
    ],
    answer: 1,
    explanation: 'Treatment includes medications that relax the ventricles and lower the pressure (afterload) the heart must pump against, reducing its workload. Activity restriction is also used; increasing exertion or sodium would worsen it.',
  },
  {
    id: 'c2-q23', chapter: 2, type: 'tf',
    question: 'True or False: Apoptosis triggers an inflammatory response, whereas necrosis does not.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. It is the reverse. Necrosis (injury-related, uncontrolled death) triggers inflammation; apoptosis (programmed death) is orderly and does NOT cause inflammation.',
  },
  {
    id: 'c2-q24', chapter: 2, type: 'tf',
    question: 'True or False: Metaplasia is generally a reversible change, while dysplasia involves abnormal, potentially precancerous cell growth.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Metaplasia is a reversible swap of one mature cell type for another; dysplasia is disordered, atypical growth that can be precancerous.',
  },
  {
    id: 'c2-q25', chapter: 2, type: 'tf',
    question: 'True or False: Active transport moves substances down their concentration gradient and requires no energy.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Active transport moves substances AGAINST the gradient and requires ATP. Moving DOWN the gradient without energy describes diffusion or facilitated transport.',
  },
  {
    id: 'c2-q26', chapter: 2, type: 'mc',
    question: 'Acromegaly, in which bones and tissues enlarge due to excess growth hormone, is an example of which cellular adaptation?',
    options: ['Atrophy', 'Metaplasia', 'Hyperplasia/hypertrophy of tissues', 'Apoptosis'],
    answer: 2,
    explanation: 'Acromegaly reflects excessive tissue growth (enlargement) driven by growth hormone — an example of hyperplasia/hypertrophy of tissues. It is not a shrinkage (atrophy) or cell-type change (metaplasia).',
  },
  {
    id: 'c2-q27', chapter: 2, type: 'mc',
    question: 'Which organelle is primarily responsible for digesting cellular waste and worn-out organelles?',
    options: ['Lysosome', 'Ribosome', 'Golgi apparatus', 'Endoplasmic reticulum'],
    answer: 0,
    explanation: 'Lysosomes contain digestive enzymes that break down waste, debris, and worn organelles. Ribosomes build proteins; the Golgi packages/ships them; the ER synthesizes proteins and lipids.',
    term: 'Lysosome', definition: 'An organelle containing digestive enzymes that break down cellular waste and worn-out organelles.',
  },
  {
    id: 'c2-q28', chapter: 2, type: 'mc',
    question: 'Cervical metaplasia and dysplasia are commonly detected by which screening test?',
    options: ['Complete blood count', 'Pap smear', 'Chest X-ray', 'Urinalysis'],
    answer: 1,
    explanation: 'A Pap smear screens for cervical metaplasia and dysplasia (abnormal cervical cells), enabling early detection before progression to cancer — a classic example of secondary prevention.',
  },
  {
    id: 'c2-q29', chapter: 2, type: 'mc',
    question: 'A patient on prolonged bed rest develops shrinking, weakened leg muscles. This is best described as which type of atrophy?',
    options: ['Denervation atrophy', 'Disuse atrophy', 'Ischemic atrophy', 'Hypertrophic atrophy'],
    answer: 1,
    explanation: 'Disuse atrophy results from lack of use (immobility, bed rest), causing muscle cells to shrink. Denervation atrophy follows loss of nerve supply; \u201chypertrophic atrophy\u201d is not a real term.',
  },
  {
    id: 'c2-q30', chapter: 2, type: 'mc',
    question: 'Which statement about cellular differentiation and proliferation is correct?',
    options: [
      'Proliferation changes a cell\u2019s function; differentiation increases cell number',
      'Proliferation increases cell number; differentiation gives cells specialized properties',
      'Both terms mean the same thing',
      'Neither is under genetic control',
    ],
    answer: 1,
    explanation: 'Proliferation = increase in cell NUMBER; differentiation = development of specialized cell properties. Both are under genetic control.',
  },

  // ============ CHAPTER 3: Inflammation & Tissue Repair ============
  {
    id: 'c3-q1', chapter: 3, type: 'mc',
    question: 'The skin and mucous membranes that physically block pathogens from entering the body represent which line of defense?',
    options: ['First line of defense', 'Second line of defense', 'Third line of defense', 'Adaptive immunity'],
    answer: 0,
    explanation: 'The first line of defense is physical/chemical barriers (skin, mucous membranes) that keep pathogens out. Inflammation is the second line; the specific immune response is the third.',
    term: 'First line of defense', definition: 'Physical and chemical barriers such as skin and mucous membranes that keep pathogens out.',
  },
  {
    id: 'c3-q2', chapter: 3, type: 'mc',
    question: 'What is the primary trigger for acute inflammation?',
    options: ['Antibody production', 'Tissue injury', 'Vaccination', 'Cellular differentiation'],
    answer: 1,
    explanation: 'Acute inflammation is triggered by tissue injury. Its goals are to increase blood flow to the site, bring healing cells to the area, and prepare for tissue repair.',
    term: 'Acute inflammation', definition: 'The immediate, short-term inflammatory response triggered by tissue injury.',
  },
  {
    id: 'c3-q3', chapter: 3, type: 'mc',
    question: 'Which of the following is NOT a goal of the acute inflammatory response?',
    options: [
      'Increase blood flow to the injured site',
      'Increase healing cells at the site',
      'Prepare the tissue for repair',
      'Permanently destroy healthy tissue',
    ],
    answer: 3,
    explanation: 'The goals of inflammation are to increase blood flow, bring healing cells, and prep for repair. Destroying healthy tissue is not a goal — in fact, proteinase inhibitors work to protect healthy tissue.',
  },
  {
    id: 'c3-q4', chapter: 3, type: 'mc',
    question: 'During the vascular response of inflammation, chemical mediators cause vasodilation and increased capillary permeability in order to:',
    options: [
      'Decrease blood flow to the area',
      'Move more blood and cells to the injured area',
      'Prevent white blood cells from arriving',
      'Cool the tissue down',
    ],
    answer: 1,
    explanation: 'Vasodilation widens vessels and increased permeability lets fluid/cells leak into tissue — both increase blood flow and deliver more healing cells to the injury. This causes the redness, heat, and swelling of inflammation.',
    term: 'Vascular response', definition: 'Vasodilation and increased capillary permeability that bring more blood and cells to an injured site.',
  },
  {
    id: 'c3-q5', chapter: 3, type: 'mc',
    question: 'Which cells are considered the “first responders” of inflammation, releasing histamine when they break apart?',
    options: ['Platelets', 'Mast cells', 'Red blood cells', 'Fibroblasts'],
    answer: 1,
    explanation: 'Mast cells are the first responders; they degranulate and release histamine, leukotrienes, and prostaglandins, which drive vasodilation and increased permeability.',
    term: 'Mast cells', definition: 'First-responder inflammatory cells that release histamine, leukotrienes, and prostaglandins.',
  },
  {
    id: 'c3-q6', chapter: 3, type: 'mc',
    question: 'Histamine, released early in inflammation, primarily causes:',
    options: [
      'Vasoconstriction and decreased permeability',
      'Vasodilation and increased capillary permeability',
      'Clot dissolution',
      'Antibody production',
    ],
    answer: 1,
    explanation: 'Histamine causes vasodilation and increases capillary permeability, producing the redness, heat, and swelling of inflammation. This is why antihistamines reduce these symptoms in allergic reactions.',
    term: 'Histamine', definition: 'An inflammatory mediator released by mast cells that causes vasodilation and increased capillary permeability.',
  },
  {
    id: 'c3-q7', chapter: 3, type: 'mc',
    question: 'Cytokines are best described as:',
    options: [
      'Structural proteins that rebuild tissue',
      'Cell proteins from WBCs that help regulate inflammation',
      'Enzymes that degrade dead tissue',
      'Antibodies produced by plasma cells',
    ],
    answer: 1,
    explanation: 'Cytokines are signaling proteins released by white blood cells that regulate and coordinate the inflammatory response. Matrix proteins rebuild tissue and proteinases degrade dead tissue.',
    term: 'Cytokines', definition: 'Cell-signaling proteins from white blood cells that help regulate inflammation and immune responses.',
  },
  {
    id: 'c3-q8', chapter: 3, type: 'mc',
    question: 'The movement of leukocytes toward the site of injury, directed by chemical signals, is called:',
    options: ['Chemotaxis', 'Diapedesis', 'Opsonization', 'Phagocytosis'],
    answer: 0,
    explanation: 'Chemotaxis is the directed movement of cells (leukocytes) toward the injury in response to chemical mediators. Phagocytosis is the engulfing/eating of pathogens once cells arrive.',
    term: 'Chemotaxis', definition: 'The directed movement of leukocytes toward the site of injury in response to chemical signals.',
  },
  {
    id: 'c3-q9', chapter: 3, type: 'mc',
    question: 'Which of the following are the classic LOCAL manifestations of inflammation?',
    options: [
      'Fever, fatigue, and elevated WBC count',
      'Redness, heat, swelling, pain, and loss of function',
      'Nausea, vomiting, and diarrhea',
      'Weight loss and night sweats',
    ],
    answer: 1,
    explanation: 'The five cardinal local signs are redness (rubor), heat (calor), swelling (tumor), pain (dolor), and loss of function. Fever and leukocytosis are SYSTEMIC manifestations.',
    term: 'Local manifestations of inflammation', definition: 'Redness, heat, swelling, pain, and loss of function at the injured site.',
  },
  {
    id: 'c3-q10', chapter: 3, type: 'mc',
    question: 'Redness of the skin caused by increased blood flow during inflammation is termed:',
    options: ['Erythema', 'Pyrexia', 'Leukocytosis', 'Lymphadenitis'],
    answer: 0,
    explanation: 'Erythema is redness from increased blood flow (vasodilation). Pyrexia is fever, leukocytosis is elevated WBCs, and lymphadenitis is inflamed lymph nodes.',
    term: 'Erythema', definition: 'Redness of the skin caused by increased blood flow during inflammation.',
  },
  {
    id: 'c3-q11', chapter: 3, type: 'mc',
    question: 'Pyrexia is the medical term for:',
    options: ['Redness', 'Fever', 'Swelling', 'Elevated white blood cell count'],
    answer: 1,
    explanation: 'Pyrexia means fever — a systemic manifestation of inflammation. Erythema is redness, edema is swelling, and leukocytosis is elevated WBCs.',
    term: 'Pyrexia', definition: 'Fever; an elevated body temperature and systemic sign of inflammation.',
  },
  {
    id: 'c3-q12', chapter: 3, type: 'mc',
    question: 'An elevated white blood cell count in response to inflammation is called:',
    options: ['Leukopenia', 'Leukocytosis', 'Lymphadenitis', 'Anemia'],
    answer: 1,
    explanation: 'Leukocytosis is an increased WBC count, a common systemic sign of inflammation/infection. Leukopenia is a decreased WBC count.',
    term: 'Leukocytosis', definition: 'An elevated white blood cell count, often seen in inflammation and infection.',
  },
  {
    id: 'c3-q13', chapter: 3, type: 'mc',
    question: 'A patient sprains an ankle. Which standard first-line treatment is summarized by the acronym RICE?',
    options: [
      'Run, Ice, Compress, Exercise',
      'Rest, Ice, Compression, Elevation',
      'Rest, Isolate, Cool, Elevate',
      'Rinse, Ice, Compress, Evaluate',
    ],
    answer: 1,
    explanation: 'RICE = Rest, Ice, Compression, Elevation — the standard early treatment to reduce blood flow, swelling, and pain in an acute injury.',
    term: 'RICE', definition: 'Rest, Ice, Compression, Elevation — first-line treatment to reduce inflammation and swelling.',
  },
  {
    id: 'c3-q14', chapter: 3, type: 'mc',
    question: 'NSAIDs such as aspirin and ibuprofen reduce inflammation primarily by:',
    options: [
      'Increasing histamine release',
      'Blocking the action of chemical mediators (e.g., prostaglandins)',
      'Stimulating vasodilation',
      'Promoting fever',
    ],
    answer: 1,
    explanation: 'NSAIDs block the production/action of chemical mediators like prostaglandins, which reduces pain, swelling, and fever. Goals of anti-inflammatory treatment include reducing blood flow, swelling, and pain.',
    term: 'NSAIDs', definition: 'Nonsteroidal anti-inflammatory drugs that reduce inflammation by blocking prostaglandin production.',
  },
  {
    id: 'c3-q15', chapter: 3, type: 'mc',
    question: 'Which nutrients are especially important for promoting wound healing?',
    options: [
      'Simple sugars and saturated fats only',
      'Proteins and vitamins A and C',
      'Sodium and potassium only',
      'Caffeine and alcohol',
    ],
    answer: 1,
    explanation: 'Adequate protein plus vitamins A and C (along with water, fats, and minerals) support wound healing. Protein rebuilds tissue; vitamin C is needed for collagen synthesis; vitamin A supports epithelial repair.',
  },
  {
    id: 'c3-q16', chapter: 3, type: 'mc',
    question: 'The separation or bursting open of a surgical wound along its suture line is called:',
    options: ['Dehiscence', 'Adhesion', 'Keloid', 'Ulceration'],
    answer: 0,
    explanation: 'Dehiscence is the reopening/separation of a wound along the incision line. A keloid is overgrown scar tissue; adhesions are internal fibrous bands; ulceration is a tissue defect/open sore.',
    term: 'Dehiscence', definition: 'The separation or rupture of a surgical wound along its suture line.',
  },
  {
    id: 'c3-q17', chapter: 3, type: 'mc',
    question: 'An overgrowth of collagen and scar tissue that extends beyond the original wound boundaries is called a:',
    options: ['Adhesion', 'Keloid', 'Granuloma', 'Fissure'],
    answer: 1,
    explanation: 'A keloid is excessive scar tissue growing beyond the original wound margins. Adhesions are fibrous bands connecting internal tissues; granulomas encase harmful substances in chronic inflammation.',
    term: 'Keloid', definition: 'An overgrowth of scar tissue that extends beyond the boundaries of the original wound.',
  },
  {
    id: 'c3-q18', chapter: 3, type: 'mc',
    question: 'Chronic inflammation is best defined as inflammation that:',
    options: [
      'Resolves within 24 hours',
      'Is recurrent or persistent, lasting several weeks or longer',
      'Never involves white blood cells',
      'Only occurs after surgery',
    ],
    answer: 1,
    explanation: 'Chronic inflammation is recurrent or persistent, lasting weeks or longer. It more prominently involves monocytes, macrophages, and lymphocytes, and often leads to granuloma formation and scarring.',
    term: 'Chronic inflammation', definition: 'Recurrent or persistent inflammation lasting several weeks or longer, involving macrophages and lymphocytes.',
  },
  {
    id: 'c3-q19', chapter: 3, type: 'mc',
    question: 'A granuloma is best described as a:',
    options: [
      'Type of white blood cell',
      'Nodular inflammatory lesion that encases a harmful substance',
      'Clotting factor',
      'Enzyme that degrades tissue',
    ],
    answer: 1,
    explanation: 'A granuloma is a nodular inflammatory lesion that walls off/encases a harmful substance the body cannot eliminate (as in tuberculosis). It is a hallmark of chronic inflammation.',
    term: 'Granuloma', definition: 'A nodular inflammatory lesion that encases a harmful substance the body cannot eliminate.',
  },
  {
    id: 'c3-q20', chapter: 3, type: 'mc',
    question: 'Which cells are more prominently involved in chronic inflammation than in acute inflammation?',
    options: [
      'Monocytes, macrophages, and lymphocytes',
      'Red blood cells and platelets',
      'Mast cells only',
      'Epithelial cells only',
    ],
    answer: 0,
    explanation: 'Chronic inflammation prominently involves monocytes, macrophages, and lymphocytes. Acute inflammation relies more on neutrophils and mast cells as first responders.',
  },
  {
    id: 'c3-q21', chapter: 3, type: 'mc',
    question: 'A superficial partial-thickness burn typically presents with:',
    options: [
      'Charred, painless, leathery skin',
      'Heat, swelling, pain, and redness',
      'No visible change to the skin',
      'Only bone involvement',
    ],
    answer: 1,
    explanation: 'Superficial partial-thickness burns show heat, swelling, pain, redness, and loss of function. Painless, leathery eschar suggests a full-thickness burn (nerve endings destroyed).',
  },
  {
    id: 'c3-q22', chapter: 3, type: 'mc',
    question: 'A full-thickness burn is characterized by:',
    options: [
      'Redness and blistering that are extremely painful',
      'Redness, eschar, edema, and exudate, often with reduced pain sensation',
      'Only mild sunburn-like redness',
      'Immediate complete healing',
    ],
    answer: 1,
    explanation: 'Full-thickness burns show redness, eschar (dead leathery tissue), edema, and exudate. Because nerve endings are destroyed, the deepest areas may be less painful than partial-thickness burns.',
  },
  {
    id: 'c3-q23', chapter: 3, type: 'mc',
    question: 'The “Rule of 9’s” is used in burn assessment to estimate:',
    options: [
      'The depth of the burn',
      'The total body surface area affected',
      'The number of skin grafts needed',
      'The patient’s age',
    ],
    answer: 1,
    explanation: 'The Rule of 9’s estimates the total body surface area (TBSA) burned by dividing the body into regions of ~9% (or multiples). This guides fluid resuscitation and treatment decisions.',
    term: 'Rule of 9’s', definition: 'A method of estimating the total body surface area affected by a burn.',
  },
  {
    id: 'c3-q24', chapter: 3, type: 'mc',
    question: 'Rheumatoid arthritis (RA) is best described as:',
    options: [
      'A degenerative wear-and-tear joint disease',
      'A chronic autoimmune inflammation of the synovial membranes',
      'A bacterial infection of the bone',
      'A vitamin deficiency',
    ],
    answer: 1,
    explanation: 'RA is a chronic AUTOIMMUNE disease causing inflammation of the synovial membranes and synovial hyperplasia. Osteoarthritis is the degenerative wear-and-tear type — don’t confuse the two.',
    term: 'Rheumatoid arthritis', definition: 'A chronic autoimmune disease causing inflammation of the synovial membranes of joints.',
  },
  {
    id: 'c3-q25', chapter: 3, type: 'mc',
    question: 'A hallmark clinical feature that distinguishes rheumatoid arthritis is:',
    options: [
      'Involvement of a single random joint',
      'Symmetrical joint involvement with pain, stiffness, and swelling',
      'Pain only after age 80',
      'Complete absence of inflammation',
    ],
    answer: 1,
    explanation: 'RA classically affects joints SYMMETRICALLY (same joints on both sides) with pain, stiffness, redness, heat, swelling, and decreased mobility. It follows a remission/exacerbation pattern.',
  },
  {
    id: 'c3-q26', chapter: 3, type: 'mc',
    question: 'In rheumatoid arthritis, the abnormal growth of inflamed synovial tissue that erodes cartilage is called:',
    options: ['Pannus', 'Ankylosis', 'Eschar', 'Exudate'],
    answer: 0,
    explanation: 'Pannus is the inflamed, proliferating synovial tissue in RA that erodes cartilage and bone. Ankylosis is the eventual joint fusion/stiffening that can result.',
    term: 'Pannus', definition: 'Abnormal inflamed synovial tissue in rheumatoid arthritis that erodes cartilage and bone.',
  },
  {
    id: 'c3-q27', chapter: 3, type: 'mc',
    question: 'Which laboratory findings support a diagnosis of rheumatoid arthritis?',
    options: [
      'Low blood glucose and high sodium',
      'Elevated ESR, elevated CRP, and positive rheumatoid factor',
      'Low white blood cell count only',
      'High urine bilirubin',
    ],
    answer: 1,
    explanation: 'RA has no single definitive test, but elevated ESR and CRP (inflammation markers), positive rheumatoid factor, and ANA increase likelihood. Joint fluid analysis and X-rays also support the diagnosis.',
  },
  {
    id: 'c3-q28', chapter: 3, type: 'tf',
    question: 'True or False: Fever and leukocytosis are systemic manifestations of inflammation, while redness and swelling are local manifestations.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Fever (pyrexia) and elevated WBCs (leukocytosis) are systemic (whole-body) signs; redness, heat, swelling, pain, and loss of function are local signs at the injury site.',
  },
  {
    id: 'c3-q29', chapter: 3, type: 'tf',
    question: 'True or False: The inflammatory response is always harmful and should be completely eliminated whenever possible.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Inflammation is a necessary, protective response that promotes healing. Treatment aims to moderate an excessive response — not eliminate it entirely.',
  },
  {
    id: 'c3-q30', chapter: 3, type: 'tf',
    question: 'True or False: In rheumatoid arthritis, joint involvement is typically symmetrical.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Symmetrical joint involvement (same joints on both sides of the body) is a hallmark of RA, helping distinguish it from osteoarthritis.',
  },

  // ============ CHAPTER 4: Altered Immunity ============
  {
    id: 'c4-q1', chapter: 4, type: 'mc',
    question: 'The immune response is considered which line of defense?',
    options: ['First line', 'Second line', 'Third line', 'It is not a line of defense'],
    answer: 2,
    explanation: 'The specific immune response is the third line of defense. The first line is barriers (skin/mucous membranes); the second is inflammation.',
    term: 'Third line of defense', definition: 'The specific immune response that recognizes and neutralizes foreign substances.',
  },
  {
    id: 'c4-q2', chapter: 4, type: 'mc',
    question: 'A substance that the immune system recognizes as foreign and mounts a response against is called a(n):',
    options: ['Antibody', 'Antigen', 'Cytokine', 'Histamine'],
    answer: 1,
    explanation: 'An antigen is a foreign substance that triggers an immune response. An antibody (immunoglobulin) is what B cells produce IN RESPONSE to an antigen.',
    term: 'Antigen', definition: 'A foreign substance recognized by the immune system that triggers an immune response.',
  },
  {
    id: 'c4-q3', chapter: 4, type: 'mc',
    question: 'The ability of the immune system to remember a prior exposure and respond faster on re-exposure is called:',
    options: ['Specificity', 'Diversity', 'Immunologic memory', 'Self/non-self recognition'],
    answer: 2,
    explanation: 'Immunologic memory allows a faster, stronger response upon re-exposure to the same antigen — the basis for how vaccines protect us. This is the secondary immune response.',
    term: 'Immunologic memory', definition: 'The immune system’s ability to remember prior antigens and respond faster upon re-exposure.',
  },
  {
    id: 'c4-q4', chapter: 4, type: 'mc',
    question: 'Where do immune cells (leukocytes) originate?',
    options: ['The liver', 'The bone marrow', 'The spleen', 'The thymus only'],
    answer: 1,
    explanation: 'All immune cells originate in the bone marrow from lymphoid and myeloid progenitor cells. T lymphocytes later mature in the thymus, but their origin is the bone marrow.',
  },
  {
    id: 'c4-q5', chapter: 4, type: 'mc',
    question: 'Which type of T lymphocyte directly destroys antigen-carrying cells?',
    options: ['Helper T cells', 'Cytotoxic T cells', 'Suppressor T cells', 'Plasma cells'],
    answer: 1,
    explanation: 'Cytotoxic T lymphocytes (CD8) directly kill infected/abnormal cells. Helper T cells (CD4) enhance responses, suppressor T cells inhibit them, and plasma cells make antibodies.',
    term: 'Cytotoxic T cells', definition: 'T lymphocytes (CD8) that directly destroy cells carrying foreign antigens.',
  },
  {
    id: 'c4-q6', chapter: 4, type: 'mc',
    question: 'Helper T lymphocytes (CD4) function to:',
    options: [
      'Directly kill infected cells',
      'Enhance both humoral and cell-mediated immune responses',
      'Produce antibodies directly',
      'Suppress all immune activity',
    ],
    answer: 1,
    explanation: 'Helper T cells (CD4) coordinate and enhance both humoral and cell-mediated responses — they are the “conductors” of the immune system. HIV attacks these cells, which is why it is so devastating.',
    term: 'Helper T cells', definition: 'T lymphocytes (CD4) that enhance both humoral and cell-mediated immune responses.',
  },
  {
    id: 'c4-q7', chapter: 4, type: 'mc',
    question: 'B lymphocytes, once activated by an antigen, differentiate into plasma cells that produce:',
    options: ['Histamine', 'Antibodies (immunoglobulins)', 'Cytotoxic enzymes', 'Red blood cells'],
    answer: 1,
    explanation: 'Activated B cells become plasma cells that secrete antibodies (immunoglobulins) targeting the specific antigen. This is the basis of humoral immunity.',
    term: 'B lymphocytes', definition: 'Immune cells that differentiate into plasma cells and produce antibodies against antigens.',
  },
  {
    id: 'c4-q8', chapter: 4, type: 'mc',
    question: 'Which granulocyte is the primary responder to bacterial infections?',
    options: ['Eosinophils', 'Basophils', 'Neutrophils', 'Lymphocytes'],
    answer: 2,
    explanation: 'Neutrophils are the primary phagocytes responding to bacterial infection. Eosinophils target parasites, and basophils work with mast cells in allergic responses.',
    term: 'Neutrophils', definition: 'Granulocytes that are the primary phagocytic responders to bacterial infection.',
  },
  {
    id: 'c4-q9', chapter: 4, type: 'mc',
    question: 'Elevated eosinophils most commonly indicate:',
    options: ['A bacterial infection', 'A parasitic infection or allergic reaction', 'A viral infection', 'Normal findings only'],
    answer: 1,
    explanation: 'Eosinophils rise in parasitic infections and allergic reactions. Neutrophils rise with bacterial infections; lymphocytes often rise with viral infections.',
    term: 'Eosinophils', definition: 'Granulocytes that respond primarily to parasites and allergic reactions.',
  },
  {
    id: 'c4-q10', chapter: 4, type: 'mc',
    question: 'Innate immunity is best characterized as:',
    options: [
      'A slow, highly specific response with memory',
      'A rapid, nonspecific first response involving macrophages, neutrophils, and dendritic cells',
      'Antibody production by B cells only',
      'A response that only develops after vaccination',
    ],
    answer: 1,
    explanation: 'Innate immunity is rapid and NONSPECIFIC (macrophages, neutrophils, dendritic cells, inflammation). Adaptive immunity is slower, highly specific, and has memory.',
    term: 'Innate immunity', definition: 'The rapid, nonspecific first-line immune response involving phagocytes and inflammation.',
  },
  {
    id: 'c4-q11', chapter: 4, type: 'mc',
    question: 'Adaptive immunity differs from innate immunity in that it is:',
    options: [
      'Immediate and nonspecific',
      'Targeted to a specific antigen and involves T and B lymphocytes',
      'Never able to form memory',
      'Only present at birth',
    ],
    answer: 1,
    explanation: 'Adaptive immunity is specific (targets a particular antigen), involves T and B lymphocytes, and forms memory. Innate immunity is the immediate, nonspecific response.',
    term: 'Adaptive immunity', definition: 'A specific immune response targeting a particular antigen, involving T and B lymphocytes and immunologic memory.',
  },
  {
    id: 'c4-q12', chapter: 4, type: 'mc',
    question: 'A person recovers from chickenpox and develops lifelong protection through their own antibody production. This is an example of:',
    options: ['Natural active immunity', 'Natural passive immunity', 'Artificial active immunity', 'Artificial passive immunity'],
    answer: 0,
    explanation: 'Natural ACTIVE immunity comes from actually having the disease and making your own antibodies. It is “natural” (not from a shot) and “active” (your body did the work).',
    term: 'Natural active immunity', definition: 'Immunity gained by having a disease and producing one’s own antibodies.',
  },
  {
    id: 'c4-q13', chapter: 4, type: 'mc',
    question: 'Receiving a vaccine that prompts your body to make antibodies is an example of:',
    options: ['Natural active immunity', 'Artificial active immunity', 'Natural passive immunity', 'Artificial passive immunity'],
    answer: 1,
    explanation: 'Artificial ACTIVE immunity comes from a vaccine (artificial) that stimulates your body to make its own antibodies (active). Contrast with passive immunity, where antibodies are given to you.',
    term: 'Artificial active immunity', definition: 'Immunity produced when a vaccine stimulates the body to make its own antibodies.',
  },
  {
    id: 'c4-q14', chapter: 4, type: 'mc',
    question: 'A newborn receives antibodies through breast milk. This is an example of:',
    options: ['Natural active immunity', 'Artificial active immunity', 'Natural passive immunity', 'Artificial passive immunity'],
    answer: 2,
    explanation: 'Natural PASSIVE immunity is receiving pre-made antibodies naturally — across the placenta or through breast milk. It is “passive” because the recipient did not make the antibodies, and “natural” because no medical injection was involved.',
    term: 'Natural passive immunity', definition: 'Immunity from receiving pre-made antibodies naturally, such as through the placenta or breast milk.',
  },
  {
    id: 'c4-q15', chapter: 4, type: 'mc',
    question: 'A patient exposed to rabies receives an injection of pre-formed antibodies. This is an example of:',
    options: ['Natural active immunity', 'Artificial active immunity', 'Natural passive immunity', 'Artificial passive immunity'],
    answer: 3,
    explanation: 'Artificial PASSIVE immunity is receiving pre-formed antibodies via injection (antibody/immunoglobulin shots). It is “passive” (antibodies given, not made) and “artificial” (medical injection).',
    term: 'Artificial passive immunity', definition: 'Immunity from an injection of pre-formed antibodies, such as immunoglobulin therapy.',
  },
  {
    id: 'c4-q16', chapter: 4, type: 'mc',
    question: 'Humoral immunity is mediated primarily by:',
    options: [
      'Cytotoxic T cells directly killing cells',
      'Antibodies secreted by plasma cells (from B lymphocytes)',
      'Neutrophil phagocytosis',
      'The complement system alone',
    ],
    answer: 1,
    explanation: 'Humoral immunity is antibody-mediated: B lymphocytes become plasma cells that secrete antibodies. Cell-mediated immunity relies on T cells directly attacking infected cells.',
    term: 'Humoral immunity', definition: 'Antibody-mediated immunity involving B lymphocytes and plasma cells.',
  },
  {
    id: 'c4-q17', chapter: 4, type: 'mc',
    question: 'Which immunoglobulin is primarily involved in Type I (immediate) hypersensitivity and allergic reactions?',
    options: ['IgA', 'IgG', 'IgM', 'IgE'],
    answer: 3,
    explanation: 'IgE mediates Type I immediate hypersensitivity (allergies, anaphylaxis) by binding mast cells and triggering histamine release. IgG and IgM are involved in Types II and III.',
    term: 'IgE', definition: 'The immunoglobulin responsible for Type I immediate hypersensitivity and allergic reactions.',
  },
  {
    id: 'c4-q18', chapter: 4, type: 'mc',
    question: 'A patient stung by a bee rapidly develops hives, difficulty breathing, and a drop in blood pressure. This is which type of hypersensitivity reaction?',
    options: ['Type I (immediate)', 'Type II (antibody-mediated)', 'Type III (immune complex)', 'Type IV (delayed)'],
    answer: 0,
    explanation: 'This is a Type I (immediate) hypersensitivity reaction — an IgE-mediated response causing rapid, systemic anaphylaxis. It is the fastest-onset hypersensitivity type.',
    term: 'Type I hypersensitivity', definition: 'An immediate, IgE-mediated hypersensitivity reaction, as in allergies and anaphylaxis.',
  },
  {
    id: 'c4-q19', chapter: 4, type: 'mc',
    question: 'A Type IV hypersensitivity reaction differs from the others in that it is:',
    options: [
      'Mediated by IgE and immediate',
      'Delayed and mediated by T lymphocytes rather than antibodies',
      'Caused by immune complexes',
      'Only seen in newborns',
    ],
    answer: 1,
    explanation: 'Type IV is a DELAYED, cell-mediated (T lymphocyte) reaction — not antibody-mediated. Classic examples include the TB skin test reaction and poison ivy contact dermatitis.',
    term: 'Type IV hypersensitivity', definition: 'A delayed, T lymphocyte–mediated hypersensitivity reaction, such as a TB skin test or contact dermatitis.',
  },
  {
    id: 'c4-q20', chapter: 4, type: 'mc',
    question: 'Autoimmunity occurs when:',
    options: [
      'The body fails to distinguish self from non-self and attacks its own tissues',
      'The immune system is completely absent',
      'A transplanted organ is rejected',
      'Antibodies are transferred from mother to child',
    ],
    answer: 0,
    explanation: 'Autoimmunity is a failure to distinguish self from non-self, so the immune system attacks the body’s own tissues (e.g., RA, SLE, type 1 diabetes). Rejection of a transplant is alloimmunity.',
    term: 'Autoimmunity', definition: 'A failure to distinguish self from non-self, causing the immune system to attack the body’s own tissues.',
  },
  {
    id: 'c4-q21', chapter: 4, type: 'mc',
    question: 'Rejection of a transplanted organ, in which the immune system attacks foreign donor tissue, is an example of:',
    options: ['Autoimmunity', 'Alloimmunity', 'Immunodeficiency', 'Passive immunity'],
    answer: 1,
    explanation: 'Alloimmunity is an immune response against tissue from another individual of the same species — such as graft/transplant rejection or graft-versus-host disease. Autoimmunity is attacking one’s OWN tissue.',
    term: 'Alloimmunity', definition: 'An immune response against tissue from another individual, as in transplant rejection.',
  },
  {
    id: 'c4-q22', chapter: 4, type: 'mc',
    question: 'AIDS results from HIV infecting and destroying which cells?',
    options: ['CD8 cytotoxic T cells', 'CD4 helper T lymphocytes', 'B lymphocytes', 'Red blood cells'],
    answer: 1,
    explanation: 'HIV infects and destroys CD4 helper T lymphocytes, crippling coordination of both cell-mediated and humoral immunity. This progressive loss of CD4 cells defines the immunodeficiency of AIDS.',
    term: 'HIV/AIDS', definition: 'A secondary immunodeficiency from HIV infection destroying CD4 helper T lymphocytes.',
  },
  {
    id: 'c4-q23', chapter: 4, type: 'mc',
    question: 'The opportunistic infections seen in AIDS (such as candidiasis, Pneumocystis pneumonia, and Kaposi sarcoma) occur because:',
    options: [
      'The patient has too many white blood cells',
      'The loss of CD4 cells severely weakens cell-mediated immunity',
      'The patient is over-vaccinated',
      'HIV directly causes these cancers via toxins',
    ],
    answer: 1,
    explanation: 'As CD4 helper T cells are destroyed, cell-mediated immunity collapses, allowing opportunistic infections and cancers that a healthy immune system would normally control.',
  },
  {
    id: 'c4-q24', chapter: 4, type: 'mc',
    question: 'The primary treatment to suppress viral load and preserve immune function in HIV is:',
    options: ['Antibiotics', 'Antiretroviral therapy (ART)', 'Antihistamines', 'Corticosteroids'],
    answer: 1,
    explanation: 'Antiretroviral therapy (ART) suppresses HIV viral load, preserves/restores immune function, and reduces morbidity/mortality. Combination drugs are used to reduce drug resistance. PrEP is used for prevention.',
    term: 'Antiretroviral therapy (ART)', definition: 'Combination drug therapy that suppresses HIV viral load and preserves immune function.',
  },
  {
    id: 'c4-q25', chapter: 4, type: 'mc',
    question: 'Anaphylaxis is an exaggerated systemic response caused by which type of hypersensitivity?',
    options: ['Type I (IgE-mediated)', 'Type II', 'Type III', 'Type IV'],
    answer: 0,
    explanation: 'Anaphylaxis is a severe, systemic Type I (IgE-mediated) hypersensitivity reaction. Mast cells and basophils degranulate, releasing mediators that cause airway constriction and vascular collapse.',
  },
  {
    id: 'c4-q26', chapter: 4, type: 'mc',
    question: 'The first-line emergency treatment for a severe anaphylactic reaction is:',
    options: ['Oral antihistamine', 'Epinephrine (EpiPen)', 'A cool compress', 'Aspirin'],
    answer: 1,
    explanation: 'Epinephrine (EpiPen) is the first-line emergency treatment for anaphylaxis — it constricts blood vessels (raising BP) and relaxes bronchial smooth muscle (opening the airway). Antihistamines are adjuncts, not the primary rescue.',
    term: 'Epinephrine', definition: 'The first-line emergency drug for anaphylaxis; it raises blood pressure and opens the airways.',
  },
  {
    id: 'c4-q27', chapter: 4, type: 'mc',
    question: 'In an anaphylactic reaction, the constriction of bronchial smooth muscle leads to which symptom?',
    options: ['Increased urine output', 'Difficulty breathing and wheezing', 'Joint pain', 'Skin thickening'],
    answer: 1,
    explanation: 'Bronchial smooth muscle constriction narrows the airways, causing difficulty breathing, wheezing, and cough. Simultaneously, vascular dilation drops blood pressure — a dangerous combination.',
  },
  {
    id: 'c4-q28', chapter: 4, type: 'tf',
    question: 'True or False: Active immunity involves the body producing its own antibodies, while passive immunity involves receiving antibodies made by another source.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Active immunity = your body makes the antibodies (disease or vaccine). Passive immunity = you receive ready-made antibodies (placenta, breast milk, or injection).',
  },
  {
    id: 'c4-q29', chapter: 4, type: 'tf',
    question: 'True or False: A CD4 count below 200 is one of the criteria used to define AIDS.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. A CD4 count below 200 cells/mm³ (or the presence of an AIDS-defining opportunistic infection) marks the progression from HIV infection to AIDS.',
  },
  {
    id: 'c4-q30', chapter: 4, type: 'tf',
    question: 'True or False: Natural killer (NK) cells are part of the adaptive immune response and require prior exposure to an antigen.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. NK cells are part of the INNATE immune response — they kill abnormal/infected cells without prior sensitization or antigen-specific memory.',
  },

  // ============ CHAPTER 5: Infection ============
  {
    id: 'c5-q1', chapter: 5, type: 'mc',
    question: 'Infection is best defined as:',
    options: [
      'A normal state of homeostasis',
      'Cellular, tissue, and organ destruction resulting from invasion by microorganisms',
      'An allergic reaction to a foreign protein',
      'The shrinking of cells due to disuse',
    ],
    answer: 1,
    explanation: 'Infection is a state of cellular, tissue, and organ destruction resulting from invasion by microorganisms that penetrate the body’s lines of defense.',
    term: 'Infection', definition: 'Cellular, tissue, and organ destruction resulting from invasion by microorganisms.',
  },
  {
    id: 'c5-q2', chapter: 5, type: 'mc',
    question: 'Which of the following is NOT a mechanism by which pathogens cause disease?',
    options: [
      'Direct destruction of host cells',
      'Interference with the host cell’s metabolic function',
      'Exposing host cells to toxins',
      'Strengthening the host’s immune memory',
    ],
    answer: 3,
    explanation: 'Pathogens cause disease by directly destroying host cells, disrupting host metabolism, or releasing toxins. Strengthening immune memory is a beneficial immune outcome, not a mechanism of causing disease.',
  },
  {
    id: 'c5-q3', chapter: 5, type: 'mc',
    question: 'The degree of pathogenicity, or the severity of disease a microbe can cause, is termed:',
    options: ['Infectivity', 'Virulence', 'Antigenicity', 'Toxigenicity'],
    answer: 1,
    explanation: 'Virulence is the degree or severity of disease a pathogen can produce. Infectivity is its ability to invade/establish; toxigenicity is its ability to produce toxins; antigenicity is its ability to trigger an immune response.',
    term: 'Virulence', definition: 'The degree of pathogenicity, or how severe a disease a microbe can cause.',
  },
  {
    id: 'c5-q4', chapter: 5, type: 'mc',
    question: 'A pathogen’s ability to invade and establish itself in a host is called its:',
    options: ['Virulence', 'Infectivity', 'Toxigenicity', 'Antigenic variability'],
    answer: 1,
    explanation: 'Infectivity is the ability to invade and establish infection in a host. Virulence is the severity of disease produced once established.',
    term: 'Infectivity', definition: 'A pathogen’s ability to invade and establish itself in a host.',
  },
  {
    id: 'c5-q5', chapter: 5, type: 'mc',
    question: 'A microorganism that can only survive and replicate inside a host cell (such as a virus) is described as a(n):',
    options: ['Facultative organism', 'Obligate organism', 'Saprophyte', 'Commensal'],
    answer: 1,
    explanation: 'An obligate organism requires a host to survive/replicate (e.g., viruses). A facultative organism can live with or without a host.',
    term: 'Obligate organism', definition: 'A microorganism that can only survive and replicate inside a host cell.',
  },
  {
    id: 'c5-q6', chapter: 5, type: 'mc',
    question: 'Which type of pathogen is treated with antibacterial (antibiotic) drugs?',
    options: ['Viruses', 'Bacteria', 'Fungi', 'Helminths'],
    answer: 1,
    explanation: 'Antibacterials (antibiotics) treat bacterial infections. Antivirals treat viruses, antifungals treat fungi — antibiotics do NOT work on viruses, a key point for patient education.',
  },
  {
    id: 'c5-q7', chapter: 5, type: 'mc',
    question: 'A superinfection is best described as:',
    options: [
      'A single mild infection',
      'A secondary infection that occurs during or after treatment of a primary infection',
      'An infection that never produces symptoms',
      'Immunity gained from a vaccine',
    ],
    answer: 1,
    explanation: 'A superinfection is a new, secondary infection that arises during/after treatment of an initial one — often when antibiotics disrupt normal flora (e.g., a yeast infection after antibiotics). Coinfection is two infections at the same time.',
    term: 'Superinfection', definition: 'A secondary infection occurring during or after treatment of a primary infection.',
  },
  {
    id: 'c5-q8', chapter: 5, type: 'mc',
    question: 'During which phase of acute infection does the pathogen enter the body, before any symptoms or reproduction occur?',
    options: ['Incubation', 'Exposure', 'Prodrome', 'Convalescence'],
    answer: 1,
    explanation: 'Exposure is when the pathogen first enters/contacts the host. Incubation follows (pathogen multiplies, still no symptoms), then prodrome (vague early symptoms), acute illness, and convalescence (recovery).',
    term: 'Exposure', definition: 'The phase of infection when a pathogen first enters or contacts the host.',
  },
  {
    id: 'c5-q9', chapter: 5, type: 'mc',
    question: 'The incubation period of an infection refers to the time:',
    options: [
      'When symptoms are at their worst',
      'Between exposure and the appearance of the first symptoms, while the pathogen multiplies',
      'When the patient is recovering',
      'After all symptoms have resolved',
    ],
    answer: 1,
    explanation: 'Incubation is the interval between exposure and the first symptoms, during which the pathogen multiplies. The patient may be asymptomatic but potentially contagious.',
    term: 'Incubation', definition: 'The period between exposure to a pathogen and the appearance of the first symptoms.',
  },
  {
    id: 'c5-q10', chapter: 5, type: 'mc',
    question: 'The prodrome phase of an infection is characterized by:',
    options: [
      'No symptoms at all',
      'Early, vague, nonspecific symptoms such as fatigue and malaise',
      'Full-blown, specific symptoms of the disease',
      'Complete recovery',
    ],
    answer: 1,
    explanation: 'The prodrome features early, vague, nonspecific symptoms (fatigue, malaise, low-grade fever) before the characteristic signs appear. The acute clinical illness phase brings the full, specific symptoms.',
    term: 'Prodrome', definition: 'The early phase of infection with vague, nonspecific symptoms before characteristic signs appear.',
  },
  {
    id: 'c5-q11', chapter: 5, type: 'mc',
    question: 'The convalescence phase of infection refers to the period when:',
    options: [
      'The pathogen first enters the body',
      'The body recovers and returns toward normal function',
      'Symptoms are most severe',
      'The pathogen is multiplying silently',
    ],
    answer: 1,
    explanation: 'Convalescence is the recovery phase, when symptoms subside and the body heals and returns to normal function. It follows the acute clinical illness phase.',
    term: 'Convalescence', definition: 'The recovery phase of infection when the body heals and returns toward normal function.',
  },
  {
    id: 'c5-q12', chapter: 5, type: 'mc',
    question: 'The presence of viable bacteria in the bloodstream is called:',
    options: ['Septicemia', 'Bacteremia', 'Septic shock', 'Leukopenia'],
    answer: 1,
    explanation: 'Bacteremia is simply the presence of bacteria in the blood. Septicemia is a more serious systemic infection with bacteria actively multiplying and causing illness; septic shock is life-threatening circulatory collapse.',
    term: 'Bacteremia', definition: 'The presence of viable bacteria in the bloodstream.',
  },
  {
    id: 'c5-q13', chapter: 5, type: 'mc',
    question: 'A patient with a severe systemic infection develops widespread vasodilation, hypotension, and poor tissue perfusion. This life-threatening complication is:',
    options: ['Bacteremia', 'Septic shock', 'Prodrome', 'Convalescence'],
    answer: 1,
    explanation: 'Septic shock is a life-threatening complication of infection: systemic vasodilation causes profound hypotension and poor tissue perfusion, which can lead to organ failure and death without rapid treatment.',
    term: 'Septic shock', definition: 'A life-threatening complication of infection with vasodilation, hypotension, and poor tissue perfusion.',
  },
  {
    id: 'c5-q14', chapter: 5, type: 'mc',
    question: 'Which of the following is a SYSTEMIC manifestation of infection?',
    options: ['Localized redness', 'Purulent exudate at a wound', 'Fever and malaise', 'Local heat and pain'],
    answer: 2,
    explanation: 'Systemic manifestations affect the whole body: fever, weakness, fatigue, headache, malaise, anorexia, nausea. Localized redness, heat, pain, and purulent exudate are LOCAL manifestations.',
  },
  {
    id: 'c5-q15', chapter: 5, type: 'mc',
    question: 'Thick, pus-containing drainage from an infected wound is termed:',
    options: ['Serous exudate', 'Purulent exudate', 'Erythema', 'Eschar'],
    answer: 1,
    explanation: 'Purulent exudate is pus — thick drainage containing dead white blood cells, bacteria, and debris, indicating infection. Serous exudate is clear/watery.',
    term: 'Purulent exudate', definition: 'Thick, pus-containing wound drainage indicating infection.',
  },
  {
    id: 'c5-q16', chapter: 5, type: 'mc',
    question: 'A culture and sensitivity test is performed on an infected wound. The “sensitivity” portion identifies:',
    options: [
      'How many white blood cells are present',
      'Which antibiotics will be effective against the specific organism',
      'The patient’s blood type',
      'Whether the patient has an allergy',
    ],
    answer: 1,
    explanation: 'The culture identifies the organism; the sensitivity determines which antibiotics that specific organism is susceptible to — guiding targeted, effective treatment rather than guessing.',
    term: 'Culture and sensitivity', definition: 'A test that identifies the causative organism (culture) and which antibiotics are effective against it (sensitivity).',
  },
  {
    id: 'c5-q17', chapter: 5, type: 'mc',
    question: 'A decreased white blood cell count, which can occur with some overwhelming infections, is called:',
    options: ['Leukocytosis', 'Leukopenia', 'Erythema', 'Bacteremia'],
    answer: 1,
    explanation: 'Leukopenia is a decreased WBC count. Leukocytosis (increased WBCs) is more typical of infection, but overwhelming sepsis or certain viral infections can cause leukopenia.',
    term: 'Leukopenia', definition: 'A decreased white blood cell count.',
  },
  {
    id: 'c5-q18', chapter: 5, type: 'mc',
    question: 'Influenza is primarily transmitted by:',
    options: ['Fecal-oral route', 'Respiratory droplets', 'Contaminated blood transfusion', 'Insect bites'],
    answer: 1,
    explanation: 'Influenza spreads via respiratory droplets, infecting epithelial cells of the airway. This is why handwashing, masks, and covering coughs are key prevention measures.',
    term: 'Influenza', definition: 'A viral infection of the airway epithelium transmitted by respiratory droplets.',
  },
  {
    id: 'c5-q19', chapter: 5, type: 'mc',
    question: 'The gradual change in the genetic composition of the influenza virus during replication, requiring updated yearly vaccines, is related to:',
    options: ['Reassortment/antigenic change', 'Phagocytosis', 'Chemotaxis', 'Apoptosis'],
    answer: 0,
    explanation: 'Influenza undergoes reassortment/antigenic change — its genetic makeup shifts during replication, so immunity from past strains may not protect against new ones. This is why the flu vaccine is updated annually.',
  },
  {
    id: 'c5-q20', chapter: 5, type: 'mc',
    question: 'The single most effective way to prevent the spread of most infections in healthcare settings is:',
    options: ['Antibiotics for everyone', 'Handwashing', 'Bed rest', 'Increasing fluid intake'],
    answer: 1,
    explanation: 'Handwashing is the single most effective infection-control measure. Vaccination is also key, but routine hand hygiene prevents the widest range of transmission.',
  },
  {
    id: 'c5-q21', chapter: 5, type: 'mc',
    question: 'Hepatitis refers to inflammation of the:',
    options: ['Kidneys', 'Liver', 'Lungs', 'Pancreas'],
    answer: 1,
    explanation: 'Hepatitis is inflammation of the liver, which can be caused by viruses, alcohol abuse, or other toxic substances, resulting in varying degrees of hepatic necrosis.',
    term: 'Hepatitis', definition: 'Inflammation of the liver, caused by viruses, alcohol, or toxins.',
  },
  {
    id: 'c5-q22', chapter: 5, type: 'mc',
    question: 'Hepatitis A is most commonly transmitted by the:',
    options: ['Respiratory droplet route', 'Fecal-oral route', 'Insect bite', 'Airborne route'],
    answer: 1,
    explanation: 'Hepatitis A spreads via the fecal-oral route (contaminated food/water, poor hand hygiene). Hepatitis B and C spread through infected blood and body fluids.',
  },
  {
    id: 'c5-q23', chapter: 5, type: 'mc',
    question: 'Which hepatitis viruses are primarily transmitted through infected blood and body fluids?',
    options: ['Hepatitis A and E', 'Hepatitis B and C', 'Hepatitis A only', 'None of them'],
    answer: 1,
    explanation: 'Hepatitis B and C are bloodborne, spread by infected blood/body fluids (needles, transfusions, sexual contact). Hepatitis A and E spread by the fecal-oral route.',
  },
  {
    id: 'c5-q24', chapter: 5, type: 'mc',
    question: 'Acute pyelonephritis is a bacterial infection of the:',
    options: ['Bladder', 'Kidneys', 'Urethra', 'Ureters only'],
    answer: 1,
    explanation: 'Acute pyelonephritis is a bacterial infection of the kidneys, most often caused by E. coli. It is more serious than a lower UTI (cystitis) confined to the bladder.',
    term: 'Acute pyelonephritis', definition: 'A bacterial infection of the kidneys, most often caused by E. coli.',
  },
  {
    id: 'c5-q25', chapter: 5, type: 'mc',
    question: 'Which organism most commonly causes acute pyelonephritis?',
    options: ['Staphylococcus aureus', 'Escherichia coli (E. coli)', 'Candida albicans', 'Influenza virus'],
    answer: 1,
    explanation: 'E. coli, a gram-negative bacterium from the GI tract, is the most common cause of acute pyelonephritis and UTIs — it ascends from the urethra into the urinary tract.',
  },
  {
    id: 'c5-q26', chapter: 5, type: 'mc',
    question: 'A patient presents with fever, costovertebral angle (flank) pain, dysuria, and urinary frequency. These findings are most consistent with:',
    options: ['Influenza', 'Acute pyelonephritis', 'Hepatitis A', 'Anaphylaxis'],
    answer: 1,
    explanation: 'Fever, costovertebral angle (flank) pain, dysuria, and urinary frequency/urgency are classic signs of acute pyelonephritis (kidney infection). Flank pain over the kidney area is a key distinguishing feature.',
  },
  {
    id: 'c5-q27', chapter: 5, type: 'mc',
    question: 'A key patient-education point regarding antibiotics is that they:',
    options: [
      'Are effective against viral infections like the common cold',
      'Are effective against bacteria but NOT viruses',
      'Should be stopped as soon as symptoms improve',
      'Never cause resistance',
    ],
    answer: 1,
    explanation: 'Antibiotics treat bacterial infections, not viruses. Patients should complete the full course (stopping early breeds resistance), and overuse contributes to multidrug-resistant organisms.',
  },
  {
    id: 'c5-q28', chapter: 5, type: 'tf',
    question: 'True or False: Antibiotics are an effective treatment for viral infections such as influenza.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Antibiotics only work against bacteria. Viral infections like influenza require antivirals or supportive care — misusing antibiotics fuels antibiotic resistance.',
  },
  {
    id: 'c5-q29', chapter: 5, type: 'tf',
    question: 'True or False: During the incubation period, a person may be asymptomatic but the pathogen is already multiplying in the body.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Incubation is the interval between exposure and first symptoms; the pathogen multiplies during this time even though the person may feel fine and may already be contagious.',
  },
  {
    id: 'c5-q30', chapter: 5, type: 'tf',
    question: 'True or False: Septicemia is a more serious systemic condition than simple bacteremia.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Bacteremia is merely bacteria present in the blood; septicemia is a serious systemic infection where organisms actively multiply and cause illness, and can progress to septic shock.',
  },
  {
    id: 'c5-q31', chapter: 5, type: 'mc',
    question: 'The chain of infection describes the sequence required for an infection to spread. Breaking any link:',
    options: [
      'Has no effect on transmission',
      'Can stop the spread of infection',
      'Guarantees the pathogen becomes more virulent',
      'Only matters for viral infections',
    ],
    answer: 1,
    explanation: 'Breaking any link in the chain of infection (pathogen, reservoir, portal of exit, transmission, portal of entry, susceptible host) stops the spread — which is why hand hygiene, isolation, and PPE are so effective.',
    term: 'Chain of infection', definition: 'The sequence of elements required for an infection to spread; breaking any link stops transmission.',
  },
  {
    id: 'c5-q32', chapter: 5, type: 'mc',
    question: 'Which type of drug would be used to treat a fungal infection such as candidiasis?',
    options: ['Antibacterial', 'Antiviral', 'Antifungal', 'Antihistamine'],
    answer: 2,
    explanation: 'Antifungals treat fungal infections (like Candida/yeast). Antibacterials treat bacteria and antivirals treat viruses — matching the drug class to the pathogen type is essential.',
  },
]
