import { Question } from './questions'

export const MATH_QUESTIONS: Question[] = [

  // ─────────────────────────────────────────────
  // SECTION 1: Systems of Measurement & Conversions
  // ─────────────────────────────────────────────

  {
    id: 'math-s1-q1', subject: 'math', chapter: 1, type: 'mc',
    question: 'Which metric prefix indicates one-thousandth (0.001) of the base unit?',
    options: ['Kilo-', 'Micro-', 'Milli-', 'Centi-'],
    answer: 2,
    explanation: 'Milli- = 0.001 of the base unit (1 mg = 0.001 g). Kilo- = 1,000×; micro- = 0.000001×; centi- = 0.01×.',
    term: 'Milli-', definition: 'Metric prefix meaning one-thousandth (1/1,000) of the base unit; e.g., 1 mg = 0.001 g.',
  },
  {
    id: 'math-s1-q2', subject: 'math', chapter: 1, type: 'mc',
    question: 'A patient weighs 176 lbs. What is the patient\'s weight in kilograms? (1 kg = 2.2 lbs)',
    options: ['60 kg', '70 kg', '80 kg', '387 kg'],
    answer: 2,
    explanation: '176 lbs ÷ 2.2 = 80 kg. A common error is multiplying instead of dividing (176 × 2.2 = 387.2), which gives an impossibly large result.',
  },
  {
    id: 'math-s1-q3', subject: 'math', chapter: 1, type: 'mc',
    question: 'How many milliliters are in 2.5 liters?',
    options: ['250 mL', '2,500 mL', '25 mL', '0.25 mL'],
    answer: 1,
    explanation: '1 L = 1,000 mL, so 2.5 L × 1,000 = 2,500 mL. Moving the decimal 3 places to the right converts liters to milliliters.',
  },
  {
    id: 'math-s1-q4', subject: 'math', chapter: 1, type: 'mc',
    question: 'A medication order reads: aspirin gr x (grains 10). Using the conversion 1 grain = 60 mg, how many milligrams should the nurse prepare?',
    options: ['60 mg', '300 mg', '600 mg', '650 mg'],
    answer: 2,
    explanation: '10 grains × 60 mg/grain = 600 mg. 650 mg is a standard adult aspirin tablet, which is close but uses a slightly different conversion factor (1 gr = 65 mg) sometimes seen in older references. For NCLEX, use 60 mg/grain.',
    term: 'Grain (gr)', definition: 'Apothecary unit of weight; 1 grain = approximately 60 mg in modern nursing calculations.',
  },
  {
    id: 'math-s1-q5', subject: 'math', chapter: 1, type: 'mc',
    question: 'A nurse instructs a patient to take 2 tablespoons of a liquid medication. How many milliliters is this?',
    options: ['10 mL', '15 mL', '30 mL', '60 mL'],
    answer: 2,
    explanation: '1 tablespoon = 15 mL, so 2 tablespoons = 2 × 15 = 30 mL. 1 teaspoon = 5 mL (not 1 tablespoon); confusing the two is a common error.',
  },
  {
    id: 'math-s1-q6', subject: 'math', chapter: 1, type: 'mc',
    question: 'A patient is instructed to drink 1 cup of water with their morning medications. How many milliliters should the nurse document as intake?',
    options: ['120 mL', '180 mL', '240 mL', '480 mL'],
    answer: 2,
    explanation: '1 cup = 8 oz = 240 mL. This is a critical conversion for I&O documentation and patient education.',
  },
  {
    id: 'math-s1-q7', subject: 'math', chapter: 1, type: 'mc',
    question: 'A physician orders morphine 4 mg. The available supply is labeled 0.004 g/mL. How many milligrams are in each milliliter of the supply?',
    options: ['0.004 mg', '0.04 mg', '4 mg', '40 mg'],
    answer: 2,
    explanation: '0.004 g × 1,000 mg/g = 4 mg. The available concentration is 4 mg/mL, which exactly matches the order — so the nurse would administer 1 mL. Converting grams to milligrams requires multiplying by 1,000.',
  },
  {
    id: 'math-s1-q8', subject: 'math', chapter: 1, type: 'mc',
    question: 'Which of the following correctly converts 2,500 mcg to milligrams?',
    options: ['0.25 mg', '2.5 mg', '25 mg', '250 mg'],
    answer: 1,
    explanation: '1 mg = 1,000 mcg, so 2,500 mcg ÷ 1,000 = 2.5 mg. Moving the decimal 3 places to the left converts micrograms to milligrams.',
    term: 'Micro- (mcg)', definition: 'Metric prefix meaning one-millionth of the base unit; 1 mcg = 0.001 mg = 0.000001 g.',
  },
  {
    id: 'math-s1-q9', subject: 'math', chapter: 1, type: 'mc',
    question: 'A patient is to receive 1.5 oz of an oral liquid. How many mL will the nurse administer? (1 oz = 30 mL)',
    options: ['15 mL', '30 mL', '45 mL', '60 mL'],
    answer: 2,
    explanation: '1.5 oz × 30 mL/oz = 45 mL. One ounce = 30 mL is a conversion nurses must know for I&O and medication administration.',
  },
  {
    id: 'math-s1-q10', subject: 'math', chapter: 1, type: 'mc',
    question: 'A nurse needs to convert 3.5 kg to grams. What is the correct answer?',
    options: ['35 g', '350 g', '3,500 g', '35,000 g'],
    answer: 2,
    explanation: '1 kg = 1,000 g, so 3.5 kg × 1,000 = 3,500 g. This within-system metric conversion moves the decimal 3 places to the right.',
  },
  {
    id: 'math-s1-q11', subject: 'math', chapter: 1, type: 'mc',
    question: 'Which measurement system uses teaspoons, tablespoons, and cups as its primary volume units?',
    options: ['Metric system', 'Apothecary system', 'Household system', 'SI system'],
    answer: 2,
    explanation: 'The household system uses familiar kitchen measures: teaspoon (5 mL), tablespoon (15 mL), and cup (240 mL). The apothecary system uses minims, drams, and ounces. The metric system uses mL and L.',
    term: 'Household system', definition: 'Measurement system using teaspoons, tablespoons, and cups; commonly used for patient medication instructions at home.',
  },
  {
    id: 'math-s1-q12', subject: 'math', chapter: 1, type: 'mc',
    question: 'A nurse converts a patient\'s weight from 90 kg to pounds. What is the correct result?',
    options: ['40.9 lbs', '178 lbs', '198 lbs', '204 lbs'],
    answer: 2,
    explanation: '90 kg × 2.2 lbs/kg = 198 lbs. Dividing 90 by 2.2 (40.9) is the error of going the wrong direction. The question asks kg → lbs, so multiply by 2.2.',
  },
  {
    id: 'math-s1-q13', subject: 'math', chapter: 1, type: 'mc',
    question: 'A nurse calculates that a patient needs 0.25 g of a medication. The supply is labeled in milligrams. What dose in milligrams should the nurse draw up?',
    options: ['2.5 mg', '25 mg', '250 mg', '2,500 mg'],
    answer: 2,
    explanation: '0.25 g × 1,000 mg/g = 250 mg. This is a critical conversion — giving 25 mg would be one-tenth of the correct dose; giving 2,500 mg would be a 10× overdose.',
  },
  {
    id: 'math-s1-q14', subject: 'math', chapter: 1, type: 'tf',
    question: 'TRUE or FALSE: 1 tablespoon is equal to 3 teaspoons and 15 mL.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. 1 tablespoon = 3 teaspoons = 15 mL. This relationship is critical for patient teaching and medication administration.',
  },
  {
    id: 'math-s1-q15', subject: 'math', chapter: 1, type: 'tf',
    question: 'TRUE or FALSE: The apothecary system is the primary measurement system used in modern U.S. nursing practice.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. The metric system is the primary system in modern nursing. The apothecary system (grains, drams, minims) is largely historical but nurses must recognize its units (e.g., "gr" for grain) when they appear in older orders.',
  },
  {
    id: 'math-s1-q16', subject: 'math', chapter: 1, type: 'sata',
    question: 'A nurse is reviewing medication conversions. Select ALL of the following that are CORRECT conversions.',
    options: [
      '1 tsp = 5 mL',
      '1 kg = 2.2 lbs',
      '1 oz = 15 mL',
      '1 grain = 60 mg',
      '1 L = 100 mL',
    ],
    answer: 0,
    answers: [0, 1, 3],
    explanation: 'Correct: 1 tsp = 5 mL ✓, 1 kg = 2.2 lbs ✓, 1 grain = 60 mg ✓. Incorrect: 1 oz = 30 mL (not 15 mL); 1 L = 1,000 mL (not 100 mL).',
  },
  {
    id: 'math-s1-q17', subject: 'math', chapter: 1, type: 'sata',
    question: 'Select ALL units that belong to the METRIC system.',
    options: [
      'Milligram (mg)',
      'Grain (gr)',
      'Liter (L)',
      'Dram',
      'Microgram (mcg)',
    ],
    answer: 0,
    answers: [0, 2, 4],
    explanation: 'Milligram, liter, and microgram are metric. Grain and dram belong to the apothecary system.',
  },
  {
    id: 'math-s1-q18', subject: 'math', chapter: 1, type: 'sata',
    question: 'Which of the following conversions are correct? Select all that apply.',
    options: [
      '1 cup = 240 mL',
      '1 tbsp = 3 tsp',
      '1 mg = 100 mcg',
      '1 kg = 1,000 g',
      '1 L = 1,000 mL',
    ],
    answer: 0,
    answers: [0, 1, 3, 4],
    explanation: 'Correct: 1 cup = 240 mL ✓, 1 tbsp = 3 tsp ✓, 1 kg = 1,000 g ✓, 1 L = 1,000 mL ✓. Incorrect: 1 mg = 1,000 mcg (not 100 mcg).',
  },
  {
    id: 'math-s1-q19', subject: 'math', chapter: 1, type: 'priority',
    question: 'A nurse must give a patient their ordered medication. The order is for 0.5 g PO and the supply is available in milligrams. Place the following conversion steps in PRIORITY ORDER (first step to last step).',
    options: [
      'Administer the correct number of tablets or mL',
      'Identify the conversion factor (1 g = 1,000 mg)',
      'Multiply 0.5 g × 1,000 mg/g = 500 mg',
      'Compare 500 mg to the available supply concentration',
    ],
    answer: 1,
    explanation: 'The priority sequence is: (1) Identify the conversion factor, (2) Multiply to convert, (3) Compare to available supply, (4) Administer. Always convert units before comparing to supply.',
  },
  {
    id: 'math-s1-q20', subject: 'math', chapter: 1, type: 'priority',
    question: 'A nurse needs to teach a newly hired LPN about household-to-metric conversions. Which conversion should the nurse teach FIRST because it is most commonly encountered in clinical oral medication administration?',
    options: [
      '1 cup = 240 mL',
      '1 tsp = 5 mL',
      '1 grain = 60 mg',
      '1 tbsp = 15 mL',
    ],
    answer: 1,
    explanation: 'The teaspoon-to-mL conversion (1 tsp = 5 mL) is taught first because it is most frequently encountered in oral liquid medication dosing for both adults and pediatrics. The grain conversion is important but belongs to the apothecary system, which is less commonly used.',
  },

  // ─────────────────────────────────────────────
  // SECTION 2: Medication Safety & Orders
  // ─────────────────────────────────────────────

  {
    id: 'math-s2-q1', subject: 'math', chapter: 2, type: 'mc',
    question: 'A nurse sees a medication order written as "5.0 mg." What is the safety concern with this notation?',
    options: [
      'The dose is too high for any medication',
      'The trailing zero could be misread as 50 mg, creating a tenfold overdose risk',
      'Leading zeros should be used instead',
      'Milligrams should always be written as micrograms',
    ],
    answer: 1,
    explanation: 'Trailing zeros are DANGEROUS. "5.0 mg" can be misread as "50 mg" — a 10× overdose. The correct notation is simply "5 mg." The Joint Commission prohibits trailing zeros in medication orders.',
    term: 'Trailing zero', definition: 'A zero written AFTER a decimal point (e.g., 5.0); prohibited in medication orders because "5.0 mg" can be misread as "50 mg," causing a tenfold error.',
  },
  {
    id: 'math-s2-q2', subject: 'math', chapter: 2, type: 'mc',
    question: 'A medication order reads ".5 mg." What is the correct way this dose should be written?',
    options: ['0.5 mg', '5 mg', '50 mg', '500 mg'],
    answer: 0,
    explanation: 'A leading zero is REQUIRED: "0.5 mg." Without it, ".5 mg" can be misread as "5 mg" — a 10× overdose. Always place a zero before the decimal point for doses less than 1.',
    term: 'Leading zero', definition: 'A zero placed BEFORE the decimal point for numbers less than 1 (e.g., 0.5 mg); required to prevent a tenfold dosing error.',
  },
  {
    id: 'math-s2-q3', subject: 'math', chapter: 2, type: 'mc',
    question: 'According to the Six Rights of Medication Administration, which right ensures the nurse confirms the patient\'s identity before giving a medication?',
    options: ['Right drug', 'Right patient', 'Right documentation', 'Right time'],
    answer: 1,
    explanation: 'The right patient requires the nurse to verify patient identity using at least two identifiers (e.g., name and date of birth or MRN) before administering any medication. This is the most fundamental safety check.',
    term: 'Six Rights of Medication Administration', definition: 'Right patient, right drug, right dose, right route, right time, right documentation — the six core checks every nurse performs before giving a medication.',
  },
  {
    id: 'math-s2-q4', subject: 'math', chapter: 2, type: 'mc',
    question: 'A nurse reads a medication order but notes it does not include the prescriber\'s signature. What action should the nurse take?',
    options: [
      'Administer the medication — the other elements are complete',
      'Contact the prescriber to obtain a signature before administering',
      'Have the charge nurse sign the order',
      'Document the missing signature and proceed',
    ],
    answer: 1,
    explanation: 'A prescriber signature is a required element of a complete medication order. An unsigned order is not valid. The nurse must contact the prescriber to complete the order before administering the medication.',
  },
  {
    id: 'math-s2-q5', subject: 'math', chapter: 2, type: 'mc',
    question: 'A nurse is preparing insulin. Which of the following reflects the MOST important safety behavior when handling this high-alert medication?',
    options: [
      'Administer without a second nurse check if you are experienced',
      'Use an insulin syringe only and obtain an independent double-check per facility policy',
      'Draw it up with a regular 3 mL syringe to save time',
      'Only verify with the MAR — no additional checks needed',
    ],
    answer: 1,
    explanation: 'Insulin is a high-alert medication. It must be drawn up with an insulin syringe (calibrated in units) and most facilities require an independent double-check. Regular syringes are inappropriate because insulin is dosed in units, not mL.',
  },
  {
    id: 'math-s2-q6', subject: 'math', chapter: 2, type: 'mc',
    question: 'At which THREE times does the nurse check a medication to follow the "three-check" rule?',
    options: [
      'When removing from storage, before preparing, before administering',
      'Before administering, during administration, after administration',
      'When the MAR prints, when scanning the barcode, after giving',
      'At shift start, at mid-shift, at shift end',
    ],
    answer: 0,
    explanation: 'The three-check rule: (1) when removing from storage/the medication drawer, (2) before preparing/drawing up the medication, (3) before administering to the patient. This catches errors at multiple points.',
    term: 'Three-check rule', definition: 'Verifying medication label accuracy three times: when removing from storage, before preparing, and before administering to the patient.',
  },
  {
    id: 'math-s2-q7', subject: 'math', chapter: 2, type: 'mc',
    question: 'A patient tells the nurse, "I don\'t want that medication." Which of the additional proposed medication rights supports the patient\'s ability to refuse?',
    options: ['Right reason', 'Right response', 'Right to refuse', 'Right documentation'],
    answer: 2,
    explanation: 'The right to refuse is one of three additional proposed rights (right reason, right response, right to refuse) beyond the original six. Patients always have the right to refuse medications; the nurse must document the refusal and notify the prescriber.',
  },
  {
    id: 'math-s2-q8', subject: 'math', chapter: 2, type: 'mc',
    question: 'A nurse receives an order for "warfarin 5.0 mg PO daily." Why should the nurse clarify this order before administering?',
    options: [
      'Warfarin is never given orally',
      'The trailing zero makes 5.0 mg dangerous — it could be misread as 50 mg',
      'Warfarin requires IV administration only',
      'Daily frequency is not acceptable for warfarin',
    ],
    answer: 1,
    explanation: 'Warfarin is an anticoagulant (high-alert medication) and "5.0 mg" contains a dangerous trailing zero — it could be misread as 50 mg. This is a 10× error risk on an already high-alert drug. Clarify the order and document "5 mg" without the trailing zero.',
  },
  {
    id: 'math-s2-q9', subject: 'math', chapter: 2, type: 'mc',
    question: 'Which of the following is NOT a required element of a complete medication order?',
    options: [
      'Patient\'s name',
      'Drug dose and route',
      'Patient\'s insurance information',
      'Prescriber\'s signature',
    ],
    answer: 2,
    explanation: 'Insurance information is a billing/administrative element, not a required part of a safe medication order. Required elements include: patient name, date/time, drug name, dose, route, frequency, and prescriber signature.',
  },
  {
    id: 'math-s2-q10', subject: 'math', chapter: 2, type: 'mc',
    question: 'A large medication dose is written as "1000 mg" in an order. What is the safest way to write this value?',
    options: ['1000 mg', '1,000 mg', '1.000 mg', '100.0 mg'],
    answer: 1,
    explanation: '"1,000 mg" with a comma is safest for large numbers to prevent misreading. "1000 mg" without a comma could be misread as "100 0 mg" or misinterpreted in electronic systems. The comma clearly separates thousands.',
  },
  {
    id: 'math-s2-q11', subject: 'math', chapter: 2, type: 'mc',
    question: 'Which class of medications is considered HIGH-ALERT and requires the MOST rigorous safety precautions?',
    options: [
      'Antacids and stool softeners',
      'Vitamins and supplements',
      'Insulin, anticoagulants, and concentrated electrolytes',
      'Antihistamines and decongestants',
    ],
    answer: 2,
    explanation: 'High-alert medications include insulin, anticoagulants (heparin, warfarin), concentrated electrolytes (KCl), opioids, and chemotherapy. These carry the highest risk of causing significant patient harm if used in error.',
    term: 'High-alert medications', definition: 'Medications that bear a heightened risk of causing significant patient harm when used in error; include insulin, anticoagulants, concentrated electrolytes, opioids, and chemotherapy.',
  },
  {
    id: 'math-s2-q12', subject: 'math', chapter: 2, type: 'mc',
    question: 'A nurse wants to verify the "right reason" before administering metformin to a patient. What does this additional medication right mean?',
    options: [
      'The nurse gives the medication for any reason the patient requests',
      'The nurse confirms the medication is indicated for the patient\'s documented diagnosis',
      'The nurse explains the reason for the medication only if the patient asks',
      'The prescriber gives a reason for every medication ordered',
    ],
    answer: 1,
    explanation: 'The right reason means the nurse confirms there is a valid clinical indication for the medication matching the patient\'s current diagnosis. For metformin, the nurse should confirm the patient has type 2 diabetes and no contraindications (e.g., kidney impairment).',
  },
  {
    id: 'math-s2-q13', subject: 'math', chapter: 2, type: 'mc',
    question: 'A medication order is missing the route of administration. A nurse notices this before administering IV potassium chloride. What is the nurse\'s priority action?',
    options: [
      'Administer IV since that is the most common route for potassium',
      'Hold the medication and contact the prescriber to clarify the route',
      'Give it orally since that is the safest default route',
      'Check a drug reference and administer the most common route listed',
    ],
    answer: 1,
    explanation: 'Route is a required element of a medication order. Potassium chloride is particularly dangerous — concentrated IV KCl given undiluted can cause fatal cardiac arrhythmias. The nurse must always clarify incomplete orders before administering, especially for high-alert medications.',
  },
  {
    id: 'math-s2-q14', subject: 'math', chapter: 2, type: 'tf',
    question: 'TRUE or FALSE: It is acceptable to write a medication dose as ".5 mg" as long as the prescriber knows what they mean.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Leading zeros are REQUIRED. ".5 mg" must be written as "0.5 mg." Intent does not prevent misreading. This is a Joint Commission requirement and a standard medication safety practice.',
  },
  {
    id: 'math-s2-q15', subject: 'math', chapter: 2, type: 'tf',
    question: 'TRUE or FALSE: After administering a medication, the nurse should document the administration immediately to ensure the right documentation right is fulfilled.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. Right documentation requires timely, accurate recording of the medication given (drug, dose, route, time, patient response). Delayed documentation creates safety risks — another nurse may give a duplicate dose if the record is not complete.',
  },
  {
    id: 'math-s2-q16', subject: 'math', chapter: 2, type: 'sata',
    question: 'A nurse is reviewing medication order safety. Select ALL examples of SAFE medication documentation practices.',
    options: [
      'Write 0.5 mg (not .5 mg)',
      'Write 5 mg (not 5.0 mg)',
      'Write 1,000 mg (not 1000 mg for large numbers)',
      'Write .25 mg to save time',
      'Omit trailing zeros after decimal points',
    ],
    answer: 0,
    answers: [0, 1, 2, 4],
    explanation: 'Safe practices: leading zero (0.5 mg) ✓, no trailing zero (5 mg, not 5.0) ✓, comma for large numbers (1,000 mg) ✓, omit trailing zeros ✓. Writing ".25 mg" is unsafe — a leading zero is required: "0.25 mg."',
  },
  {
    id: 'math-s2-q17', subject: 'math', chapter: 2, type: 'sata',
    question: 'Select ALL medications that are classified as HIGH-ALERT medications.',
    options: [
      'Insulin',
      'Ibuprofen',
      'Heparin (anticoagulant)',
      'Concentrated potassium chloride',
      'Acetaminophen',
    ],
    answer: 0,
    answers: [0, 2, 3],
    explanation: 'Insulin ✓, heparin ✓, and concentrated potassium chloride ✓ are classic high-alert medications. Ibuprofen and acetaminophen are common OTC drugs without the same level of risk, though they require appropriate assessment.',
  },
  {
    id: 'math-s2-q18', subject: 'math', chapter: 2, type: 'sata',
    question: 'Select ALL of the components that are REQUIRED elements of a valid medication order.',
    options: [
      'Patient\'s full name',
      'Date and time the order was written',
      'Medication dose and route',
      'Patient\'s insurance provider',
      'Prescriber\'s signature',
    ],
    answer: 0,
    answers: [0, 1, 2, 4],
    explanation: 'Required elements: patient name ✓, date/time ✓, drug name/dose/route/frequency ✓, prescriber signature ✓. Insurance information is an administrative/billing detail, not a medication order element.',
  },
  {
    id: 'math-s2-q19', subject: 'math', chapter: 2, type: 'priority',
    question: 'A nurse receives a new medication order. Place the following actions in the CORRECT PRIORITY ORDER to ensure medication safety.',
    options: [
      'Administer the medication to the patient using two-identifier verification',
      'Verify the order is complete (patient name, drug, dose, route, frequency, prescriber signature)',
      'Check the medication three times and review the MAR',
      'Document administration immediately after giving the medication',
    ],
    answer: 1,
    explanation: 'Priority sequence: (1) Verify the order is complete, (2) Check medication three times and review MAR, (3) Administer with two-identifier verification, (4) Document immediately after. Verification comes before administration; documentation follows.',
  },
  {
    id: 'math-s2-q20', subject: 'math', chapter: 2, type: 'priority',
    question: 'A nurse discovers a medication error — a patient received twice the ordered dose. What is the nurse\'s FIRST priority action?',
    options: [
      'Complete an incident report',
      'Notify the charge nurse',
      'Assess the patient\'s condition and vital signs',
      'Document the error in the medical record',
    ],
    answer: 2,
    explanation: 'Patient safety first. The nurse must immediately assess the patient\'s condition and vital signs to identify any adverse effects requiring urgent treatment. Then notify the prescriber and charge nurse, document, and complete an incident report — but patient assessment comes first.',
  },

  // ─────────────────────────────────────────────
  // SECTION 3: I&O Calculation
  // ─────────────────────────────────────────────

  {
    id: 'math-s3-q1', subject: 'math', chapter: 3, type: 'mc',
    question: 'A patient consumes the following at lunch: 6 oz of soup, 4 oz of juice, 1 cup of ice cream, and ½ cup of water. How many mL should the nurse record as intake? (1 oz = 30 mL; 1 cup = 240 mL)',
    options: ['480 mL', '600 mL', '660 mL', '750 mL'],
    answer: 2,
    explanation: 'Soup: 6 oz × 30 = 180 mL; Juice: 4 oz × 30 = 120 mL; Ice cream: 1 cup × 240 = 240 mL; Water: ½ cup × 240 = 120 mL. Total = 180 + 120 + 240 + 120 = 660 mL. Ice cream is liquid at room temperature, so it counts as intake.',
  },
  {
    id: 'math-s3-q2', subject: 'math', chapter: 3, type: 'mc',
    question: 'An IV bag is marked at 1,000 mL. After 4 hours, the markings on the bag show 375 mL remaining. How many mL has the patient received?',
    options: ['375 mL', '575 mL', '625 mL', '1,000 mL'],
    answer: 2,
    explanation: '1,000 mL (started) − 375 mL (remaining) = 625 mL infused. IV bag markings count DOWN as fluid infuses — what remains is NOT what was given. The nurse documents 625 mL as parenteral intake.',
    term: 'IV bag markings', definition: 'Graduated markings on an IV bag that count downward as fluid infuses; the amount infused = starting volume minus remaining volume.',
  },
  {
    id: 'math-s3-q3', subject: 'math', chapter: 3, type: 'mc',
    question: 'A patient\'s 8-hour shift urine output totals 180 mL. The patient weighs 75 kg. Is this output adequate?',
    options: [
      'Yes — urine output is well within normal range',
      'No — normal minimum is 30 mL/hr; 180 mL over 8 hours = 22.5 mL/hr, which is concerning',
      'No — urine output must be at least 1,000 mL per 8-hour shift',
      'Yes — any urine output is acceptable as long as the patient is voiding',
    ],
    answer: 1,
    explanation: '180 mL ÷ 8 hours = 22.5 mL/hr. Normal minimum urine output is 30 mL/hr (or 0.5 mL/kg/hr; 75 kg × 0.5 = 37.5 mL/hr). At 22.5 mL/hr, this patient is below the acceptable minimum — the nurse should notify the provider.',
    term: 'Minimum urine output', definition: 'The lowest acceptable urine output: 30 mL/hr for adults, or 0.5 mL/kg/hr; output below this threshold indicates inadequate renal perfusion.',
  },
  {
    id: 'math-s3-q4', subject: 'math', chapter: 3, type: 'mc',
    question: 'Which of the following is classified as PARENTERAL intake and should be recorded on the intake side of the I&O record?',
    options: [
      'Oral water and juice',
      'IV fluids, IV medications, and tube feedings',
      'Urine output and wound drainage',
      'Ice chips and popsicles',
    ],
    answer: 1,
    explanation: 'Parenteral intake = anything entering the body other than orally: IV fluids, IV medications, tube feedings, and blood products. Oral water, juice, ice chips, and popsicles are oral intake. Urine and drainage are outputs.',
    term: 'Parenteral intake', definition: 'Fluid entering the body by routes other than the GI tract, including IV fluids, IV medications, tube feedings, and blood products.',
  },
  {
    id: 'math-s3-q5', subject: 'math', chapter: 3, type: 'mc',
    question: 'During a 12-hour shift, a patient receives: 850 mL IV fluid, 150 mL IV antibiotic, and drinks 600 mL oral fluids. Output: 980 mL urine, 120 mL NG suction. What is the patient\'s fluid balance for the shift?',
    options: ['+500 mL (positive balance)', '+600 mL (positive balance)', '+1,600 mL (positive balance)', '−100 mL (negative balance)'],
    answer: 0,
    explanation: 'Total Intake: 850 + 150 + 600 = 1,600 mL. Total Output: 980 + 120 = 1,100 mL. Balance = 1,600 − 1,100 = +500 mL positive fluid balance.',
  },
  {
    id: 'math-s3-q6', subject: 'math', chapter: 3, type: 'mc',
    question: 'A patient had a bowl of chicken noodle soup (240 mL), 4 oz of gelatin, and 2 popsicles (each 60 mL) for lunch. How many mL of oral intake should the nurse document? (1 oz = 30 mL)',
    options: ['300 mL', '360 mL', '420 mL', '480 mL'],
    answer: 2,
    explanation: 'Soup: 240 mL; Gelatin: 4 oz × 30 = 120 mL; Popsicles: 2 × 60 = 120 mL. Total = 240 + 120 + 120 = 480 mL. Gelatin and popsicles are liquid at room temperature — both count as intake.',
  },
  {
    id: 'math-s3-q7', subject: 'math', chapter: 3, type: 'mc',
    question: 'A nurse is calculating a patient\'s output. Which of the following should be included in the OUTPUT measurement?',
    options: [
      'IV fluids and oral liquids',
      'Urine, emesis, wound drainage, chest tube drainage, and liquid stool',
      'Tube feedings and blood products',
      'Perspiration and respiratory moisture',
    ],
    answer: 1,
    explanation: 'Measurable output includes: urine, emesis (vomit), wound drainage, chest tube drainage, NG suction, and liquid stool. Perspiration and respiratory moisture are insensible losses — not measurable. IV fluids and tube feedings are intake.',
  },
  {
    id: 'math-s3-q8', subject: 'math', chapter: 3, type: 'mc',
    question: 'An 80 kg patient has a urine output of 35 mL/hr. How does this compare to the minimum acceptable urine output?',
    options: [
      'Below normal — minimum is 80 mL/hr for this patient',
      'Adequate — minimum is 0.5 mL/kg/hr = 40 mL/hr; 35 mL/hr is just below normal',
      'Normal — any output above 30 mL/hr is always acceptable',
      'Above normal — this patient is producing too much urine',
    ],
    answer: 1,
    explanation: '0.5 mL/kg/hr × 80 kg = 40 mL/hr minimum. At 35 mL/hr, this patient is slightly below the weight-based minimum. The nurse should monitor closely and notify the provider if it continues to decline.',
  },
  {
    id: 'math-s3-q9', subject: 'math', chapter: 3, type: 'mc',
    question: 'Which food item is NOT counted as part of oral fluid intake in I&O measurement?',
    options: [
      'Popsicles',
      'Gelatin (Jell-O)',
      'Scrambled eggs',
      'Ice cream',
    ],
    answer: 2,
    explanation: 'Scrambled eggs are a solid food and remain solid at room temperature — they are NOT counted as fluid intake. Popsicles, gelatin, and ice cream all become liquid at room temperature and ARE counted as oral fluid intake.',
  },
  {
    id: 'math-s3-q10', subject: 'math', chapter: 3, type: 'mc',
    question: 'At the start of the shift, an IV bag reads 750 mL. At the end of the 8-hour shift, the bag reads 0 mL and a new bag at 500 mL was started, now reading 320 mL. How much IV fluid has the patient received this shift?',
    options: ['570 mL', '750 mL', '930 mL', '1,070 mL'],
    answer: 2,
    explanation: 'First bag: 750 − 0 = 750 mL infused. Second bag: 500 − 320 = 180 mL infused. Total = 750 + 180 = 930 mL. Always subtract remaining volume from starting volume for each bag.',
  },
  {
    id: 'math-s3-q11', subject: 'math', chapter: 3, type: 'mc',
    question: 'What are "insensible losses" in the context of I&O measurement?',
    options: [
      'Urine output that was not measured properly',
      'Fluid lost through perspiration and respiration that cannot be directly measured',
      'NG tube output that is discarded',
      'Blood loss that is estimated rather than measured',
    ],
    answer: 1,
    explanation: 'Insensible losses are fluid losses that cannot be directly measured — primarily through the skin (perspiration) and lungs (respiration). They are acknowledged in fluid balance calculations but are not recorded as measurable output on the I&O record.',
    term: 'Insensible losses', definition: 'Fluid lost through perspiration and respiration that cannot be directly measured; typically estimated at 500–900 mL/day in adults.',
  },
  {
    id: 'math-s3-q12', subject: 'math', chapter: 3, type: 'mc',
    question: 'A patient drinks 8 oz of water, 6 oz of juice, 4 oz of broth, and eats a 4 oz serving of solid macaroni. What is the oral fluid intake in mL? (1 oz = 30 mL)',
    options: ['420 mL', '480 mL', '540 mL', '660 mL'],
    answer: 2,
    explanation: 'Water: 8 × 30 = 240 mL; Juice: 6 × 30 = 180 mL; Broth: 4 × 30 = 120 mL; Macaroni: solid food, NOT counted. Total = 240 + 180 + 120 = 540 mL. Solid foods are excluded from fluid intake calculations.',
  },
  {
    id: 'math-s3-q13', subject: 'math', chapter: 3, type: 'mc',
    question: 'A nurse is documenting I&O. The patient has: urine 400 mL, wound drain 80 mL, and 50 mL emesis. What is the total output for this period?',
    options: ['400 mL', '450 mL', '480 mL', '530 mL'],
    answer: 3,
    explanation: 'Total output = urine (400) + wound drain (80) + emesis (50) = 530 mL. All measurable fluid losses — urine, drainage, emesis, NG output, liquid stool — are summed for total output.',
  },
  {
    id: 'math-s3-q14', subject: 'math', chapter: 3, type: 'tf',
    question: 'TRUE or FALSE: A patient who is receiving nothing by mouth (NPO) can still have parenteral intake that must be recorded.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. NPO refers to oral intake only. IV fluids, IV medications, and other parenteral fluids continue and must be recorded as intake. NPO patients may still receive significant fluid through parenteral routes.',
  },
  {
    id: 'math-s3-q15', subject: 'math', chapter: 3, type: 'tf',
    question: 'TRUE or FALSE: An IV bag with markings showing 400 mL means the patient has received 400 mL of fluid.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. IV bag markings show what REMAINS, not what was given. If the bag started at 1,000 mL and now shows 400 mL, the patient received 600 mL (1,000 − 400 = 600 mL infused).',
  },
  {
    id: 'math-s3-q16', subject: 'math', chapter: 3, type: 'sata',
    question: 'A nurse is calculating oral fluid intake for a patient\'s lunch tray. Select ALL items that should be counted as fluid intake.',
    options: [
      'A cup of chicken broth',
      'A serving of gelatin (Jell-O)',
      'A hard-boiled egg',
      'An ice cream bar',
      'A glass of apple juice',
    ],
    answer: 0,
    answers: [0, 1, 3, 4],
    explanation: 'Count as fluid: broth ✓ (liquid), gelatin ✓ (liquid at room temp), ice cream ✓ (liquid at room temp), apple juice ✓ (liquid). Exclude: hard-boiled egg (solid at room temperature).',
  },
  {
    id: 'math-s3-q17', subject: 'math', chapter: 3, type: 'sata',
    question: 'Select ALL items that belong on the OUTPUT side of the I&O record.',
    options: [
      'Urine',
      'IV antibiotic infusion',
      'Nasogastric (NG) suction',
      'Wound drainage',
      'Tube feeding',
    ],
    answer: 0,
    answers: [0, 2, 3],
    explanation: 'Output: urine ✓, NG suction ✓, wound drainage ✓. IV antibiotics and tube feedings are INTAKE items. Only fluid leaving the body is output.',
  },
  {
    id: 'math-s3-q18', subject: 'math', chapter: 3, type: 'sata',
    question: 'A nurse is concerned about a patient\'s urine output. Select ALL assessment findings that indicate INADEQUATE urine output.',
    options: [
      'Urine output of 20 mL/hr in an adult',
      'Urine output of 50 mL/hr',
      'Total urine output of 160 mL over 8 hours (20 mL/hr)',
      'Urine output of 0.3 mL/kg/hr in a 70 kg patient',
      'Urine output of 35 mL/hr consistently',
    ],
    answer: 0,
    answers: [0, 2, 3],
    explanation: 'Inadequate: 20 mL/hr ✓ (below 30 mL/hr minimum), 160 mL/8 hrs = 20 mL/hr ✓ (below minimum), 0.3 mL/kg/hr ✓ (below 0.5 mL/kg/hr minimum). Normal: 50 mL/hr ✓ and 35 mL/hr are acceptable (above 30 mL/hr threshold).',
  },
  {
    id: 'math-s3-q19', subject: 'math', chapter: 3, type: 'priority',
    question: 'A nurse notes that a patient\'s urine output for the past 3 hours has been 20 mL, 18 mL, and 22 mL. Place the following nursing actions in PRIORITY ORDER.',
    options: [
      'Document the finding in the medical record',
      'Assess the patient (fluid status, mucous membranes, skin turgor, vital signs)',
      'Notify the healthcare provider of the low urine output',
      'Check if IV fluids are infusing at the correct rate',
    ],
    answer: 1,
    explanation: 'Priority: (1) Assess the patient first to gather clinical data, (2) Check IV fluid rate (quick intervention), (3) Notify the provider with assessment data, (4) Document all findings. Assessment before action — you need data before calling the provider.',
  },
  {
    id: 'math-s3-q20', subject: 'math', chapter: 3, type: 'priority',
    question: 'At the end of a shift, a nurse must complete I&O documentation. Which action should the nurse complete FIRST?',
    options: [
      'Total all outputs and compare to intake',
      'Collect and measure any remaining urine or drainage before totaling',
      'Document the current IV bag volume',
      'Report the shift total to the oncoming nurse',
    ],
    answer: 1,
    explanation: 'The nurse must first collect and measure any remaining/current drainage before totaling the shift I&O — otherwise output is underreported. Then document IV bag volume, total all I&O, and report to the oncoming nurse.',
  },

  // ─────────────────────────────────────────────
  // SECTION 4: Dimensional Analysis
  // ─────────────────────────────────────────────

  {
    id: 'math-s4-q1', subject: 'math', chapter: 4, type: 'mc',
    question: 'Order: Amoxicillin 750 mg PO. Available: 250 mg per 5 mL suspension. How many mL should the nurse administer?',
    options: ['10 mL', '12 mL', '15 mL', '7.5 mL'],
    answer: 2,
    explanation: 'Using dimensional analysis: 750 mg × (5 mL ÷ 250 mg) = 3,750 ÷ 250 = 15 mL. The mg units cancel, leaving mL. 10 mL would be for 500 mg; inverting the fraction (250 mg ÷ 5 mL) and multiplying gives 750 × 50 — a setup error.',
    term: 'Dimensional analysis', definition: 'A calculation method using a chain of fractions where unwanted units cancel, leaving only the desired unit in the answer.',
  },
  {
    id: 'math-s4-q2', subject: 'math', chapter: 4, type: 'mc',
    question: 'A patient is ordered hydromorphone 1.5 mg IV. Available: 2 mg/mL. How many mL will the nurse administer?',
    options: ['0.5 mL', '0.75 mL', '1.0 mL', '1.33 mL'],
    answer: 1,
    explanation: '1.5 mg × (1 mL ÷ 2 mg) = 1.5 ÷ 2 = 0.75 mL. The mg cancel, leaving mL. 0.5 mL would be for 1 mg; 1.0 mL would be the full 2 mg (the entire vial).',
  },
  {
    id: 'math-s4-q3', subject: 'math', chapter: 4, type: 'mc',
    question: 'A patient weighs 154 lbs. The order is for Drug X at 5 mg/kg/day. Using dimensional analysis, what is the total daily dose? (1 kg = 2.2 lbs)',
    options: ['280 mg/day', '350 mg/day', '385 mg/day', '770 mg/day'],
    answer: 1,
    explanation: '154 lbs × (1 kg ÷ 2.2 lbs) × (5 mg ÷ 1 kg) = 154 ÷ 2.2 × 5 = 70 kg × 5 mg/kg = 350 mg/day. Units cancel: lbs→kg→mg/day. Forgetting to convert lbs to kg gives 154 × 5 = 770 mg (wrong).',
  },
  {
    id: 'math-s4-q4', subject: 'math', chapter: 4, type: 'mc',
    question: 'What is the FIRST number you write down when setting up a dimensional analysis equation?',
    options: [
      'The available concentration (supply on hand)',
      'The conversion factor needed',
      'The ordered dose (what is prescribed)',
      'The desired unit of the answer',
    ],
    answer: 2,
    explanation: 'Dimensional analysis always STARTS with the ordered dose — what the prescriber wrote. Then you multiply by fractions (available concentration, conversion factors) to cancel unwanted units until only the desired unit remains.',
  },
  {
    id: 'math-s4-q5', subject: 'math', chapter: 4, type: 'mc',
    question: 'An IV is ordered to run at 30 mg/hr. The available concentration is 120 mg per 250 mL. What rate in mL/hr should the nurse program the pump?',
    options: ['30 mL/hr', '62.5 mL/hr', '90 mL/hr', '14.4 mL/hr'],
    answer: 1,
    explanation: '30 mg/hr × (250 mL ÷ 120 mg) = 7,500 ÷ 120 = 62.5 mL/hr. The mg units cancel: mg/hr × mL/mg = mL/hr. Setting up the fraction as 120 mg ÷ 250 mL (inverted) would give 30 × 0.48 = 14.4 mL/hr — a setup error.',
  },
  {
    id: 'math-s4-q6', subject: 'math', chapter: 4, type: 'mc',
    question: 'Order: Penicillin 0.5 g IM. Available: 500 mg/mL. How many mL should the nurse administer?',
    options: ['0.5 mL', '1 mL', '2 mL', '5 mL'],
    answer: 1,
    explanation: '0.5 g × (1,000 mg ÷ 1 g) × (1 mL ÷ 500 mg) = 500 ÷ 500 = 1 mL. Note the two-step DA: first convert grams to milligrams, then use concentration to find mL. Skipping the g→mg step and using 0.5 ÷ 500 = 0.001 mL is the common error.',
  },
  {
    id: 'math-s4-q7', subject: 'math', chapter: 4, type: 'mc',
    question: 'In dimensional analysis, what does it mean when the units "cancel"?',
    options: [
      'The numbers become equal on both sides of the equation',
      'The same unit appears in the numerator of one fraction and the denominator of another, eliminating it from the final answer',
      'The medication dose is eliminated from the calculation',
      'The answer is confirmed as correct',
    ],
    answer: 1,
    explanation: 'Unit cancellation occurs when the same unit appears in the top (numerator) of one fraction and the bottom (denominator) of an adjacent fraction — they divide out to 1 and disappear. The remaining units are the units of your answer.',
  },
  {
    id: 'math-s4-q8', subject: 'math', chapter: 4, type: 'mc',
    question: 'An IV dopamine drip is ordered at 400 mcg/min. The solution contains 800 mg in 500 mL. Using DA, what rate in mL/hr should the pump be set to?',
    options: ['7.5 mL/hr', '12 mL/hr', '15 mL/hr', '30 mL/hr'],
    answer: 2,
    explanation: '400 mcg/min × (1 mg ÷ 1,000 mcg) × (500 mL ÷ 800 mg) × (60 min ÷ 1 hr) = 400 × 0.001 × 0.625 × 60 = 15 mL/hr. Units: mcg/min → mg/min → mL/min → mL/hr. All unit conversions happen in one chained DA equation.',
  },
  {
    id: 'math-s4-q9', subject: 'math', chapter: 4, type: 'mc',
    question: 'A nurse is teaching a student about dimensional analysis. Which statement by the student indicates correct understanding?',
    options: [
      '"I multiply all the numerators and divide by all the denominators to get my answer."',
      '"I just need to know the formula D/H × Q — DA is too complicated."',
      '"I set up fractions so that unwanted units appear in both a numerator and denominator so they cancel out."',
      '"I always convert units first, then recalculate from scratch in a separate step."',
    ],
    answer: 2,
    explanation: 'The student who understands DA knows the key principle: arrange fractions so unwanted units cancel. DA can incorporate unit conversions AND concentration in one chained equation — it does not require separate steps.',
  },
  {
    id: 'math-s4-q10', subject: 'math', chapter: 4, type: 'mc',
    question: 'Order: furosemide 0.5 mg/kg IV push. Patient weighs 88 lbs. Available: 10 mg/2 mL. How many mL should the nurse administer? (1 kg = 2.2 lbs)',
    options: ['2 mL', '4 mL', '8 mL', '10 mL'],
    answer: 1,
    explanation: '88 lbs × (1 kg ÷ 2.2 lbs) × (0.5 mg ÷ 1 kg) × (2 mL ÷ 10 mg) = 88 ÷ 2.2 × 0.5 × 0.2 = 40 kg × 0.5 × 0.2 = 4 mL. Chain: lbs → kg → mg → mL. All units cancel except mL.',
  },
  {
    id: 'math-s4-q11', subject: 'math', chapter: 4, type: 'mc',
    question: 'Why is it critical to label EVERY number with its unit when setting up a dimensional analysis equation?',
    options: [
      'It is a regulatory requirement but doesn\'t affect calculation accuracy',
      'It helps the nurse see which units cancel and confirms the answer\'s unit is correct',
      'It is only necessary for cross-system conversions',
      'It slows the calculation down but is required by NCLEX standards',
    ],
    answer: 1,
    explanation: 'Labeling every number with its unit is the core safety feature of DA. It lets the nurse visually confirm which units cancel and verify the final answer is in the correct unit. If the wrong unit remains after cancellation, the equation is set up incorrectly.',
  },
  {
    id: 'math-s4-q12', subject: 'math', chapter: 4, type: 'mc',
    question: 'A nurse needs to convert 2.5 g to milligrams using dimensional analysis. Which setup is CORRECT?',
    options: [
      '2.5 g × (1 g ÷ 1,000 mg)',
      '2.5 g × (1,000 mg ÷ 1 g)',
      '2.5 g ÷ (1,000 mg ÷ 1 g)',
      '2.5 g × (1 mg ÷ 1,000 g)',
    ],
    answer: 1,
    explanation: '2.5 g × (1,000 mg ÷ 1 g) = 2,500 mg. The "g" in 2.5 g and the "g" in the denominator cancel, leaving mg. Option A inverts the fraction (gives 0.0025 — wrong direction). Always put the unit you want to ELIMINATE in the denominator of the conversion fraction.',
  },
  {
    id: 'math-s4-q13', subject: 'math', chapter: 4, type: 'mc',
    question: 'Order: vancomycin 1.25 g IV. Available: 500 mg/100 mL premixed bags. How many mL should be infused?',
    options: ['100 mL', '150 mL', '250 mL', '500 mL'],
    answer: 2,
    explanation: '1.25 g × (1,000 mg ÷ 1 g) × (100 mL ÷ 500 mg) = 1,250 × 0.2 = 250 mL. Chain: g → mg → mL. The nurse would need 2.5 bags of the 100 mL premix (typically prepared by pharmacy as one bag).',
  },
  {
    id: 'math-s4-q14', subject: 'math', chapter: 4, type: 'tf',
    question: 'TRUE or FALSE: Dimensional analysis can only be used for within-system conversions (e.g., mg to g) but not for cross-system conversions (e.g., lbs to kg).',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. A major advantage of dimensional analysis is that it can cross measurement systems in a single equation — for example, converting lbs to kg and then calculating a weight-based dose in the same chained equation.',
  },
  {
    id: 'math-s4-q15', subject: 'math', chapter: 4, type: 'tf',
    question: 'TRUE or FALSE: In a correctly set up dimensional analysis equation, the only unit remaining after all cancellations should be the unit of the desired answer.',
    options: ['True', 'False'],
    answer: 0,
    explanation: 'True. This is the built-in proof of dimensional analysis: if your setup is correct, the only uncanceled unit is the unit you want (e.g., mL). If a different unit remains, you know the equation is set up incorrectly.',
  },
  {
    id: 'math-s4-q16', subject: 'math', chapter: 4, type: 'sata',
    question: 'A nursing student is learning dimensional analysis. Select ALL statements that are TRUE about the dimensional analysis method.',
    options: [
      'Start the equation with the ordered (prescribed) dose',
      'Arrange fractions so unwanted units cancel',
      'You must always do unit conversions as a separate calculation first',
      'You can incorporate multiple conversion factors in one equation',
      'The final unit remaining should match the desired answer unit',
    ],
    answer: 0,
    answers: [0, 1, 3, 4],
    explanation: 'True: start with ordered dose ✓, cancel units ✓, incorporate multiple factors ✓, final unit must match desired ✓. False: separate calculations are NOT required — DA handles all conversions in one chained equation.',
  },
  {
    id: 'math-s4-q17', subject: 'math', chapter: 4, type: 'sata',
    question: 'Select ALL scenarios where dimensional analysis would be the appropriate calculation method to use.',
    options: [
      'Converting a patient\'s weight from lbs to kg for a weight-based dose',
      'Calculating mL/hr when given mg/hr and a drug concentration',
      'Estimating a patient\'s pain on the 0–10 scale',
      'Converting an oral dose from grams to milligrams',
      'Calculating a weight-based pediatric dose that crosses systems',
    ],
    answer: 0,
    answers: [0, 1, 3, 4],
    explanation: 'DA is used for all unit-conversion and dose calculation scenarios: lbs to kg ✓, mL/hr from mg/hr ✓, g to mg ✓, weight-based pediatric dose ✓. Pain scale assessment is clinical judgment, not a math calculation.',
  },
  {
    id: 'math-s4-q18', subject: 'math', chapter: 4, type: 'sata',
    question: 'A nurse checks a DA equation and finds the final unit is "mg²/mL" instead of "mg." Select ALL conclusions that are CORRECT about this finding.',
    options: [
      'The equation is set up incorrectly',
      'At least one conversion fraction is inverted',
      'The nurse should recalculate with properly oriented fractions',
      'The answer is still valid because it contains the right drug unit',
      'The nurse should administer based on the numeric result regardless',
    ],
    answer: 0,
    answers: [0, 1, 2],
    explanation: 'If the unit is wrong, the equation is set up incorrectly ✓ — likely an inverted fraction ✓ — and must be recalculated ✓. A wrong unit invalidates the numeric result. Never administer based on a misconfigured equation.',
  },
  {
    id: 'math-s4-q19', subject: 'math', chapter: 4, type: 'priority',
    question: 'A nurse is calculating an IV rate using dimensional analysis. Place the steps in the CORRECT ORDER.',
    options: [
      'Multiply all numerators and divide by all denominators to solve',
      'Write down the ordered dose as the starting point',
      'Verify the final unit matches the desired answer unit',
      'Add conversion factor fractions so unwanted units cancel',
    ],
    answer: 1,
    explanation: 'DA sequence: (1) Write the ordered dose, (2) Add conversion fractions to cancel units, (3) Multiply/divide to solve, (4) Verify the remaining unit is correct. The unit check at the end catches setup errors before administering.',
  },
  {
    id: 'math-s4-q20', subject: 'math', chapter: 4, type: 'priority',
    question: 'A nurse receives an order for a weight-based IV medication requiring unit conversion across two systems. What is the PRIORITY reason to use dimensional analysis over a simple D/H × Q formula?',
    options: [
      'DA is required by NCLEX and most hospitals for all calculations',
      'DA allows all unit conversions and the dose calculation to occur in one organized equation, reducing errors from multiple separate steps',
      'D/H × Q cannot be used with IV medications',
      'DA gives a different (more accurate) numeric answer than other methods',
    ],
    answer: 1,
    explanation: 'DA\'s priority advantage is error reduction: all conversion factors and the dose calculation are organized in one transparent equation where unit cancellation provides a built-in check. Multiple separate calculations multiply the chance of transcription or arithmetic errors.',
  },

  // ─────────────────────────────────────────────
  // SECTION 5: Oral Doses & Reconstitution
  // ─────────────────────────────────────────────

  {
    id: 'math-s5-q1', subject: 'math', chapter: 5, type: 'mc',
    question: 'Order: metoprolol 37.5 mg PO. Available: 25 mg scored tablets. Using D/H × Q, how many tablets should the nurse administer?',
    options: ['1 tablet', '1.5 tablets', '2 tablets', '3 tablets'],
    answer: 1,
    explanation: 'D/H × Q = 37.5 mg ÷ 25 mg × 1 tablet = 1.5 tablets. Because the tablets are SCORED, they can safely be split in half. 1.5 tablets is within the acceptable range (≤3 tablets).',
    term: 'D/H × Q formula', definition: 'Oral dose formula: Desired dose ÷ Have (available dose) × Quantity; gives the number of tablets or mL to administer.',
  },
  {
    id: 'math-s5-q2', subject: 'math', chapter: 5, type: 'mc',
    question: 'Order: acetaminophen 1,000 mg PO. Available: 500 mg tablets (unscored). How many tablets should the nurse give?',
    options: ['1 tablet', '1.5 tablets', '2 tablets', '4 tablets'],
    answer: 2,
    explanation: 'D/H × Q = 1,000 ÷ 500 × 1 = 2 tablets. This is within the safe range (≤3 tablets per dose). Unscored tablets cannot be split, but 2 whole tablets are required and appropriate here.',
  },
  {
    id: 'math-s5-q3', subject: 'math', chapter: 5, type: 'mc',
    question: 'A nurse is reconstituting a 1 g vial of cefazolin. The directions say to add 2.5 mL of sterile water, resulting in a final volume of 3 mL. What is the final concentration?',
    options: ['250 mg/mL', '333 mg/mL', '400 mg/mL', '500 mg/mL'],
    answer: 1,
    explanation: '1 g = 1,000 mg total drug ÷ 3 mL final volume = 333 mg/mL. The final volume (3 mL) is slightly larger than the diluent added (2.5 mL) because the powder displaces volume. Always use the FINAL volume, not the diluent volume.',
    term: 'Final concentration', definition: 'Total amount of drug divided by the total final volume after reconstitution; used to calculate the volume to administer.',
  },
  {
    id: 'math-s5-q4', subject: 'math', chapter: 5, type: 'mc',
    question: 'After reconstituting a vial, a nurse has a final concentration of 250 mg/mL. The order is for 375 mg. How many mL should the nurse draw up?',
    options: ['0.75 mL', '1.5 mL', '2 mL', '3 mL'],
    answer: 1,
    explanation: 'D/H × Q = 375 mg ÷ 250 mg/mL × 1 mL = 1.5 mL. Alternatively: 375 ÷ 250 = 1.5 mL. Drawing 0.75 mL would deliver 187.5 mg (half the correct dose); drawing 3 mL would deliver 750 mg (double).',
  },
  {
    id: 'math-s5-q5', subject: 'math', chapter: 5, type: 'mc',
    question: 'A 2 g vial of ampicillin is reconstituted by adding 6.8 mL of sterile water, yielding a final volume of 8 mL. What is the final concentration in mg/mL?',
    options: ['200 mg/mL', '250 mg/mL', '294 mg/mL', '400 mg/mL'],
    answer: 1,
    explanation: '2 g = 2,000 mg ÷ 8 mL final volume = 250 mg/mL. Note: 6.8 mL was added but 8 mL is the final volume — the powder displaces 1.2 mL. Final concentration always uses total final volume.',
  },
  {
    id: 'math-s5-q6', subject: 'math', chapter: 5, type: 'mc',
    question: 'Order: prednisone 15 mg PO. Available: 5 mg tablets (scored). How many tablets will the nurse administer?',
    options: ['1 tablet', '2 tablets', '3 tablets', '4 tablets'],
    answer: 2,
    explanation: 'D/H × Q = 15 mg ÷ 5 mg × 1 tablet = 3 tablets. Three tablets is the maximum generally accepted for a single dose. The tablets are scored, though splitting isn\'t needed here since 3 whole tablets achieve the exact dose.',
  },
  {
    id: 'math-s5-q7', subject: 'math', chapter: 5, type: 'mc',
    question: 'A nurse receives an order for a medication that would require giving 4 tablets per dose. What is the priority nursing action?',
    options: [
      'Administer all 4 tablets since the D/H × Q calculation is correct',
      'Hold the medication and contact the prescriber — 4 tablets per dose exceeds safe practice',
      'Give 3 tablets and discard the fourth',
      'Split two of the tablets in half and give the equivalent amount',
    ],
    answer: 1,
    explanation: 'The general safety rule is to give NO MORE than 3 tablets per dose. Needing 4 tablets signals a likely order error or incorrect supply — the nurse should contact the prescriber to clarify before administering.',
  },
  {
    id: 'math-s5-q8', subject: 'math', chapter: 5, type: 'mc',
    question: 'Which of the following tablets CAN be safely split in half if needed for dosing?',
    options: [
      'Enteric-coated aspirin',
      'Extended-release metformin (XR)',
      'Scored lisinopril tablet',
      'Sublingual nitroglycerin tablet',
    ],
    answer: 2,
    explanation: 'Scored tablets are designed to be split and the score line marks the splitting point. Enteric-coated tablets cannot be split (removes the protective coating); extended-release tablets cannot be split (alters release mechanism); sublingual tablets cannot be split (alters absorption).',
    term: 'Scored tablet', definition: 'A tablet with an indented line (score) manufactured specifically to be split in half; the only type of tablet that can safely be divided for dosing adjustments.',
  },
  {
    id: 'math-s5-q9', subject: 'math', chapter: 5, type: 'mc',
    question: 'What is the purpose of adding a diluent (such as sterile water) to a powdered medication vial?',
    options: [
      'To increase the potency of the medication',
      'To dissolve the powder and create a solution that can be measured and administered',
      'To decrease the final concentration for safety',
      'To change the route of administration from IV to IM',
    ],
    answer: 1,
    explanation: 'Reconstitution dissolves the lyophilized (freeze-dried) powder to create a solution. The resulting solution has a predictable concentration (final drug ÷ final volume) that the nurse then uses to calculate the correct dose volume.',
    term: 'Reconstitution', definition: 'Adding a specified amount of diluent (sterile water, NS) to a powder medication to create a solution; the final concentration = total drug ÷ total final volume.',
  },
  {
    id: 'math-s5-q10', subject: 'math', chapter: 5, type: 'mc',
    question: 'Order: ceftriaxone 750 mg IM. A 1 g vial is reconstituted with 3.6 mL sterile water for a final volume of 4 mL (250 mg/mL). How many mL should the nurse administer?',
    options: ['2 mL', '2.5 mL', '3 mL', '4 mL'],
    answer: 2,
    explanation: 'D/H × Q = 750 mg ÷ 250 mg/mL × 1 mL = 3 mL. Or via DA: 750 mg × (1 mL ÷ 250 mg) = 3 mL. The mg cancel, leaving 3 mL. This is within acceptable IM injection volume range.',
  },
  {
    id: 'math-s5-q11', subject: 'math', chapter: 5, type: 'mc',
    question: 'What is the difference between reconstitution and dilution?',
    options: [
      'They are the same process',
      'Reconstitution adds diluent to a DRY powder; dilution adds more fluid to an ALREADY DISSOLVED solution',
      'Reconstitution is used only for IV medications; dilution is used only for oral medications',
      'Dilution is done by the nurse; reconstitution is done by the pharmacist only',
    ],
    answer: 1,
    explanation: 'Reconstitution = dissolving dry powder with a diluent (creating a solution from powder). Dilution = adding more fluid to a solution that is already dissolved (to reduce concentration). Both may occur with the same medication (reconstitute first, then dilute for IV infusion).',
    term: 'Dilution', definition: 'Adding additional fluid to an already-dissolved medication to reduce its concentration; different from reconstitution, which creates a solution from powder.',
  },
  {
    id: 'math-s5-q12', subject: 'math', chapter: 5, type: 'mc',
    question: 'Order: azithromycin 0.5 g PO. Available: 250 mg tablets. How many tablets should the nurse give?',
    options: ['0.5 tablet', '1 tablet', '2 tablets', '4 tablets'],
    answer: 2,
    explanation: '0.5 g = 500 mg (convert first). D/H × Q = 500 mg ÷ 250 mg × 1 tablet = 2 tablets. Unit conversion (g → mg) is required before using the formula. This is within the safe range (≤3 tablets).',
  },
  {
    id: 'math-s5-q13', subject: 'math', chapter: 5, type: 'mc',
    question: 'A nurse reconstitutes a 500 mg vial of vancomycin powder by adding 10 mL of sterile water. The final volume after reconstitution is 10 mL (the powder does not displace significant volume). What is the final concentration?',
    options: ['5 mg/mL', '50 mg/mL', '500 mg/mL', '5,000 mg/mL'],
    answer: 1,
    explanation: '500 mg ÷ 10 mL = 50 mg/mL. This is the initial reconstituted concentration — pharmacy will then typically dilute this further (e.g., into 250 mL NS) before IV infusion. Always verify both reconstitution and dilution instructions.',
  },
  {
    id: 'math-s5-q14', subject: 'math', chapter: 5, type: 'tf',
    question: 'TRUE or FALSE: An extended-release (XR) tablet can be cut in half as long as it is scored.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Extended-release tablets CANNOT be cut, crushed, or chewed regardless of scoring, because altering them destroys the extended-release mechanism and delivers the full dose at once — a potentially fatal overdose for many XR medications.',
  },
  {
    id: 'math-s5-q15', subject: 'math', chapter: 5, type: 'tf',
    question: 'TRUE or FALSE: When calculating the final concentration of a reconstituted medication, the nurse should divide the total drug by the volume of diluent ADDED, not the final total volume.',
    options: ['True', 'False'],
    answer: 1,
    explanation: 'False. Final concentration = total drug ÷ FINAL VOLUME (not diluent added). The powder itself displaces some volume. Always use the total final volume after reconstitution, which will be slightly larger than the diluent volume added.',
  },
  {
    id: 'math-s5-q16', subject: 'math', chapter: 5, type: 'sata',
    question: 'A nurse is preparing to administer oral tablets. Select ALL types of tablets that CANNOT be safely split or crushed.',
    options: [
      'Enteric-coated tablets',
      'Scored immediate-release tablets',
      'Extended-release (XR/ER) capsules',
      'Sublingual tablets',
      'Unscored tablets',
    ],
    answer: 0,
    answers: [0, 2, 3, 4],
    explanation: 'Cannot split/crush: enteric-coated ✓ (removes protective coating), extended-release ✓ (causes dose dumping), sublingual ✓ (alters absorption mechanism), unscored ✓ (no designated split point, inaccurate dosing). Scored immediate-release tablets are designed to be split.',
  },
  {
    id: 'math-s5-q17', subject: 'math', chapter: 5, type: 'sata',
    question: 'Select ALL statements that are TRUE about medication reconstitution.',
    options: [
      'The final concentration equals total drug divided by total final volume',
      'The volume of diluent added always equals the final volume',
      'The powder in the vial displaces some volume upon reconstitution',
      'Always follow the manufacturer\'s or pharmacist\'s reconstitution instructions',
      'The diluent type (sterile water vs. NS) never matters for reconstitution',
    ],
    answer: 0,
    answers: [0, 2, 3],
    explanation: 'True: final concentration = drug ÷ final volume ✓, powder displaces volume ✓, always follow instructions ✓. False: diluent volume ≠ final volume (powder adds volume); diluent type DOES matter (some drugs are incompatible with certain diluents).',
  },
  {
    id: 'math-s5-q18', subject: 'math', chapter: 5, type: 'sata',
    question: 'A nurse is using the D/H × Q formula for oral medications. Select ALL statements that represent correct application of this formula.',
    options: [
      '"D" = the dose ordered (desired)',
      '"H" = the dose on hand (available supply per tablet/mL)',
      '"Q" = the quantity of the supply form (e.g., 1 tablet, 5 mL)',
      '"D" = the diluent added during reconstitution',
      'The formula can only be used for tablets, not liquids',
    ],
    answer: 0,
    answers: [0, 1, 2],
    explanation: 'D = desired (ordered) ✓, H = have (available concentration) ✓, Q = quantity of the supply form ✓. "D" is never the diluent. D/H × Q works for both tablets and oral liquids (mL).',
  },
  {
    id: 'math-s5-q19', subject: 'math', chapter: 5, type: 'priority',
    question: 'A nurse receives an order to reconstitute and administer a powdered antibiotic. Place the steps in the CORRECT PRIORITY ORDER.',
    options: [
      'Administer the calculated volume to the patient',
      'Read the manufacturer\'s reconstitution instructions for diluent type and volume',
      'Calculate the dose volume using D/H × Q or DA',
      'Add the specified diluent volume to the powder and mix to dissolve',
    ],
    answer: 1,
    explanation: 'Priority: (1) Read reconstitution instructions (diluent type and volume), (2) Add diluent and dissolve the powder, (3) Calculate dose volume using final concentration, (4) Administer. You must know the final concentration before calculating the dose.',
  },
  {
    id: 'math-s5-q20', subject: 'math', chapter: 5, type: 'priority',
    question: 'A nurse calculates that a patient needs 4.5 tablets of a medication per dose. What is the PRIORITY nursing action?',
    options: [
      'Administer 4.5 tablets as calculated — the math is correct',
      'Give 4 whole tablets and discard the 0.5 tablet',
      'Hold the medication and contact the prescriber — the number of tablets exceeds safe limits',
      'Split a tablet to make the 0.5 and give all 4.5',
    ],
    answer: 2,
    explanation: 'Giving more than 3 tablets per dose is a safety red flag. 4.5 tablets almost certainly indicates a calculation error, wrong supply, or ordering error. The nurse must HOLD and clarify with the prescriber before administering — patient safety overrides completing the task.',
  },
]
