 'use client'
import {useEffect,useState} from 'react'
import {getSupabaseBrowser} from '@/lib/filmroom-supabase-browser'
export function CustomClipTags({selected,toggle}:{selected:string[];toggle:(tag:string)=>void}){
 const [key,setKey]=useState('');const [tags,setTags]=useState<string[]>([]);const [draft,setDraft]=useState('');const [manage,setManage]=useState(false)
 useEffect(()=>{let active=true;getSupabaseBrowser().auth.getUser().then(({data})=>{if(!active||!data.user)return;const k=`filmroom:clipTags:${data.user.id}`;setKey(k);try{const saved=JSON.parse(localStorage.getItem(k)||'[]');if(Array.isArray(saved))setTags(saved.filter(t=>typeof t==='string').slice(0,24))}catch{}});return()=>{active=false}},[])
 function save(next:string[]){setTags(next);if(key)try{localStorage.setItem(key,JSON.stringify(next))}catch{}}
 return <fieldset className="space-y-2"><legend className="text-xs text-[#c9c3b8]">Your quick tags</legend><div className="flex flex-wrap gap-2">{tags.map(tag=><button key={tag} type="button" aria-pressed={selected.includes(tag)} onClick={()=>toggle(tag)} className={`min-h-9 rounded border px-3 text-xs ${selected.includes(tag)?'border-[#e49269] text-[#e49269]':'border-white/20 text-[#c9c3b8]'}`}>{tag}</button>)}<button type="button" onClick={()=>setManage(!manage)} className="min-h-9 text-xs text-[#e49269]">Customize</button></div>{manage&&<div className="space-y-2 rounded border border-white/15 p-3"><p className="text-xs text-[#c9c3b8]">Saved for your account on this browser.</p><label className="block text-xs">New quick tag<input maxLength={40} value={draft} onChange={e=>setDraft(e.target.value)} className="mt-1 w-full rounded border border-white/20 bg-black/20 p-2"/></label><button type="button" disabled={!key||!draft.trim()||tags.length>=24} className="min-h-9 text-xs text-[#e49269]" onClick={()=>{const tag=draft.trim().replaceAll(',','');if(tag)save([...new Set([...tags,tag])]);setDraft('')}}>Add quick tag</button>{tags.map(t=><button key={t} type="button" className="block min-h-9 text-xs text-[#c9c3b8]" onClick={()=>save(tags.filter(x=>x!==t))}>Remove {t}</button>)}</div>}</fieldset>
}
