 'use client'
import {useState} from 'react'
import type {PlaylistClip,SessionPlan} from '@/types/filmroom'
export function SessionPlanner({playlistId,initial,clips,onSelect}:{playlistId:string;initial?:SessionPlan;clips:PlaylistClip[];onSelect:(index:number)=>void}){
 const [plan,setPlan]=useState<SessionPlan>(initial||{objective:'',sections:[]});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
 const patch=(i:number,v:Partial<SessionPlan['sections'][number]>)=>{setMessage('');setPlan(p=>({...p,sections:p.sections.map((s,j)=>i===j?{...s,...v}:s)}))}
 async function save(){setBusy(true);setMessage('');setError('');try{const liveIds=new Set(clips.map(c=>c.clip_id));const clean={...plan,sections:plan.sections.map(s=>({...s,clip_ids:s.clip_ids.filter(id=>liveIds.has(id))}))};const r=await fetch(`/api/filmroom/playlists/${playlistId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_plan:clean})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save session.');setPlan(clean);setMessage('Session plan saved.')}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
 const seconds=Math.round(clips.reduce((n,c)=>n+Math.max(0,(c.clip?.end_time_ms||0)-(c.clip?.start_time_ms||0)),0)/1000)
 const field='mt-1 w-full rounded border border-white/20 bg-[#181917] p-2 text-sm'
 return <section className="space-y-4 border-t border-white/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-bold" style={{fontFamily:'var(--font-bc)'}}>Film session plan</h2><span className="text-sm text-[#c9c3b8]">{Math.floor(seconds/60)}m {seconds%60}s of film · plus discussion</span></div><label className="block text-sm">Session objective<textarea maxLength={2000} rows={2} className={field} placeholder="What should players understand by the end?" value={plan.objective} onChange={e=>{setMessage('');setPlan({...plan,objective:e.target.value})}}/></label>{plan.sections.map((s,i)=><div key={s.id} className="space-y-3 rounded border border-white/15 p-4"><div className="flex items-center justify-between"><h3 className="font-bold">Section {i+1}</h3><button onClick={()=>setPlan({...plan,sections:plan.sections.filter((_,j)=>i!==j)})} className="min-h-11 px-2 text-sm text-[#c9c3b8]">Remove section</button></div><label className="block text-sm">Title<input maxLength={120} className={field} value={s.title} onChange={e=>patch(i,{title:e.target.value})}/></label><label className="block text-sm">Teaching point<textarea maxLength={1000} className={field} value={s.objective} onChange={e=>patch(i,{objective:e.target.value})}/></label><fieldset><legend className="text-sm text-[#c9c3b8]">Clips in this section</legend>{clips.length===0&&<p className="text-sm">Add clips to the playlist to assign them here.</p>}{clips.map((c,index)=><div key={c.id} className="flex items-center gap-3 py-1"><label className="flex min-h-11 flex-1 items-center gap-2 text-sm"><input type="checkbox" checked={s.clip_ids.includes(c.clip_id)} onChange={e=>patch(i,{clip_ids:e.target.checked?[...s.clip_ids,c.clip_id]:s.clip_ids.filter(id=>id!==c.clip_id)})}/>{c.clip?.title||'Untitled clip'}</label><button onClick={()=>onSelect(index)} className="min-h-11 text-sm text-[#e49269]">Review</button></div>)}</fieldset></div>)}<div className="flex flex-wrap gap-3"><button disabled={plan.sections.length>=30} className="min-h-11 rounded border border-white/20 px-4 text-sm" onClick={()=>setPlan({...plan,sections:[...plan.sections,{id:crypto.randomUUID(),title:`Teaching point ${plan.sections.length+1}`,objective:'',clip_ids:[]}]})}>Add teaching section</button><button disabled={busy} onClick={save} className="min-h-11 rounded bg-[#c66a3e] px-4 font-semibold text-[#181917]">{busy?'Saving…':'Save session plan'}</button></div>{message&&<p role="status" className="text-sm text-[#e49269]">{message}</p>}{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}</section>
}
