'use client'
import {useState} from 'react'
import {Play,Film,ArrowUpRight} from 'lucide-react'
import {VideoThumbnail,formatGameDate} from '../components/cs-shared'
import type {SharedGame} from './ParentGameView'
export function FamilyLibrary({games,onOpen}:{games:SharedGame[];onOpen:(game:SharedGame)=>void}){
 const [team,setTeam]=useState('all')
 const teams=Array.from(new Set(games.map(g=>g.team)))
 const filtered=games.filter(g=>team==='all'||g.team===team).sort((a,b)=>b.game_date.localeCompare(a.game_date))
 const latest=filtered[0]
 const preview=(g:SharedGame,className:string)=>g.film&&g.has_video?<VideoThumbnail gameId={g.id} className={className}/>:<div className={className+' flex items-center justify-center bg-[#111210] text-[#aaa89f]'}><Film className="mr-2 h-6 w-6"/>{g.film?'Awaiting film':'Stats & shot chart'}</div>
 return <section className="mx-auto max-w-[1440px] space-y-6" aria-label="Shared games">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-[#e49269]">Your team. Your film.</p><h1 className="mt-1 text-5xl font-black uppercase" style={{fontFamily:'var(--font-bc)'}}>Film library</h1><p className="mt-2 text-sm text-[#c9c3b8]">{filtered.length} shared {filtered.length===1?'game':'games'} · Film, clips, and stats from your coach.</p></div>{teams.length>1&&<label className="text-xs text-[#c9c3b8]">Team<select value={team} onChange={e=>setTeam(e.target.value)} className="ml-3 min-h-11 rounded border border-white/15 bg-[#252621] px-3 text-sm"><option value="all">All teams</option>{teams.map(t=><option key={t}>{t}</option>)}</select></label>}</div>
  {latest&&<button onClick={()=>onOpen(latest)} className="group grid w-full overflow-hidden rounded-lg border border-white/15 bg-[#20211e] text-left hover:border-[#c66a3e] md:grid-cols-[1.6fr_1fr]" aria-label={`Open latest game: ${latest.opponent}`}><div className="relative">{preview(latest,'aspect-video')}<span className="absolute left-4 top-4 rounded bg-[#181917]/90 px-3 py-1 text-xs font-bold uppercase tracking-wider text-[#e49269]">Latest film</span><span className="absolute bottom-4 right-4 flex h-12 w-12 items-center justify-center rounded-full bg-[#c66a3e] text-white"><Play className="h-5 w-5"/></span></div><div className="flex flex-col justify-center p-6 lg:p-9"><p className="text-xs uppercase tracking-[.15em] text-[#e49269]">{latest.team}</p><h2 className="mt-3 text-4xl font-black uppercase leading-none lg:text-5xl" style={{fontFamily:'var(--font-bc)'}}>{latest.opponent}</h2><p className="mt-4 text-sm text-[#c9c3b8]">{formatGameDate(latest.game_date)}</p><span className="mt-7 inline-flex items-center gap-2 font-semibold">{latest.film?'Open game film':'View game stats'}<ArrowUpRight className="h-5 w-5 text-[#e49269]"/></span></div></button>}
  <div><h2 className="mb-3 text-xl font-bold uppercase tracking-wide" style={{fontFamily:'var(--font-bc)'}}>All games</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(g=><button key={g.id} onClick={()=>onOpen(g)} className="group overflow-hidden rounded-md border border-white/10 bg-[#1e1f1d] text-left hover:border-[#c66a3e]">{preview(g,'aspect-video')}<div className="p-4"><p className="text-xs text-[#e49269]">{g.team} · {formatGameDate(g.game_date)}</p><h3 className="mt-2 text-2xl font-bold uppercase" style={{fontFamily:'var(--font-bc)'}}>{g.opponent}</h3><p className="mt-3 flex items-center justify-between text-xs text-[#c9c3b8]"><span>{[g.film?'Film & clips':null,g.stats?'Box score & shots':null].filter(Boolean).join(' · ')}</span><ArrowUpRight className="h-4 w-4"/></p></div></button>)}</div></div>
 </section>
}
