 'use client'
import {FamilyLibrary} from './FamilyLibrary'
import {ParentGameView, type SharedGame as Game} from './ParentGameView'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {LogoutButton} from '../components/LogoutButton'
type Invitation={id:string;team:string;accepted:boolean;expires_at:string}
export default function Family(){
 const [games,setGames]=useState<Game[]>([]),[invites,setInvites]=useState<Invitation[]>([]),[selected,setSelected]=useState<Game|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false)
 const [email,setEmail]=useState('')
 async function load(){const r=await fetch('/api/filmroom/family',{cache:'no-store'});if(!r.ok)throw Error('Could not load shared games.');const d=await r.json();setGames(d.games);setInvites(d.invitations);setEmail(d.email||'');setReady(true);setSelected(old=>old?d.games.find((g:Game)=>g.id===old.id)||null:null)}
 useEffect(()=>{void load().catch(e=>setError(e.message));const timer=setInterval(()=>{void load().catch(()=>{})},40000);return()=>clearInterval(timer)},[])
 async function accept(id:string){setBusy(true);setError('');try{const r=await fetch('/api/filmroom/family',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)throw Error(d.error);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="cs min-h-screen bg-[#181917] text-[#eee9df]"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 px-5 py-4"><Link href="/filmroom/family" className="font-semibold text-lg">Film Room <span className="ml-2 text-sm text-[#e49269]">Family view</span></Link><div className="flex flex-wrap items-center gap-4"><Link href="/filmroom?view=coach" className="min-h-11 inline-flex items-center text-sm">Coach library</Link><LogoutButton/></div></header><main className="mx-auto max-w-[1800px] space-y-6 px-4 py-8">{error&&<p role="alert" className="text-red-300">{error} <button className="underline" onClick={()=>{setError('');void load().catch(e=>setError(e.message))}}>Retry</button></p>}{!ready&&!error&&<p role="status">Loading your invitations…</p>}{invites.filter(i=>!i.accepted).map(i=><section key={i.id} className="flex flex-wrap items-center justify-between gap-4 rounded-lg border border-[#c66a3e]/50 p-5"><div><h2 className="text-xl font-semibold">Join {i.team}</h2><p className="mt-1 text-sm text-[#c9c3b8]">Your coach invited you to view shared film and stats.</p></div><button disabled={busy} onClick={()=>void accept(i.id)} className="min-h-11 rounded bg-[#c66a3e] px-5 font-semibold text-[#181917] disabled:opacity-50">Join team & view games</button></section>)}{ready&&!games.length&&!invites.some(i=>!i.accepted)&&<section className="rounded-lg border border-white/15 p-6"><h2 className="font-semibold">No shared games yet</h2><p className="mt-2 text-[#c9c3b8]">{invites.some(i=>i.accepted)?'You have joined your team. Your coach has not shared any games with you yet.':'No invitation was found for this email. Ask your coach to invite the email shown above.'}</p></section>}{selected?<ParentGameView key={selected.id} game={selected} onBack={()=>setSelected(null)}/>:<FamilyLibrary games={games} onOpen={g=>{setError('');setSelected(g)}}/>}{!selected&&<footer className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-3 border-t border-white/10 py-4 text-xs text-[#c9c3b8]"><span>Signed in as {email} · Parent viewing is free</span><Link href="/filmroom/billing" className="min-h-11 inline-flex items-center gap-2 text-[#e49269]">Coach your own team? Explore Coach →</Link></footer>}</main></div>
}
